// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GRAMMARRULES_GRAMMARRULES_H_
#define FLATBUFFERS_GENERATED_GRAMMARRULES_GRAMMARRULES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace GrammarRules {

struct GrammarComponent;
struct GrammarComponentBuilder;

struct CommandVerb;
struct CommandVerbBuilder;

struct CommandObject;
struct CommandObjectBuilder;

struct SentenceTemplate;
struct SentenceTemplateBuilder;

struct ContextRule;
struct ContextRuleBuilder;

struct LearningConfig;
struct LearningConfigBuilder;

struct GrammarConfig;
struct GrammarConfigBuilder;

struct GrammarComponent FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GrammarComponentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DESCRIPTION = 6,
    VT_PATTERNS = 8,
    VT_OPTIONAL = 10,
    VT_CAPTURE = 12,
    VT_REQUIRES_CONTEXT = 14,
    VT_FREQUENCY = 16,
    VT_WEIGHT = 18
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *patterns() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_PATTERNS);
  }
  bool optional() const {
    return GetField<uint8_t>(VT_OPTIONAL, 0) != 0;
  }
  bool capture() const {
    return GetField<uint8_t>(VT_CAPTURE, 0) != 0;
  }
  bool requires_context() const {
    return GetField<uint8_t>(VT_REQUIRES_CONTEXT, 0) != 0;
  }
  int32_t frequency() const {
    return GetField<int32_t>(VT_FREQUENCY, 0);
  }
  float weight() const {
    return GetField<float>(VT_WEIGHT, 1.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyOffset(verifier, VT_PATTERNS) &&
           verifier.VerifyVector(patterns()) &&
           verifier.VerifyVectorOfStrings(patterns()) &&
           VerifyField<uint8_t>(verifier, VT_OPTIONAL, 1) &&
           VerifyField<uint8_t>(verifier, VT_CAPTURE, 1) &&
           VerifyField<uint8_t>(verifier, VT_REQUIRES_CONTEXT, 1) &&
           VerifyField<int32_t>(verifier, VT_FREQUENCY, 4) &&
           VerifyField<float>(verifier, VT_WEIGHT, 4) &&
           verifier.EndTable();
  }
};

struct GrammarComponentBuilder {
  typedef GrammarComponent Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(GrammarComponent::VT_NAME, name);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(GrammarComponent::VT_DESCRIPTION, description);
  }
  void add_patterns(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> patterns) {
    fbb_.AddOffset(GrammarComponent::VT_PATTERNS, patterns);
  }
  void add_optional(bool optional) {
    fbb_.AddElement<uint8_t>(GrammarComponent::VT_OPTIONAL, static_cast<uint8_t>(optional), 0);
  }
  void add_capture(bool capture) {
    fbb_.AddElement<uint8_t>(GrammarComponent::VT_CAPTURE, static_cast<uint8_t>(capture), 0);
  }
  void add_requires_context(bool requires_context) {
    fbb_.AddElement<uint8_t>(GrammarComponent::VT_REQUIRES_CONTEXT, static_cast<uint8_t>(requires_context), 0);
  }
  void add_frequency(int32_t frequency) {
    fbb_.AddElement<int32_t>(GrammarComponent::VT_FREQUENCY, frequency, 0);
  }
  void add_weight(float weight) {
    fbb_.AddElement<float>(GrammarComponent::VT_WEIGHT, weight, 1.0f);
  }
  explicit GrammarComponentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GrammarComponent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GrammarComponent>(end);
    fbb_.Required(o, GrammarComponent::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<GrammarComponent> CreateGrammarComponent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> patterns = 0,
    bool optional = false,
    bool capture = false,
    bool requires_context = false,
    int32_t frequency = 0,
    float weight = 1.0f) {
  GrammarComponentBuilder builder_(_fbb);
  builder_.add_weight(weight);
  builder_.add_frequency(frequency);
  builder_.add_patterns(patterns);
  builder_.add_description(description);
  builder_.add_name(name);
  builder_.add_requires_context(requires_context);
  builder_.add_capture(capture);
  builder_.add_optional(optional);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GrammarComponent> CreateGrammarComponentDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *description = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *patterns = nullptr,
    bool optional = false,
    bool capture = false,
    bool requires_context = false,
    int32_t frequency = 0,
    float weight = 1.0f) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto patterns__ = patterns ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*patterns) : 0;
  return GrammarRules::CreateGrammarComponent(
      _fbb,
      name__,
      description__,
      patterns__,
      optional,
      capture,
      requires_context,
      frequency,
      weight);
}

struct CommandVerb FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CommandVerbBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CANONICAL = 4,
    VT_SYNONYMS = 6,
    VT_INTENT = 8,
    VT_REQUIRES_OBJECT = 10,
    VT_FREQUENCY = 12,
    VT_WEIGHT = 14,
    VT_PIPELINE_CATEGORY = 16
  };
  const ::flatbuffers::String *canonical() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CANONICAL);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *synonyms() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_SYNONYMS);
  }
  const ::flatbuffers::String *intent() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INTENT);
  }
  bool requires_object() const {
    return GetField<uint8_t>(VT_REQUIRES_OBJECT, 0) != 0;
  }
  int32_t frequency() const {
    return GetField<int32_t>(VT_FREQUENCY, 0);
  }
  float weight() const {
    return GetField<float>(VT_WEIGHT, 1.0f);
  }
  const ::flatbuffers::String *pipeline_category() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PIPELINE_CATEGORY);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CANONICAL) &&
           verifier.VerifyString(canonical()) &&
           VerifyOffset(verifier, VT_SYNONYMS) &&
           verifier.VerifyVector(synonyms()) &&
           verifier.VerifyVectorOfStrings(synonyms()) &&
           VerifyOffset(verifier, VT_INTENT) &&
           verifier.VerifyString(intent()) &&
           VerifyField<uint8_t>(verifier, VT_REQUIRES_OBJECT, 1) &&
           VerifyField<int32_t>(verifier, VT_FREQUENCY, 4) &&
           VerifyField<float>(verifier, VT_WEIGHT, 4) &&
           VerifyOffset(verifier, VT_PIPELINE_CATEGORY) &&
           verifier.VerifyString(pipeline_category()) &&
           verifier.EndTable();
  }
};

struct CommandVerbBuilder {
  typedef CommandVerb Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_canonical(::flatbuffers::Offset<::flatbuffers::String> canonical) {
    fbb_.AddOffset(CommandVerb::VT_CANONICAL, canonical);
  }
  void add_synonyms(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> synonyms) {
    fbb_.AddOffset(CommandVerb::VT_SYNONYMS, synonyms);
  }
  void add_intent(::flatbuffers::Offset<::flatbuffers::String> intent) {
    fbb_.AddOffset(CommandVerb::VT_INTENT, intent);
  }
  void add_requires_object(bool requires_object) {
    fbb_.AddElement<uint8_t>(CommandVerb::VT_REQUIRES_OBJECT, static_cast<uint8_t>(requires_object), 0);
  }
  void add_frequency(int32_t frequency) {
    fbb_.AddElement<int32_t>(CommandVerb::VT_FREQUENCY, frequency, 0);
  }
  void add_weight(float weight) {
    fbb_.AddElement<float>(CommandVerb::VT_WEIGHT, weight, 1.0f);
  }
  void add_pipeline_category(::flatbuffers::Offset<::flatbuffers::String> pipeline_category) {
    fbb_.AddOffset(CommandVerb::VT_PIPELINE_CATEGORY, pipeline_category);
  }
  explicit CommandVerbBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CommandVerb> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CommandVerb>(end);
    fbb_.Required(o, CommandVerb::VT_CANONICAL);
    return o;
  }
};

inline ::flatbuffers::Offset<CommandVerb> CreateCommandVerb(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> canonical = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> synonyms = 0,
    ::flatbuffers::Offset<::flatbuffers::String> intent = 0,
    bool requires_object = false,
    int32_t frequency = 0,
    float weight = 1.0f,
    ::flatbuffers::Offset<::flatbuffers::String> pipeline_category = 0) {
  CommandVerbBuilder builder_(_fbb);
  builder_.add_pipeline_category(pipeline_category);
  builder_.add_weight(weight);
  builder_.add_frequency(frequency);
  builder_.add_intent(intent);
  builder_.add_synonyms(synonyms);
  builder_.add_canonical(canonical);
  builder_.add_requires_object(requires_object);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CommandVerb> CreateCommandVerbDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *canonical = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *synonyms = nullptr,
    const char *intent = nullptr,
    bool requires_object = false,
    int32_t frequency = 0,
    float weight = 1.0f,
    const char *pipeline_category = nullptr) {
  auto canonical__ = canonical ? _fbb.CreateString(canonical) : 0;
  auto synonyms__ = synonyms ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*synonyms) : 0;
  auto intent__ = intent ? _fbb.CreateString(intent) : 0;
  auto pipeline_category__ = pipeline_category ? _fbb.CreateString(pipeline_category) : 0;
  return GrammarRules::CreateCommandVerb(
      _fbb,
      canonical__,
      synonyms__,
      intent__,
      requires_object,
      frequency,
      weight,
      pipeline_category__);
}

struct CommandObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CommandObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CANONICAL = 4,
    VT_SYNONYMS = 6,
    VT_CATEGORY = 8,
    VT_FREQUENCY = 10,
    VT_WEIGHT = 12
  };
  const ::flatbuffers::String *canonical() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CANONICAL);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *synonyms() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_SYNONYMS);
  }
  const ::flatbuffers::String *category() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CATEGORY);
  }
  int32_t frequency() const {
    return GetField<int32_t>(VT_FREQUENCY, 0);
  }
  float weight() const {
    return GetField<float>(VT_WEIGHT, 1.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CANONICAL) &&
           verifier.VerifyString(canonical()) &&
           VerifyOffset(verifier, VT_SYNONYMS) &&
           verifier.VerifyVector(synonyms()) &&
           verifier.VerifyVectorOfStrings(synonyms()) &&
           VerifyOffset(verifier, VT_CATEGORY) &&
           verifier.VerifyString(category()) &&
           VerifyField<int32_t>(verifier, VT_FREQUENCY, 4) &&
           VerifyField<float>(verifier, VT_WEIGHT, 4) &&
           verifier.EndTable();
  }
};

struct CommandObjectBuilder {
  typedef CommandObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_canonical(::flatbuffers::Offset<::flatbuffers::String> canonical) {
    fbb_.AddOffset(CommandObject::VT_CANONICAL, canonical);
  }
  void add_synonyms(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> synonyms) {
    fbb_.AddOffset(CommandObject::VT_SYNONYMS, synonyms);
  }
  void add_category(::flatbuffers::Offset<::flatbuffers::String> category) {
    fbb_.AddOffset(CommandObject::VT_CATEGORY, category);
  }
  void add_frequency(int32_t frequency) {
    fbb_.AddElement<int32_t>(CommandObject::VT_FREQUENCY, frequency, 0);
  }
  void add_weight(float weight) {
    fbb_.AddElement<float>(CommandObject::VT_WEIGHT, weight, 1.0f);
  }
  explicit CommandObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CommandObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CommandObject>(end);
    fbb_.Required(o, CommandObject::VT_CANONICAL);
    return o;
  }
};

inline ::flatbuffers::Offset<CommandObject> CreateCommandObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> canonical = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> synonyms = 0,
    ::flatbuffers::Offset<::flatbuffers::String> category = 0,
    int32_t frequency = 0,
    float weight = 1.0f) {
  CommandObjectBuilder builder_(_fbb);
  builder_.add_weight(weight);
  builder_.add_frequency(frequency);
  builder_.add_category(category);
  builder_.add_synonyms(synonyms);
  builder_.add_canonical(canonical);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CommandObject> CreateCommandObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *canonical = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *synonyms = nullptr,
    const char *category = nullptr,
    int32_t frequency = 0,
    float weight = 1.0f) {
  auto canonical__ = canonical ? _fbb.CreateString(canonical) : 0;
  auto synonyms__ = synonyms ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*synonyms) : 0;
  auto category__ = category ? _fbb.CreateString(category) : 0;
  return GrammarRules::CreateCommandObject(
      _fbb,
      canonical__,
      synonyms__,
      category__,
      frequency,
      weight);
}

struct SentenceTemplate FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SentenceTemplateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_STRUCTURE = 6,
    VT_EXAMPLES = 8,
    VT_REQUIRES_CONTEXT = 10,
    VT_CATEGORY = 12,
    VT_FREQUENCY = 14,
    VT_WEIGHT = 16,
    VT_PIPELINE_CATEGORY = 18,
    VT_AVG_DEPTH = 20,
    VT_COMMON_MODIFIERS = 22
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *structure() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STRUCTURE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *examples() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_EXAMPLES);
  }
  bool requires_context() const {
    return GetField<uint8_t>(VT_REQUIRES_CONTEXT, 0) != 0;
  }
  const ::flatbuffers::String *category() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CATEGORY);
  }
  int32_t frequency() const {
    return GetField<int32_t>(VT_FREQUENCY, 0);
  }
  float weight() const {
    return GetField<float>(VT_WEIGHT, 1.0f);
  }
  const ::flatbuffers::String *pipeline_category() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PIPELINE_CATEGORY);
  }
  float avg_depth() const {
    return GetField<float>(VT_AVG_DEPTH, 0.0f);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *common_modifiers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_COMMON_MODIFIERS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffsetRequired(verifier, VT_STRUCTURE) &&
           verifier.VerifyString(structure()) &&
           VerifyOffset(verifier, VT_EXAMPLES) &&
           verifier.VerifyVector(examples()) &&
           verifier.VerifyVectorOfStrings(examples()) &&
           VerifyField<uint8_t>(verifier, VT_REQUIRES_CONTEXT, 1) &&
           VerifyOffset(verifier, VT_CATEGORY) &&
           verifier.VerifyString(category()) &&
           VerifyField<int32_t>(verifier, VT_FREQUENCY, 4) &&
           VerifyField<float>(verifier, VT_WEIGHT, 4) &&
           VerifyOffset(verifier, VT_PIPELINE_CATEGORY) &&
           verifier.VerifyString(pipeline_category()) &&
           VerifyField<float>(verifier, VT_AVG_DEPTH, 4) &&
           VerifyOffset(verifier, VT_COMMON_MODIFIERS) &&
           verifier.VerifyVector(common_modifiers()) &&
           verifier.VerifyVectorOfStrings(common_modifiers()) &&
           verifier.EndTable();
  }
};

struct SentenceTemplateBuilder {
  typedef SentenceTemplate Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SentenceTemplate::VT_NAME, name);
  }
  void add_structure(::flatbuffers::Offset<::flatbuffers::String> structure) {
    fbb_.AddOffset(SentenceTemplate::VT_STRUCTURE, structure);
  }
  void add_examples(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> examples) {
    fbb_.AddOffset(SentenceTemplate::VT_EXAMPLES, examples);
  }
  void add_requires_context(bool requires_context) {
    fbb_.AddElement<uint8_t>(SentenceTemplate::VT_REQUIRES_CONTEXT, static_cast<uint8_t>(requires_context), 0);
  }
  void add_category(::flatbuffers::Offset<::flatbuffers::String> category) {
    fbb_.AddOffset(SentenceTemplate::VT_CATEGORY, category);
  }
  void add_frequency(int32_t frequency) {
    fbb_.AddElement<int32_t>(SentenceTemplate::VT_FREQUENCY, frequency, 0);
  }
  void add_weight(float weight) {
    fbb_.AddElement<float>(SentenceTemplate::VT_WEIGHT, weight, 1.0f);
  }
  void add_pipeline_category(::flatbuffers::Offset<::flatbuffers::String> pipeline_category) {
    fbb_.AddOffset(SentenceTemplate::VT_PIPELINE_CATEGORY, pipeline_category);
  }
  void add_avg_depth(float avg_depth) {
    fbb_.AddElement<float>(SentenceTemplate::VT_AVG_DEPTH, avg_depth, 0.0f);
  }
  void add_common_modifiers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> common_modifiers) {
    fbb_.AddOffset(SentenceTemplate::VT_COMMON_MODIFIERS, common_modifiers);
  }
  explicit SentenceTemplateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SentenceTemplate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SentenceTemplate>(end);
    fbb_.Required(o, SentenceTemplate::VT_NAME);
    fbb_.Required(o, SentenceTemplate::VT_STRUCTURE);
    return o;
  }
};

inline ::flatbuffers::Offset<SentenceTemplate> CreateSentenceTemplate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> structure = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> examples = 0,
    bool requires_context = false,
    ::flatbuffers::Offset<::flatbuffers::String> category = 0,
    int32_t frequency = 0,
    float weight = 1.0f,
    ::flatbuffers::Offset<::flatbuffers::String> pipeline_category = 0,
    float avg_depth = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> common_modifiers = 0) {
  SentenceTemplateBuilder builder_(_fbb);
  builder_.add_common_modifiers(common_modifiers);
  builder_.add_avg_depth(avg_depth);
  builder_.add_pipeline_category(pipeline_category);
  builder_.add_weight(weight);
  builder_.add_frequency(frequency);
  builder_.add_category(category);
  builder_.add_examples(examples);
  builder_.add_structure(structure);
  builder_.add_name(name);
  builder_.add_requires_context(requires_context);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SentenceTemplate> CreateSentenceTemplateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *structure = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *examples = nullptr,
    bool requires_context = false,
    const char *category = nullptr,
    int32_t frequency = 0,
    float weight = 1.0f,
    const char *pipeline_category = nullptr,
    float avg_depth = 0.0f,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *common_modifiers = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto structure__ = structure ? _fbb.CreateString(structure) : 0;
  auto examples__ = examples ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*examples) : 0;
  auto category__ = category ? _fbb.CreateString(category) : 0;
  auto pipeline_category__ = pipeline_category ? _fbb.CreateString(pipeline_category) : 0;
  auto common_modifiers__ = common_modifiers ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*common_modifiers) : 0;
  return GrammarRules::CreateSentenceTemplate(
      _fbb,
      name__,
      structure__,
      examples__,
      requires_context,
      category__,
      frequency,
      weight,
      pipeline_category__,
      avg_depth,
      common_modifiers__);
}

struct ContextRule FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ContextRuleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONDITION = 4,
    VT_ACTION = 6,
    VT_PRIORITY = 8,
    VT_WEIGHT_MODIFIER = 10
  };
  const ::flatbuffers::String *condition() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONDITION);
  }
  const ::flatbuffers::String *action() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACTION);
  }
  int32_t priority() const {
    return GetField<int32_t>(VT_PRIORITY, 50);
  }
  float weight_modifier() const {
    return GetField<float>(VT_WEIGHT_MODIFIER, 1.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CONDITION) &&
           verifier.VerifyString(condition()) &&
           VerifyOffsetRequired(verifier, VT_ACTION) &&
           verifier.VerifyString(action()) &&
           VerifyField<int32_t>(verifier, VT_PRIORITY, 4) &&
           VerifyField<float>(verifier, VT_WEIGHT_MODIFIER, 4) &&
           verifier.EndTable();
  }
};

struct ContextRuleBuilder {
  typedef ContextRule Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_condition(::flatbuffers::Offset<::flatbuffers::String> condition) {
    fbb_.AddOffset(ContextRule::VT_CONDITION, condition);
  }
  void add_action(::flatbuffers::Offset<::flatbuffers::String> action) {
    fbb_.AddOffset(ContextRule::VT_ACTION, action);
  }
  void add_priority(int32_t priority) {
    fbb_.AddElement<int32_t>(ContextRule::VT_PRIORITY, priority, 50);
  }
  void add_weight_modifier(float weight_modifier) {
    fbb_.AddElement<float>(ContextRule::VT_WEIGHT_MODIFIER, weight_modifier, 1.0f);
  }
  explicit ContextRuleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ContextRule> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ContextRule>(end);
    fbb_.Required(o, ContextRule::VT_CONDITION);
    fbb_.Required(o, ContextRule::VT_ACTION);
    return o;
  }
};

inline ::flatbuffers::Offset<ContextRule> CreateContextRule(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> condition = 0,
    ::flatbuffers::Offset<::flatbuffers::String> action = 0,
    int32_t priority = 50,
    float weight_modifier = 1.0f) {
  ContextRuleBuilder builder_(_fbb);
  builder_.add_weight_modifier(weight_modifier);
  builder_.add_priority(priority);
  builder_.add_action(action);
  builder_.add_condition(condition);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ContextRule> CreateContextRuleDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *condition = nullptr,
    const char *action = nullptr,
    int32_t priority = 50,
    float weight_modifier = 1.0f) {
  auto condition__ = condition ? _fbb.CreateString(condition) : 0;
  auto action__ = action ? _fbb.CreateString(action) : 0;
  return GrammarRules::CreateContextRule(
      _fbb,
      condition__,
      action__,
      priority,
      weight_modifier);
}

struct LearningConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LearningConfigBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENABLE_ONLINE_LEARNING = 4,
    VT_MIN_CONFIDENCE_THRESHOLD = 6,
    VT_FEEDBACK_WEIGHT = 8,
    VT_DECAY_RATE = 10
  };
  bool enable_online_learning() const {
    return GetField<uint8_t>(VT_ENABLE_ONLINE_LEARNING, 1) != 0;
  }
  float min_confidence_threshold() const {
    return GetField<float>(VT_MIN_CONFIDENCE_THRESHOLD, 0.6f);
  }
  float feedback_weight() const {
    return GetField<float>(VT_FEEDBACK_WEIGHT, 0.3f);
  }
  float decay_rate() const {
    return GetField<float>(VT_DECAY_RATE, 0.95f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_ENABLE_ONLINE_LEARNING, 1) &&
           VerifyField<float>(verifier, VT_MIN_CONFIDENCE_THRESHOLD, 4) &&
           VerifyField<float>(verifier, VT_FEEDBACK_WEIGHT, 4) &&
           VerifyField<float>(verifier, VT_DECAY_RATE, 4) &&
           verifier.EndTable();
  }
};

struct LearningConfigBuilder {
  typedef LearningConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_enable_online_learning(bool enable_online_learning) {
    fbb_.AddElement<uint8_t>(LearningConfig::VT_ENABLE_ONLINE_LEARNING, static_cast<uint8_t>(enable_online_learning), 1);
  }
  void add_min_confidence_threshold(float min_confidence_threshold) {
    fbb_.AddElement<float>(LearningConfig::VT_MIN_CONFIDENCE_THRESHOLD, min_confidence_threshold, 0.6f);
  }
  void add_feedback_weight(float feedback_weight) {
    fbb_.AddElement<float>(LearningConfig::VT_FEEDBACK_WEIGHT, feedback_weight, 0.3f);
  }
  void add_decay_rate(float decay_rate) {
    fbb_.AddElement<float>(LearningConfig::VT_DECAY_RATE, decay_rate, 0.95f);
  }
  explicit LearningConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LearningConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LearningConfig>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LearningConfig> CreateLearningConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool enable_online_learning = true,
    float min_confidence_threshold = 0.6f,
    float feedback_weight = 0.3f,
    float decay_rate = 0.95f) {
  LearningConfigBuilder builder_(_fbb);
  builder_.add_decay_rate(decay_rate);
  builder_.add_feedback_weight(feedback_weight);
  builder_.add_min_confidence_threshold(min_confidence_threshold);
  builder_.add_enable_online_learning(enable_online_learning);
  return builder_.Finish();
}

struct GrammarConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GrammarConfigBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_LANGUAGE = 6,
    VT_TREEBANK_SOURCE = 8,
    VT_COMPONENTS = 10,
    VT_VERBS = 12,
    VT_OBJECTS = 14,
    VT_TEMPLATES = 16,
    VT_CONTEXT_RULES = 18,
    VT_LEARNING_CONFIG = 20,
    VT_GENERATED_TIMESTAMP = 22,
    VT_TOTAL_SENTENCES_ANALYZED = 24,
    VT_MERGE_STRATEGY = 26
  };
  int32_t version() const {
    return GetField<int32_t>(VT_VERSION, 1);
  }
  const ::flatbuffers::String *language() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LANGUAGE);
  }
  const ::flatbuffers::String *treebank_source() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TREEBANK_SOURCE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::GrammarComponent>> *components() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::GrammarComponent>> *>(VT_COMPONENTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::CommandVerb>> *verbs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::CommandVerb>> *>(VT_VERBS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::CommandObject>> *objects() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::CommandObject>> *>(VT_OBJECTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::SentenceTemplate>> *templates() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::SentenceTemplate>> *>(VT_TEMPLATES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::ContextRule>> *context_rules() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::ContextRule>> *>(VT_CONTEXT_RULES);
  }
  const GrammarRules::LearningConfig *learning_config() const {
    return GetPointer<const GrammarRules::LearningConfig *>(VT_LEARNING_CONFIG);
  }
  int64_t generated_timestamp() const {
    return GetField<int64_t>(VT_GENERATED_TIMESTAMP, 0);
  }
  int32_t total_sentences_analyzed() const {
    return GetField<int32_t>(VT_TOTAL_SENTENCES_ANALYZED, 0);
  }
  const ::flatbuffers::String *merge_strategy() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MERGE_STRATEGY);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_LANGUAGE) &&
           verifier.VerifyString(language()) &&
           VerifyOffset(verifier, VT_TREEBANK_SOURCE) &&
           verifier.VerifyString(treebank_source()) &&
           VerifyOffset(verifier, VT_COMPONENTS) &&
           verifier.VerifyVector(components()) &&
           verifier.VerifyVectorOfTables(components()) &&
           VerifyOffset(verifier, VT_VERBS) &&
           verifier.VerifyVector(verbs()) &&
           verifier.VerifyVectorOfTables(verbs()) &&
           VerifyOffset(verifier, VT_OBJECTS) &&
           verifier.VerifyVector(objects()) &&
           verifier.VerifyVectorOfTables(objects()) &&
           VerifyOffset(verifier, VT_TEMPLATES) &&
           verifier.VerifyVector(templates()) &&
           verifier.VerifyVectorOfTables(templates()) &&
           VerifyOffset(verifier, VT_CONTEXT_RULES) &&
           verifier.VerifyVector(context_rules()) &&
           verifier.VerifyVectorOfTables(context_rules()) &&
           VerifyOffset(verifier, VT_LEARNING_CONFIG) &&
           verifier.VerifyTable(learning_config()) &&
           VerifyField<int64_t>(verifier, VT_GENERATED_TIMESTAMP, 8) &&
           VerifyField<int32_t>(verifier, VT_TOTAL_SENTENCES_ANALYZED, 4) &&
           VerifyOffset(verifier, VT_MERGE_STRATEGY) &&
           verifier.VerifyString(merge_strategy()) &&
           verifier.EndTable();
  }
};

struct GrammarConfigBuilder {
  typedef GrammarConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(int32_t version) {
    fbb_.AddElement<int32_t>(GrammarConfig::VT_VERSION, version, 1);
  }
  void add_language(::flatbuffers::Offset<::flatbuffers::String> language) {
    fbb_.AddOffset(GrammarConfig::VT_LANGUAGE, language);
  }
  void add_treebank_source(::flatbuffers::Offset<::flatbuffers::String> treebank_source) {
    fbb_.AddOffset(GrammarConfig::VT_TREEBANK_SOURCE, treebank_source);
  }
  void add_components(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::GrammarComponent>>> components) {
    fbb_.AddOffset(GrammarConfig::VT_COMPONENTS, components);
  }
  void add_verbs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::CommandVerb>>> verbs) {
    fbb_.AddOffset(GrammarConfig::VT_VERBS, verbs);
  }
  void add_objects(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::CommandObject>>> objects) {
    fbb_.AddOffset(GrammarConfig::VT_OBJECTS, objects);
  }
  void add_templates(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::SentenceTemplate>>> templates) {
    fbb_.AddOffset(GrammarConfig::VT_TEMPLATES, templates);
  }
  void add_context_rules(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::ContextRule>>> context_rules) {
    fbb_.AddOffset(GrammarConfig::VT_CONTEXT_RULES, context_rules);
  }
  void add_learning_config(::flatbuffers::Offset<GrammarRules::LearningConfig> learning_config) {
    fbb_.AddOffset(GrammarConfig::VT_LEARNING_CONFIG, learning_config);
  }
  void add_generated_timestamp(int64_t generated_timestamp) {
    fbb_.AddElement<int64_t>(GrammarConfig::VT_GENERATED_TIMESTAMP, generated_timestamp, 0);
  }
  void add_total_sentences_analyzed(int32_t total_sentences_analyzed) {
    fbb_.AddElement<int32_t>(GrammarConfig::VT_TOTAL_SENTENCES_ANALYZED, total_sentences_analyzed, 0);
  }
  void add_merge_strategy(::flatbuffers::Offset<::flatbuffers::String> merge_strategy) {
    fbb_.AddOffset(GrammarConfig::VT_MERGE_STRATEGY, merge_strategy);
  }
  explicit GrammarConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GrammarConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GrammarConfig>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GrammarConfig> CreateGrammarConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t version = 1,
    ::flatbuffers::Offset<::flatbuffers::String> language = 0,
    ::flatbuffers::Offset<::flatbuffers::String> treebank_source = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::GrammarComponent>>> components = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::CommandVerb>>> verbs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::CommandObject>>> objects = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::SentenceTemplate>>> templates = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GrammarRules::ContextRule>>> context_rules = 0,
    ::flatbuffers::Offset<GrammarRules::LearningConfig> learning_config = 0,
    int64_t generated_timestamp = 0,
    int32_t total_sentences_analyzed = 0,
    ::flatbuffers::Offset<::flatbuffers::String> merge_strategy = 0) {
  GrammarConfigBuilder builder_(_fbb);
  builder_.add_generated_timestamp(generated_timestamp);
  builder_.add_merge_strategy(merge_strategy);
  builder_.add_total_sentences_analyzed(total_sentences_analyzed);
  builder_.add_learning_config(learning_config);
  builder_.add_context_rules(context_rules);
  builder_.add_templates(templates);
  builder_.add_objects(objects);
  builder_.add_verbs(verbs);
  builder_.add_components(components);
  builder_.add_treebank_source(treebank_source);
  builder_.add_language(language);
  builder_.add_version(version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GrammarConfig> CreateGrammarConfigDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t version = 1,
    const char *language = nullptr,
    const char *treebank_source = nullptr,
    const std::vector<::flatbuffers::Offset<GrammarRules::GrammarComponent>> *components = nullptr,
    const std::vector<::flatbuffers::Offset<GrammarRules::CommandVerb>> *verbs = nullptr,
    const std::vector<::flatbuffers::Offset<GrammarRules::CommandObject>> *objects = nullptr,
    const std::vector<::flatbuffers::Offset<GrammarRules::SentenceTemplate>> *templates = nullptr,
    const std::vector<::flatbuffers::Offset<GrammarRules::ContextRule>> *context_rules = nullptr,
    ::flatbuffers::Offset<GrammarRules::LearningConfig> learning_config = 0,
    int64_t generated_timestamp = 0,
    int32_t total_sentences_analyzed = 0,
    const char *merge_strategy = nullptr) {
  auto language__ = language ? _fbb.CreateString(language) : 0;
  auto treebank_source__ = treebank_source ? _fbb.CreateString(treebank_source) : 0;
  auto components__ = components ? _fbb.CreateVector<::flatbuffers::Offset<GrammarRules::GrammarComponent>>(*components) : 0;
  auto verbs__ = verbs ? _fbb.CreateVector<::flatbuffers::Offset<GrammarRules::CommandVerb>>(*verbs) : 0;
  auto objects__ = objects ? _fbb.CreateVector<::flatbuffers::Offset<GrammarRules::CommandObject>>(*objects) : 0;
  auto templates__ = templates ? _fbb.CreateVector<::flatbuffers::Offset<GrammarRules::SentenceTemplate>>(*templates) : 0;
  auto context_rules__ = context_rules ? _fbb.CreateVector<::flatbuffers::Offset<GrammarRules::ContextRule>>(*context_rules) : 0;
  auto merge_strategy__ = merge_strategy ? _fbb.CreateString(merge_strategy) : 0;
  return GrammarRules::CreateGrammarConfig(
      _fbb,
      version,
      language__,
      treebank_source__,
      components__,
      verbs__,
      objects__,
      templates__,
      context_rules__,
      learning_config,
      generated_timestamp,
      total_sentences_analyzed,
      merge_strategy__);
}

inline const GrammarRules::GrammarConfig *GetGrammarConfig(const void *buf) {
  return ::flatbuffers::GetRoot<GrammarRules::GrammarConfig>(buf);
}

inline const GrammarRules::GrammarConfig *GetSizePrefixedGrammarConfig(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GrammarRules::GrammarConfig>(buf);
}

inline bool VerifyGrammarConfigBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GrammarRules::GrammarConfig>(nullptr);
}

inline bool VerifySizePrefixedGrammarConfigBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GrammarRules::GrammarConfig>(nullptr);
}

inline void FinishGrammarConfigBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GrammarRules::GrammarConfig> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGrammarConfigBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GrammarRules::GrammarConfig> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace GrammarRules

#endif  // FLATBUFFERS_GENERATED_GRAMMARRULES_GRAMMARRULES_H_
