// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WEBTRAININGDATA_GRIMWEBTRAINING_H_
#define FLATBUFFERS_GENERATED_WEBTRAININGDATA_GRIMWEBTRAINING_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25,
             "Non-compatible flatbuffers version included");

namespace GRIMWebTraining {

struct SourceInfo;
struct SourceInfoBuilder;

struct VerificationInfo;
struct VerificationInfoBuilder;

struct ContentMetadata;
struct ContentMetadataBuilder;

struct TrainingExample;
struct TrainingExampleBuilder;

struct TrainingBatch;
struct TrainingBatchBuilder;

struct CollectionSession;
struct CollectionSessionBuilder;

struct WebTrainingDataset;
struct WebTrainingDatasetBuilder;

struct LanguageCount;
struct LanguageCountBuilder;

struct ExampleIndex;
struct ExampleIndexBuilder;

struct DatasetIndex;
struct DatasetIndexBuilder;

enum SourceType : int8_t {
  SourceType_UNKNOWN = 0,
  SourceType_NEWS_API = 1,
  SourceType_GITHUB = 2,
  SourceType_TECH_DOCS = 3,
  SourceType_WIKIPEDIA = 4,
  SourceType_ARXIV = 5,
  SourceType_STACKOVERFLOW = 6,
  SourceType_REDDIT = 7,
  SourceType_CUSTOM = 8,
  SourceType_MIN = SourceType_UNKNOWN,
  SourceType_MAX = SourceType_CUSTOM
};

inline const SourceType (&EnumValuesSourceType())[9] {
  static const SourceType values[] = {
    SourceType_UNKNOWN,
    SourceType_NEWS_API,
    SourceType_GITHUB,
    SourceType_TECH_DOCS,
    SourceType_WIKIPEDIA,
    SourceType_ARXIV,
    SourceType_STACKOVERFLOW,
    SourceType_REDDIT,
    SourceType_CUSTOM
  };
  return values;
}

inline const char * const *EnumNamesSourceType() {
  static const char * const names[10] = {
    "UNKNOWN",
    "NEWS_API",
    "GITHUB",
    "TECH_DOCS",
    "WIKIPEDIA",
    "ARXIV",
    "STACKOVERFLOW",
    "REDDIT",
    "CUSTOM",
    nullptr
  };
  return names;
}

inline const char *EnumNameSourceType(SourceType e) {
  if (::flatbuffers::IsOutRange(e, SourceType_UNKNOWN, SourceType_CUSTOM)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSourceType()[index];
}

enum VerificationStatus : int8_t {
  VerificationStatus_UNVERIFIED = 0,
  VerificationStatus_VERIFIED = 1,
  VerificationStatus_FAILED = 2,
  VerificationStatus_PENDING = 3,
  VerificationStatus_CROSS_REFERENCED = 4,
  VerificationStatus_MIN = VerificationStatus_UNVERIFIED,
  VerificationStatus_MAX = VerificationStatus_CROSS_REFERENCED
};

inline const VerificationStatus (&EnumValuesVerificationStatus())[5] {
  static const VerificationStatus values[] = {
    VerificationStatus_UNVERIFIED,
    VerificationStatus_VERIFIED,
    VerificationStatus_FAILED,
    VerificationStatus_PENDING,
    VerificationStatus_CROSS_REFERENCED
  };
  return values;
}

inline const char * const *EnumNamesVerificationStatus() {
  static const char * const names[6] = {
    "UNVERIFIED",
    "VERIFIED",
    "FAILED",
    "PENDING",
    "CROSS_REFERENCED",
    nullptr
  };
  return names;
}

inline const char *EnumNameVerificationStatus(VerificationStatus e) {
  if (::flatbuffers::IsOutRange(e, VerificationStatus_UNVERIFIED, VerificationStatus_CROSS_REFERENCED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesVerificationStatus()[index];
}

struct SourceInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SourceInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_URL = 4,
    VT_SOURCE_TYPE = 6,
    VT_DOMAIN = 8,
    VT_AUTHOR = 10,
    VT_TITLE = 12,
    VT_PUBLISH_DATE = 14,
    VT_FETCH_DATE = 16,
    VT_API_KEY_USED = 18
  };
  const ::flatbuffers::String *url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_URL);
  }
  GRIMWebTraining::SourceType source_type() const {
    return static_cast<GRIMWebTraining::SourceType>(GetField<int8_t>(VT_SOURCE_TYPE, 0));
  }
  const ::flatbuffers::String *domain() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DOMAIN);
  }
  const ::flatbuffers::String *author() const {
    return GetPointer<const ::flatbuffers::String *>(VT_AUTHOR);
  }
  const ::flatbuffers::String *title() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TITLE);
  }
  uint64_t publish_date() const {
    return GetField<uint64_t>(VT_PUBLISH_DATE, 0);
  }
  uint64_t fetch_date() const {
    return GetField<uint64_t>(VT_FETCH_DATE, 0);
  }
  bool api_key_used() const {
    return GetField<uint8_t>(VT_API_KEY_USED, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_URL) &&
           verifier.VerifyString(url()) &&
           VerifyField<int8_t>(verifier, VT_SOURCE_TYPE, 1) &&
           VerifyOffset(verifier, VT_DOMAIN) &&
           verifier.VerifyString(domain()) &&
           VerifyOffset(verifier, VT_AUTHOR) &&
           verifier.VerifyString(author()) &&
           VerifyOffset(verifier, VT_TITLE) &&
           verifier.VerifyString(title()) &&
           VerifyField<uint64_t>(verifier, VT_PUBLISH_DATE, 8) &&
           VerifyField<uint64_t>(verifier, VT_FETCH_DATE, 8) &&
           VerifyField<uint8_t>(verifier, VT_API_KEY_USED, 1) &&
           verifier.EndTable();
  }
};

struct SourceInfoBuilder {
  typedef SourceInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_url(::flatbuffers::Offset<::flatbuffers::String> url) {
    fbb_.AddOffset(SourceInfo::VT_URL, url);
  }
  void add_source_type(GRIMWebTraining::SourceType source_type) {
    fbb_.AddElement<int8_t>(SourceInfo::VT_SOURCE_TYPE, static_cast<int8_t>(source_type), 0);
  }
  void add_domain(::flatbuffers::Offset<::flatbuffers::String> domain) {
    fbb_.AddOffset(SourceInfo::VT_DOMAIN, domain);
  }
  void add_author(::flatbuffers::Offset<::flatbuffers::String> author) {
    fbb_.AddOffset(SourceInfo::VT_AUTHOR, author);
  }
  void add_title(::flatbuffers::Offset<::flatbuffers::String> title) {
    fbb_.AddOffset(SourceInfo::VT_TITLE, title);
  }
  void add_publish_date(uint64_t publish_date) {
    fbb_.AddElement<uint64_t>(SourceInfo::VT_PUBLISH_DATE, publish_date, 0);
  }
  void add_fetch_date(uint64_t fetch_date) {
    fbb_.AddElement<uint64_t>(SourceInfo::VT_FETCH_DATE, fetch_date, 0);
  }
  void add_api_key_used(bool api_key_used) {
    fbb_.AddElement<uint8_t>(SourceInfo::VT_API_KEY_USED, static_cast<uint8_t>(api_key_used), 0);
  }
  explicit SourceInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SourceInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SourceInfo>(end);
    fbb_.Required(o, SourceInfo::VT_URL);
    return o;
  }
};

inline ::flatbuffers::Offset<SourceInfo> CreateSourceInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> url = 0,
    GRIMWebTraining::SourceType source_type = GRIMWebTraining::SourceType_UNKNOWN,
    ::flatbuffers::Offset<::flatbuffers::String> domain = 0,
    ::flatbuffers::Offset<::flatbuffers::String> author = 0,
    ::flatbuffers::Offset<::flatbuffers::String> title = 0,
    uint64_t publish_date = 0,
    uint64_t fetch_date = 0,
    bool api_key_used = false) {
  SourceInfoBuilder builder_(_fbb);
  builder_.add_fetch_date(fetch_date);
  builder_.add_publish_date(publish_date);
  builder_.add_title(title);
  builder_.add_author(author);
  builder_.add_domain(domain);
  builder_.add_url(url);
  builder_.add_api_key_used(api_key_used);
  builder_.add_source_type(source_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SourceInfo> CreateSourceInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *url = nullptr,
    GRIMWebTraining::SourceType source_type = GRIMWebTraining::SourceType_UNKNOWN,
    const char *domain = nullptr,
    const char *author = nullptr,
    const char *title = nullptr,
    uint64_t publish_date = 0,
    uint64_t fetch_date = 0,
    bool api_key_used = false) {
  auto url__ = url ? _fbb.CreateString(url) : 0;
  auto domain__ = domain ? _fbb.CreateString(domain) : 0;
  auto author__ = author ? _fbb.CreateString(author) : 0;
  auto title__ = title ? _fbb.CreateString(title) : 0;
  return GRIMWebTraining::CreateSourceInfo(
      _fbb,
      url__,
      source_type,
      domain__,
      author__,
      title__,
      publish_date,
      fetch_date,
      api_key_used);
}

struct VerificationInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VerificationInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATUS = 4,
    VT_RELIABILITY_SCORE = 6,
    VT_NUM_CROSS_REFS = 8,
    VT_CROSS_REF_URLS = 10,
    VT_VERIFICATION_DATE = 12,
    VT_VERIFICATION_METHOD = 14,
    VT_CONTENT_QUALITY_SCORE = 16,
    VT_FACTUAL_CONSISTENCY = 18,
    VT_IS_DUPLICATE = 20,
    VT_IS_MALFORMED = 22,
    VT_PASSED_FILTERS = 24
  };
  GRIMWebTraining::VerificationStatus status() const {
    return static_cast<GRIMWebTraining::VerificationStatus>(GetField<int8_t>(VT_STATUS, 0));
  }
  float reliability_score() const {
    return GetField<float>(VT_RELIABILITY_SCORE, 0.0f);
  }
  uint32_t num_cross_refs() const {
    return GetField<uint32_t>(VT_NUM_CROSS_REFS, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *cross_ref_urls() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_CROSS_REF_URLS);
  }
  uint64_t verification_date() const {
    return GetField<uint64_t>(VT_VERIFICATION_DATE, 0);
  }
  const ::flatbuffers::String *verification_method() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VERIFICATION_METHOD);
  }
  float content_quality_score() const {
    return GetField<float>(VT_CONTENT_QUALITY_SCORE, 0.0f);
  }
  float factual_consistency() const {
    return GetField<float>(VT_FACTUAL_CONSISTENCY, 0.0f);
  }
  bool is_duplicate() const {
    return GetField<uint8_t>(VT_IS_DUPLICATE, 0) != 0;
  }
  bool is_malformed() const {
    return GetField<uint8_t>(VT_IS_MALFORMED, 0) != 0;
  }
  bool passed_filters() const {
    return GetField<uint8_t>(VT_PASSED_FILTERS, 1) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_STATUS, 1) &&
           VerifyField<float>(verifier, VT_RELIABILITY_SCORE, 4) &&
           VerifyField<uint32_t>(verifier, VT_NUM_CROSS_REFS, 4) &&
           VerifyOffset(verifier, VT_CROSS_REF_URLS) &&
           verifier.VerifyVector(cross_ref_urls()) &&
           verifier.VerifyVectorOfStrings(cross_ref_urls()) &&
           VerifyField<uint64_t>(verifier, VT_VERIFICATION_DATE, 8) &&
           VerifyOffset(verifier, VT_VERIFICATION_METHOD) &&
           verifier.VerifyString(verification_method()) &&
           VerifyField<float>(verifier, VT_CONTENT_QUALITY_SCORE, 4) &&
           VerifyField<float>(verifier, VT_FACTUAL_CONSISTENCY, 4) &&
           VerifyField<uint8_t>(verifier, VT_IS_DUPLICATE, 1) &&
           VerifyField<uint8_t>(verifier, VT_IS_MALFORMED, 1) &&
           VerifyField<uint8_t>(verifier, VT_PASSED_FILTERS, 1) &&
           verifier.EndTable();
  }
};

struct VerificationInfoBuilder {
  typedef VerificationInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_status(GRIMWebTraining::VerificationStatus status) {
    fbb_.AddElement<int8_t>(VerificationInfo::VT_STATUS, static_cast<int8_t>(status), 0);
  }
  void add_reliability_score(float reliability_score) {
    fbb_.AddElement<float>(VerificationInfo::VT_RELIABILITY_SCORE, reliability_score, 0.0f);
  }
  void add_num_cross_refs(uint32_t num_cross_refs) {
    fbb_.AddElement<uint32_t>(VerificationInfo::VT_NUM_CROSS_REFS, num_cross_refs, 0);
  }
  void add_cross_ref_urls(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> cross_ref_urls) {
    fbb_.AddOffset(VerificationInfo::VT_CROSS_REF_URLS, cross_ref_urls);
  }
  void add_verification_date(uint64_t verification_date) {
    fbb_.AddElement<uint64_t>(VerificationInfo::VT_VERIFICATION_DATE, verification_date, 0);
  }
  void add_verification_method(::flatbuffers::Offset<::flatbuffers::String> verification_method) {
    fbb_.AddOffset(VerificationInfo::VT_VERIFICATION_METHOD, verification_method);
  }
  void add_content_quality_score(float content_quality_score) {
    fbb_.AddElement<float>(VerificationInfo::VT_CONTENT_QUALITY_SCORE, content_quality_score, 0.0f);
  }
  void add_factual_consistency(float factual_consistency) {
    fbb_.AddElement<float>(VerificationInfo::VT_FACTUAL_CONSISTENCY, factual_consistency, 0.0f);
  }
  void add_is_duplicate(bool is_duplicate) {
    fbb_.AddElement<uint8_t>(VerificationInfo::VT_IS_DUPLICATE, static_cast<uint8_t>(is_duplicate), 0);
  }
  void add_is_malformed(bool is_malformed) {
    fbb_.AddElement<uint8_t>(VerificationInfo::VT_IS_MALFORMED, static_cast<uint8_t>(is_malformed), 0);
  }
  void add_passed_filters(bool passed_filters) {
    fbb_.AddElement<uint8_t>(VerificationInfo::VT_PASSED_FILTERS, static_cast<uint8_t>(passed_filters), 1);
  }
  explicit VerificationInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VerificationInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VerificationInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VerificationInfo> CreateVerificationInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GRIMWebTraining::VerificationStatus status = GRIMWebTraining::VerificationStatus_UNVERIFIED,
    float reliability_score = 0.0f,
    uint32_t num_cross_refs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> cross_ref_urls = 0,
    uint64_t verification_date = 0,
    ::flatbuffers::Offset<::flatbuffers::String> verification_method = 0,
    float content_quality_score = 0.0f,
    float factual_consistency = 0.0f,
    bool is_duplicate = false,
    bool is_malformed = false,
    bool passed_filters = true) {
  VerificationInfoBuilder builder_(_fbb);
  builder_.add_verification_date(verification_date);
  builder_.add_factual_consistency(factual_consistency);
  builder_.add_content_quality_score(content_quality_score);
  builder_.add_verification_method(verification_method);
  builder_.add_cross_ref_urls(cross_ref_urls);
  builder_.add_num_cross_refs(num_cross_refs);
  builder_.add_reliability_score(reliability_score);
  builder_.add_passed_filters(passed_filters);
  builder_.add_is_malformed(is_malformed);
  builder_.add_is_duplicate(is_duplicate);
  builder_.add_status(status);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VerificationInfo> CreateVerificationInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GRIMWebTraining::VerificationStatus status = GRIMWebTraining::VerificationStatus_UNVERIFIED,
    float reliability_score = 0.0f,
    uint32_t num_cross_refs = 0,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *cross_ref_urls = nullptr,
    uint64_t verification_date = 0,
    const char *verification_method = nullptr,
    float content_quality_score = 0.0f,
    float factual_consistency = 0.0f,
    bool is_duplicate = false,
    bool is_malformed = false,
    bool passed_filters = true) {
  auto cross_ref_urls__ = cross_ref_urls ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*cross_ref_urls) : 0;
  auto verification_method__ = verification_method ? _fbb.CreateString(verification_method) : 0;
  return GRIMWebTraining::CreateVerificationInfo(
      _fbb,
      status,
      reliability_score,
      num_cross_refs,
      cross_ref_urls__,
      verification_date,
      verification_method__,
      content_quality_score,
      factual_consistency,
      is_duplicate,
      is_malformed,
      passed_filters);
}

struct ContentMetadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ContentMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHAR_COUNT = 4,
    VT_WORD_COUNT = 6,
    VT_SENTENCE_COUNT = 8,
    VT_PARAGRAPH_COUNT = 10,
    VT_LANGUAGE = 12,
    VT_LANGUAGE_CONFIDENCE = 14,
    VT_TOPICS = 16,
    VT_KEYWORDS = 18,
    VT_NAMED_ENTITIES = 20,
    VT_CONTENT_CATEGORY = 22,
    VT_HAS_CODE_BLOCKS = 24,
    VT_HAS_MARKDOWN = 26,
    VT_HAS_MATH = 28,
    VT_READABILITY_SCORE = 30
  };
  uint32_t char_count() const {
    return GetField<uint32_t>(VT_CHAR_COUNT, 0);
  }
  uint32_t word_count() const {
    return GetField<uint32_t>(VT_WORD_COUNT, 0);
  }
  uint32_t sentence_count() const {
    return GetField<uint32_t>(VT_SENTENCE_COUNT, 0);
  }
  uint32_t paragraph_count() const {
    return GetField<uint32_t>(VT_PARAGRAPH_COUNT, 0);
  }
  const ::flatbuffers::String *language() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LANGUAGE);
  }
  float language_confidence() const {
    return GetField<float>(VT_LANGUAGE_CONFIDENCE, 1.0f);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *topics() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_TOPICS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *keywords() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_KEYWORDS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *named_entities() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_NAMED_ENTITIES);
  }
  const ::flatbuffers::String *content_category() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONTENT_CATEGORY);
  }
  bool has_code_blocks() const {
    return GetField<uint8_t>(VT_HAS_CODE_BLOCKS, 0) != 0;
  }
  bool has_markdown() const {
    return GetField<uint8_t>(VT_HAS_MARKDOWN, 0) != 0;
  }
  bool has_math() const {
    return GetField<uint8_t>(VT_HAS_MATH, 0) != 0;
  }
  float readability_score() const {
    return GetField<float>(VT_READABILITY_SCORE, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CHAR_COUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_WORD_COUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_SENTENCE_COUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_PARAGRAPH_COUNT, 4) &&
           VerifyOffset(verifier, VT_LANGUAGE) &&
           verifier.VerifyString(language()) &&
           VerifyField<float>(verifier, VT_LANGUAGE_CONFIDENCE, 4) &&
           VerifyOffset(verifier, VT_TOPICS) &&
           verifier.VerifyVector(topics()) &&
           verifier.VerifyVectorOfStrings(topics()) &&
           VerifyOffset(verifier, VT_KEYWORDS) &&
           verifier.VerifyVector(keywords()) &&
           verifier.VerifyVectorOfStrings(keywords()) &&
           VerifyOffset(verifier, VT_NAMED_ENTITIES) &&
           verifier.VerifyVector(named_entities()) &&
           verifier.VerifyVectorOfStrings(named_entities()) &&
           VerifyOffset(verifier, VT_CONTENT_CATEGORY) &&
           verifier.VerifyString(content_category()) &&
           VerifyField<uint8_t>(verifier, VT_HAS_CODE_BLOCKS, 1) &&
           VerifyField<uint8_t>(verifier, VT_HAS_MARKDOWN, 1) &&
           VerifyField<uint8_t>(verifier, VT_HAS_MATH, 1) &&
           VerifyField<float>(verifier, VT_READABILITY_SCORE, 4) &&
           verifier.EndTable();
  }
};

struct ContentMetadataBuilder {
  typedef ContentMetadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_char_count(uint32_t char_count) {
    fbb_.AddElement<uint32_t>(ContentMetadata::VT_CHAR_COUNT, char_count, 0);
  }
  void add_word_count(uint32_t word_count) {
    fbb_.AddElement<uint32_t>(ContentMetadata::VT_WORD_COUNT, word_count, 0);
  }
  void add_sentence_count(uint32_t sentence_count) {
    fbb_.AddElement<uint32_t>(ContentMetadata::VT_SENTENCE_COUNT, sentence_count, 0);
  }
  void add_paragraph_count(uint32_t paragraph_count) {
    fbb_.AddElement<uint32_t>(ContentMetadata::VT_PARAGRAPH_COUNT, paragraph_count, 0);
  }
  void add_language(::flatbuffers::Offset<::flatbuffers::String> language) {
    fbb_.AddOffset(ContentMetadata::VT_LANGUAGE, language);
  }
  void add_language_confidence(float language_confidence) {
    fbb_.AddElement<float>(ContentMetadata::VT_LANGUAGE_CONFIDENCE, language_confidence, 1.0f);
  }
  void add_topics(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> topics) {
    fbb_.AddOffset(ContentMetadata::VT_TOPICS, topics);
  }
  void add_keywords(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> keywords) {
    fbb_.AddOffset(ContentMetadata::VT_KEYWORDS, keywords);
  }
  void add_named_entities(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> named_entities) {
    fbb_.AddOffset(ContentMetadata::VT_NAMED_ENTITIES, named_entities);
  }
  void add_content_category(::flatbuffers::Offset<::flatbuffers::String> content_category) {
    fbb_.AddOffset(ContentMetadata::VT_CONTENT_CATEGORY, content_category);
  }
  void add_has_code_blocks(bool has_code_blocks) {
    fbb_.AddElement<uint8_t>(ContentMetadata::VT_HAS_CODE_BLOCKS, static_cast<uint8_t>(has_code_blocks), 0);
  }
  void add_has_markdown(bool has_markdown) {
    fbb_.AddElement<uint8_t>(ContentMetadata::VT_HAS_MARKDOWN, static_cast<uint8_t>(has_markdown), 0);
  }
  void add_has_math(bool has_math) {
    fbb_.AddElement<uint8_t>(ContentMetadata::VT_HAS_MATH, static_cast<uint8_t>(has_math), 0);
  }
  void add_readability_score(float readability_score) {
    fbb_.AddElement<float>(ContentMetadata::VT_READABILITY_SCORE, readability_score, 0.0f);
  }
  explicit ContentMetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ContentMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ContentMetadata>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ContentMetadata> CreateContentMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t char_count = 0,
    uint32_t word_count = 0,
    uint32_t sentence_count = 0,
    uint32_t paragraph_count = 0,
    ::flatbuffers::Offset<::flatbuffers::String> language = 0,
    float language_confidence = 1.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> topics = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> keywords = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> named_entities = 0,
    ::flatbuffers::Offset<::flatbuffers::String> content_category = 0,
    bool has_code_blocks = false,
    bool has_markdown = false,
    bool has_math = false,
    float readability_score = 0.0f) {
  ContentMetadataBuilder builder_(_fbb);
  builder_.add_readability_score(readability_score);
  builder_.add_content_category(content_category);
  builder_.add_named_entities(named_entities);
  builder_.add_keywords(keywords);
  builder_.add_topics(topics);
  builder_.add_language_confidence(language_confidence);
  builder_.add_language(language);
  builder_.add_paragraph_count(paragraph_count);
  builder_.add_sentence_count(sentence_count);
  builder_.add_word_count(word_count);
  builder_.add_char_count(char_count);
  builder_.add_has_math(has_math);
  builder_.add_has_markdown(has_markdown);
  builder_.add_has_code_blocks(has_code_blocks);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ContentMetadata> CreateContentMetadataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t char_count = 0,
    uint32_t word_count = 0,
    uint32_t sentence_count = 0,
    uint32_t paragraph_count = 0,
    const char *language = nullptr,
    float language_confidence = 1.0f,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *topics = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *keywords = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *named_entities = nullptr,
    const char *content_category = nullptr,
    bool has_code_blocks = false,
    bool has_markdown = false,
    bool has_math = false,
    float readability_score = 0.0f) {
  auto language__ = language ? _fbb.CreateString(language) : 0;
  auto topics__ = topics ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*topics) : 0;
  auto keywords__ = keywords ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*keywords) : 0;
  auto named_entities__ = named_entities ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*named_entities) : 0;
  auto content_category__ = content_category ? _fbb.CreateString(content_category) : 0;
  return GRIMWebTraining::CreateContentMetadata(
      _fbb,
      char_count,
      word_count,
      sentence_count,
      paragraph_count,
      language__,
      language_confidence,
      topics__,
      keywords__,
      named_entities__,
      content_category__,
      has_code_blocks,
      has_markdown,
      has_math,
      readability_score);
}

struct TrainingExample FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrainingExampleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RAW_TEXT = 4,
    VT_CLEANED_TEXT = 6,
    VT_TOKEN_IDS = 8,
    VT_TOKEN_COUNT = 10,
    VT_SOURCE = 12,
    VT_VERIFICATION = 14,
    VT_METADATA = 16,
    VT_INPUT_TEXT = 18,
    VT_TARGET_TEXT = 20,
    VT_CONTEXT = 22,
    VT_PROMPT = 24,
    VT_EXAMPLE_ID = 26,
    VT_PROCESSED_DATE = 28,
    VT_PARSER_VERSION = 30
  };
  const ::flatbuffers::String *raw_text() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RAW_TEXT);
  }
  const ::flatbuffers::String *cleaned_text() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CLEANED_TEXT);
  }
  const ::flatbuffers::Vector<uint32_t> *token_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_TOKEN_IDS);
  }
  uint32_t token_count() const {
    return GetField<uint32_t>(VT_TOKEN_COUNT, 0);
  }
  const GRIMWebTraining::SourceInfo *source() const {
    return GetPointer<const GRIMWebTraining::SourceInfo *>(VT_SOURCE);
  }
  const GRIMWebTraining::VerificationInfo *verification() const {
    return GetPointer<const GRIMWebTraining::VerificationInfo *>(VT_VERIFICATION);
  }
  const GRIMWebTraining::ContentMetadata *metadata() const {
    return GetPointer<const GRIMWebTraining::ContentMetadata *>(VT_METADATA);
  }
  const ::flatbuffers::String *input_text() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INPUT_TEXT);
  }
  const ::flatbuffers::String *target_text() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TARGET_TEXT);
  }
  const ::flatbuffers::String *context() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONTEXT);
  }
  const ::flatbuffers::String *prompt() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROMPT);
  }
  const ::flatbuffers::String *example_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXAMPLE_ID);
  }
  uint64_t processed_date() const {
    return GetField<uint64_t>(VT_PROCESSED_DATE, 0);
  }
  const ::flatbuffers::String *parser_version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PARSER_VERSION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_RAW_TEXT) &&
           verifier.VerifyString(raw_text()) &&
           VerifyOffset(verifier, VT_CLEANED_TEXT) &&
           verifier.VerifyString(cleaned_text()) &&
           VerifyOffset(verifier, VT_TOKEN_IDS) &&
           verifier.VerifyVector(token_ids()) &&
           VerifyField<uint32_t>(verifier, VT_TOKEN_COUNT, 4) &&
           VerifyOffsetRequired(verifier, VT_SOURCE) &&
           verifier.VerifyTable(source()) &&
           VerifyOffsetRequired(verifier, VT_VERIFICATION) &&
           verifier.VerifyTable(verification()) &&
           VerifyOffset(verifier, VT_METADATA) &&
           verifier.VerifyTable(metadata()) &&
           VerifyOffset(verifier, VT_INPUT_TEXT) &&
           verifier.VerifyString(input_text()) &&
           VerifyOffset(verifier, VT_TARGET_TEXT) &&
           verifier.VerifyString(target_text()) &&
           VerifyOffset(verifier, VT_CONTEXT) &&
           verifier.VerifyString(context()) &&
           VerifyOffset(verifier, VT_PROMPT) &&
           verifier.VerifyString(prompt()) &&
           VerifyOffsetRequired(verifier, VT_EXAMPLE_ID) &&
           verifier.VerifyString(example_id()) &&
           VerifyField<uint64_t>(verifier, VT_PROCESSED_DATE, 8) &&
           VerifyOffset(verifier, VT_PARSER_VERSION) &&
           verifier.VerifyString(parser_version()) &&
           verifier.EndTable();
  }
};

struct TrainingExampleBuilder {
  typedef TrainingExample Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_raw_text(::flatbuffers::Offset<::flatbuffers::String> raw_text) {
    fbb_.AddOffset(TrainingExample::VT_RAW_TEXT, raw_text);
  }
  void add_cleaned_text(::flatbuffers::Offset<::flatbuffers::String> cleaned_text) {
    fbb_.AddOffset(TrainingExample::VT_CLEANED_TEXT, cleaned_text);
  }
  void add_token_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> token_ids) {
    fbb_.AddOffset(TrainingExample::VT_TOKEN_IDS, token_ids);
  }
  void add_token_count(uint32_t token_count) {
    fbb_.AddElement<uint32_t>(TrainingExample::VT_TOKEN_COUNT, token_count, 0);
  }
  void add_source(::flatbuffers::Offset<GRIMWebTraining::SourceInfo> source) {
    fbb_.AddOffset(TrainingExample::VT_SOURCE, source);
  }
  void add_verification(::flatbuffers::Offset<GRIMWebTraining::VerificationInfo> verification) {
    fbb_.AddOffset(TrainingExample::VT_VERIFICATION, verification);
  }
  void add_metadata(::flatbuffers::Offset<GRIMWebTraining::ContentMetadata> metadata) {
    fbb_.AddOffset(TrainingExample::VT_METADATA, metadata);
  }
  void add_input_text(::flatbuffers::Offset<::flatbuffers::String> input_text) {
    fbb_.AddOffset(TrainingExample::VT_INPUT_TEXT, input_text);
  }
  void add_target_text(::flatbuffers::Offset<::flatbuffers::String> target_text) {
    fbb_.AddOffset(TrainingExample::VT_TARGET_TEXT, target_text);
  }
  void add_context(::flatbuffers::Offset<::flatbuffers::String> context) {
    fbb_.AddOffset(TrainingExample::VT_CONTEXT, context);
  }
  void add_prompt(::flatbuffers::Offset<::flatbuffers::String> prompt) {
    fbb_.AddOffset(TrainingExample::VT_PROMPT, prompt);
  }
  void add_example_id(::flatbuffers::Offset<::flatbuffers::String> example_id) {
    fbb_.AddOffset(TrainingExample::VT_EXAMPLE_ID, example_id);
  }
  void add_processed_date(uint64_t processed_date) {
    fbb_.AddElement<uint64_t>(TrainingExample::VT_PROCESSED_DATE, processed_date, 0);
  }
  void add_parser_version(::flatbuffers::Offset<::flatbuffers::String> parser_version) {
    fbb_.AddOffset(TrainingExample::VT_PARSER_VERSION, parser_version);
  }
  explicit TrainingExampleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrainingExample> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrainingExample>(end);
    fbb_.Required(o, TrainingExample::VT_RAW_TEXT);
    fbb_.Required(o, TrainingExample::VT_SOURCE);
    fbb_.Required(o, TrainingExample::VT_VERIFICATION);
    fbb_.Required(o, TrainingExample::VT_EXAMPLE_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<TrainingExample> CreateTrainingExample(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> raw_text = 0,
    ::flatbuffers::Offset<::flatbuffers::String> cleaned_text = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> token_ids = 0,
    uint32_t token_count = 0,
    ::flatbuffers::Offset<GRIMWebTraining::SourceInfo> source = 0,
    ::flatbuffers::Offset<GRIMWebTraining::VerificationInfo> verification = 0,
    ::flatbuffers::Offset<GRIMWebTraining::ContentMetadata> metadata = 0,
    ::flatbuffers::Offset<::flatbuffers::String> input_text = 0,
    ::flatbuffers::Offset<::flatbuffers::String> target_text = 0,
    ::flatbuffers::Offset<::flatbuffers::String> context = 0,
    ::flatbuffers::Offset<::flatbuffers::String> prompt = 0,
    ::flatbuffers::Offset<::flatbuffers::String> example_id = 0,
    uint64_t processed_date = 0,
    ::flatbuffers::Offset<::flatbuffers::String> parser_version = 0) {
  TrainingExampleBuilder builder_(_fbb);
  builder_.add_processed_date(processed_date);
  builder_.add_parser_version(parser_version);
  builder_.add_example_id(example_id);
  builder_.add_prompt(prompt);
  builder_.add_context(context);
  builder_.add_target_text(target_text);
  builder_.add_input_text(input_text);
  builder_.add_metadata(metadata);
  builder_.add_verification(verification);
  builder_.add_source(source);
  builder_.add_token_count(token_count);
  builder_.add_token_ids(token_ids);
  builder_.add_cleaned_text(cleaned_text);
  builder_.add_raw_text(raw_text);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TrainingExample> CreateTrainingExampleDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *raw_text = nullptr,
    const char *cleaned_text = nullptr,
    const std::vector<uint32_t> *token_ids = nullptr,
    uint32_t token_count = 0,
    ::flatbuffers::Offset<GRIMWebTraining::SourceInfo> source = 0,
    ::flatbuffers::Offset<GRIMWebTraining::VerificationInfo> verification = 0,
    ::flatbuffers::Offset<GRIMWebTraining::ContentMetadata> metadata = 0,
    const char *input_text = nullptr,
    const char *target_text = nullptr,
    const char *context = nullptr,
    const char *prompt = nullptr,
    const char *example_id = nullptr,
    uint64_t processed_date = 0,
    const char *parser_version = nullptr) {
  auto raw_text__ = raw_text ? _fbb.CreateString(raw_text) : 0;
  auto cleaned_text__ = cleaned_text ? _fbb.CreateString(cleaned_text) : 0;
  auto token_ids__ = token_ids ? _fbb.CreateVector<uint32_t>(*token_ids) : 0;
  auto input_text__ = input_text ? _fbb.CreateString(input_text) : 0;
  auto target_text__ = target_text ? _fbb.CreateString(target_text) : 0;
  auto context__ = context ? _fbb.CreateString(context) : 0;
  auto prompt__ = prompt ? _fbb.CreateString(prompt) : 0;
  auto example_id__ = example_id ? _fbb.CreateString(example_id) : 0;
  auto parser_version__ = parser_version ? _fbb.CreateString(parser_version) : 0;
  return GRIMWebTraining::CreateTrainingExample(
      _fbb,
      raw_text__,
      cleaned_text__,
      token_ids__,
      token_count,
      source,
      verification,
      metadata,
      input_text__,
      target_text__,
      context__,
      prompt__,
      example_id__,
      processed_date,
      parser_version__);
}

struct TrainingBatch FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrainingBatchBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EXAMPLES = 4,
    VT_BATCH_ID = 6,
    VT_CREATED_DATE = 8,
    VT_TOTAL_TOKENS = 10,
    VT_AVG_TOKENS_PER_EXAMPLE = 12,
    VT_MIN_TOKENS = 14,
    VT_MAX_TOKENS = 16
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::TrainingExample>> *examples() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::TrainingExample>> *>(VT_EXAMPLES);
  }
  const ::flatbuffers::String *batch_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BATCH_ID);
  }
  uint64_t created_date() const {
    return GetField<uint64_t>(VT_CREATED_DATE, 0);
  }
  uint64_t total_tokens() const {
    return GetField<uint64_t>(VT_TOTAL_TOKENS, 0);
  }
  float avg_tokens_per_example() const {
    return GetField<float>(VT_AVG_TOKENS_PER_EXAMPLE, 0.0f);
  }
  uint32_t min_tokens() const {
    return GetField<uint32_t>(VT_MIN_TOKENS, 0);
  }
  uint32_t max_tokens() const {
    return GetField<uint32_t>(VT_MAX_TOKENS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_EXAMPLES) &&
           verifier.VerifyVector(examples()) &&
           verifier.VerifyVectorOfTables(examples()) &&
           VerifyOffsetRequired(verifier, VT_BATCH_ID) &&
           verifier.VerifyString(batch_id()) &&
           VerifyField<uint64_t>(verifier, VT_CREATED_DATE, 8) &&
           VerifyField<uint64_t>(verifier, VT_TOTAL_TOKENS, 8) &&
           VerifyField<float>(verifier, VT_AVG_TOKENS_PER_EXAMPLE, 4) &&
           VerifyField<uint32_t>(verifier, VT_MIN_TOKENS, 4) &&
           VerifyField<uint32_t>(verifier, VT_MAX_TOKENS, 4) &&
           verifier.EndTable();
  }
};

struct TrainingBatchBuilder {
  typedef TrainingBatch Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_examples(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::TrainingExample>>> examples) {
    fbb_.AddOffset(TrainingBatch::VT_EXAMPLES, examples);
  }
  void add_batch_id(::flatbuffers::Offset<::flatbuffers::String> batch_id) {
    fbb_.AddOffset(TrainingBatch::VT_BATCH_ID, batch_id);
  }
  void add_created_date(uint64_t created_date) {
    fbb_.AddElement<uint64_t>(TrainingBatch::VT_CREATED_DATE, created_date, 0);
  }
  void add_total_tokens(uint64_t total_tokens) {
    fbb_.AddElement<uint64_t>(TrainingBatch::VT_TOTAL_TOKENS, total_tokens, 0);
  }
  void add_avg_tokens_per_example(float avg_tokens_per_example) {
    fbb_.AddElement<float>(TrainingBatch::VT_AVG_TOKENS_PER_EXAMPLE, avg_tokens_per_example, 0.0f);
  }
  void add_min_tokens(uint32_t min_tokens) {
    fbb_.AddElement<uint32_t>(TrainingBatch::VT_MIN_TOKENS, min_tokens, 0);
  }
  void add_max_tokens(uint32_t max_tokens) {
    fbb_.AddElement<uint32_t>(TrainingBatch::VT_MAX_TOKENS, max_tokens, 0);
  }
  explicit TrainingBatchBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrainingBatch> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrainingBatch>(end);
    fbb_.Required(o, TrainingBatch::VT_EXAMPLES);
    fbb_.Required(o, TrainingBatch::VT_BATCH_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<TrainingBatch> CreateTrainingBatch(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::TrainingExample>>> examples = 0,
    ::flatbuffers::Offset<::flatbuffers::String> batch_id = 0,
    uint64_t created_date = 0,
    uint64_t total_tokens = 0,
    float avg_tokens_per_example = 0.0f,
    uint32_t min_tokens = 0,
    uint32_t max_tokens = 0) {
  TrainingBatchBuilder builder_(_fbb);
  builder_.add_total_tokens(total_tokens);
  builder_.add_created_date(created_date);
  builder_.add_max_tokens(max_tokens);
  builder_.add_min_tokens(min_tokens);
  builder_.add_avg_tokens_per_example(avg_tokens_per_example);
  builder_.add_batch_id(batch_id);
  builder_.add_examples(examples);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TrainingBatch> CreateTrainingBatchDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<GRIMWebTraining::TrainingExample>> *examples = nullptr,
    const char *batch_id = nullptr,
    uint64_t created_date = 0,
    uint64_t total_tokens = 0,
    float avg_tokens_per_example = 0.0f,
    uint32_t min_tokens = 0,
    uint32_t max_tokens = 0) {
  auto examples__ = examples ? _fbb.CreateVector<::flatbuffers::Offset<GRIMWebTraining::TrainingExample>>(*examples) : 0;
  auto batch_id__ = batch_id ? _fbb.CreateString(batch_id) : 0;
  return GRIMWebTraining::CreateTrainingBatch(
      _fbb,
      examples__,
      batch_id__,
      created_date,
      total_tokens,
      avg_tokens_per_example,
      min_tokens,
      max_tokens);
}

struct CollectionSession FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CollectionSessionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SESSION_ID = 4,
    VT_START_TIME = 6,
    VT_END_TIME = 8,
    VT_SOURCE_URLS = 10,
    VT_NUM_SOURCES = 12,
    VT_TOTAL_FETCHED = 14,
    VT_SUCCESSFUL = 16,
    VT_FAILED = 18,
    VT_TOTAL_VERIFIED = 20,
    VT_VERIFICATION_PASSED = 22,
    VT_VERIFICATION_FAILED = 24,
    VT_AVG_RELIABILITY_SCORE = 26,
    VT_CONFIG_JSON = 28,
    VT_ERRORS = 30,
    VT_WARNINGS = 32
  };
  const ::flatbuffers::String *session_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SESSION_ID);
  }
  uint64_t start_time() const {
    return GetField<uint64_t>(VT_START_TIME, 0);
  }
  uint64_t end_time() const {
    return GetField<uint64_t>(VT_END_TIME, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *source_urls() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_SOURCE_URLS);
  }
  uint32_t num_sources() const {
    return GetField<uint32_t>(VT_NUM_SOURCES, 0);
  }
  uint32_t total_fetched() const {
    return GetField<uint32_t>(VT_TOTAL_FETCHED, 0);
  }
  uint32_t successful() const {
    return GetField<uint32_t>(VT_SUCCESSFUL, 0);
  }
  uint32_t failed() const {
    return GetField<uint32_t>(VT_FAILED, 0);
  }
  uint32_t total_verified() const {
    return GetField<uint32_t>(VT_TOTAL_VERIFIED, 0);
  }
  uint32_t verification_passed() const {
    return GetField<uint32_t>(VT_VERIFICATION_PASSED, 0);
  }
  uint32_t verification_failed() const {
    return GetField<uint32_t>(VT_VERIFICATION_FAILED, 0);
  }
  float avg_reliability_score() const {
    return GetField<float>(VT_AVG_RELIABILITY_SCORE, 0.0f);
  }
  const ::flatbuffers::String *config_json() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONFIG_JSON);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *errors() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_ERRORS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *warnings() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_WARNINGS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_SESSION_ID) &&
           verifier.VerifyString(session_id()) &&
           VerifyField<uint64_t>(verifier, VT_START_TIME, 8) &&
           VerifyField<uint64_t>(verifier, VT_END_TIME, 8) &&
           VerifyOffset(verifier, VT_SOURCE_URLS) &&
           verifier.VerifyVector(source_urls()) &&
           verifier.VerifyVectorOfStrings(source_urls()) &&
           VerifyField<uint32_t>(verifier, VT_NUM_SOURCES, 4) &&
           VerifyField<uint32_t>(verifier, VT_TOTAL_FETCHED, 4) &&
           VerifyField<uint32_t>(verifier, VT_SUCCESSFUL, 4) &&
           VerifyField<uint32_t>(verifier, VT_FAILED, 4) &&
           VerifyField<uint32_t>(verifier, VT_TOTAL_VERIFIED, 4) &&
           VerifyField<uint32_t>(verifier, VT_VERIFICATION_PASSED, 4) &&
           VerifyField<uint32_t>(verifier, VT_VERIFICATION_FAILED, 4) &&
           VerifyField<float>(verifier, VT_AVG_RELIABILITY_SCORE, 4) &&
           VerifyOffset(verifier, VT_CONFIG_JSON) &&
           verifier.VerifyString(config_json()) &&
           VerifyOffset(verifier, VT_ERRORS) &&
           verifier.VerifyVector(errors()) &&
           verifier.VerifyVectorOfStrings(errors()) &&
           VerifyOffset(verifier, VT_WARNINGS) &&
           verifier.VerifyVector(warnings()) &&
           verifier.VerifyVectorOfStrings(warnings()) &&
           verifier.EndTable();
  }
};

struct CollectionSessionBuilder {
  typedef CollectionSession Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_session_id(::flatbuffers::Offset<::flatbuffers::String> session_id) {
    fbb_.AddOffset(CollectionSession::VT_SESSION_ID, session_id);
  }
  void add_start_time(uint64_t start_time) {
    fbb_.AddElement<uint64_t>(CollectionSession::VT_START_TIME, start_time, 0);
  }
  void add_end_time(uint64_t end_time) {
    fbb_.AddElement<uint64_t>(CollectionSession::VT_END_TIME, end_time, 0);
  }
  void add_source_urls(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> source_urls) {
    fbb_.AddOffset(CollectionSession::VT_SOURCE_URLS, source_urls);
  }
  void add_num_sources(uint32_t num_sources) {
    fbb_.AddElement<uint32_t>(CollectionSession::VT_NUM_SOURCES, num_sources, 0);
  }
  void add_total_fetched(uint32_t total_fetched) {
    fbb_.AddElement<uint32_t>(CollectionSession::VT_TOTAL_FETCHED, total_fetched, 0);
  }
  void add_successful(uint32_t successful) {
    fbb_.AddElement<uint32_t>(CollectionSession::VT_SUCCESSFUL, successful, 0);
  }
  void add_failed(uint32_t failed) {
    fbb_.AddElement<uint32_t>(CollectionSession::VT_FAILED, failed, 0);
  }
  void add_total_verified(uint32_t total_verified) {
    fbb_.AddElement<uint32_t>(CollectionSession::VT_TOTAL_VERIFIED, total_verified, 0);
  }
  void add_verification_passed(uint32_t verification_passed) {
    fbb_.AddElement<uint32_t>(CollectionSession::VT_VERIFICATION_PASSED, verification_passed, 0);
  }
  void add_verification_failed(uint32_t verification_failed) {
    fbb_.AddElement<uint32_t>(CollectionSession::VT_VERIFICATION_FAILED, verification_failed, 0);
  }
  void add_avg_reliability_score(float avg_reliability_score) {
    fbb_.AddElement<float>(CollectionSession::VT_AVG_RELIABILITY_SCORE, avg_reliability_score, 0.0f);
  }
  void add_config_json(::flatbuffers::Offset<::flatbuffers::String> config_json) {
    fbb_.AddOffset(CollectionSession::VT_CONFIG_JSON, config_json);
  }
  void add_errors(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> errors) {
    fbb_.AddOffset(CollectionSession::VT_ERRORS, errors);
  }
  void add_warnings(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> warnings) {
    fbb_.AddOffset(CollectionSession::VT_WARNINGS, warnings);
  }
  explicit CollectionSessionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CollectionSession> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CollectionSession>(end);
    fbb_.Required(o, CollectionSession::VT_SESSION_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<CollectionSession> CreateCollectionSession(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> session_id = 0,
    uint64_t start_time = 0,
    uint64_t end_time = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> source_urls = 0,
    uint32_t num_sources = 0,
    uint32_t total_fetched = 0,
    uint32_t successful = 0,
    uint32_t failed = 0,
    uint32_t total_verified = 0,
    uint32_t verification_passed = 0,
    uint32_t verification_failed = 0,
    float avg_reliability_score = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::String> config_json = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> errors = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> warnings = 0) {
  CollectionSessionBuilder builder_(_fbb);
  builder_.add_end_time(end_time);
  builder_.add_start_time(start_time);
  builder_.add_warnings(warnings);
  builder_.add_errors(errors);
  builder_.add_config_json(config_json);
  builder_.add_avg_reliability_score(avg_reliability_score);
  builder_.add_verification_failed(verification_failed);
  builder_.add_verification_passed(verification_passed);
  builder_.add_total_verified(total_verified);
  builder_.add_failed(failed);
  builder_.add_successful(successful);
  builder_.add_total_fetched(total_fetched);
  builder_.add_num_sources(num_sources);
  builder_.add_source_urls(source_urls);
  builder_.add_session_id(session_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CollectionSession> CreateCollectionSessionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *session_id = nullptr,
    uint64_t start_time = 0,
    uint64_t end_time = 0,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *source_urls = nullptr,
    uint32_t num_sources = 0,
    uint32_t total_fetched = 0,
    uint32_t successful = 0,
    uint32_t failed = 0,
    uint32_t total_verified = 0,
    uint32_t verification_passed = 0,
    uint32_t verification_failed = 0,
    float avg_reliability_score = 0.0f,
    const char *config_json = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *errors = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *warnings = nullptr) {
  auto session_id__ = session_id ? _fbb.CreateString(session_id) : 0;
  auto source_urls__ = source_urls ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*source_urls) : 0;
  auto config_json__ = config_json ? _fbb.CreateString(config_json) : 0;
  auto errors__ = errors ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*errors) : 0;
  auto warnings__ = warnings ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*warnings) : 0;
  return GRIMWebTraining::CreateCollectionSession(
      _fbb,
      session_id__,
      start_time,
      end_time,
      source_urls__,
      num_sources,
      total_fetched,
      successful,
      failed,
      total_verified,
      verification_passed,
      verification_failed,
      avg_reliability_score,
      config_json__,
      errors__,
      warnings__);
}

struct WebTrainingDataset FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WebTrainingDatasetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATASET_ID = 4,
    VT_DATASET_NAME = 6,
    VT_VERSION = 8,
    VT_CREATED_DATE = 10,
    VT_EXAMPLES = 12,
    VT_SESSIONS = 14,
    VT_TOTAL_EXAMPLES = 16,
    VT_TOTAL_TOKENS = 18,
    VT_TOTAL_SOURCES = 20,
    VT_AVG_RELIABILITY_SCORE = 22,
    VT_SOURCE_TYPE_COUNTS = 24,
    VT_HIGH_QUALITY_COUNT = 26,
    VT_MEDIUM_QUALITY_COUNT = 28,
    VT_LOW_QUALITY_COUNT = 30,
    VT_LANGUAGE_COUNTS = 32,
    VT_SPLIT_TYPE = 34,
    VT_TRAIN_RATIO = 36,
    VT_VAL_RATIO = 38,
    VT_TEST_RATIO = 40,
    VT_VOCAB_SIZE = 42,
    VT_MAX_SEQ_LENGTH = 44,
    VT_TOKENIZER_VERSION = 46
  };
  const ::flatbuffers::String *dataset_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATASET_ID);
  }
  const ::flatbuffers::String *dataset_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATASET_NAME);
  }
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 1);
  }
  uint64_t created_date() const {
    return GetField<uint64_t>(VT_CREATED_DATE, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::TrainingExample>> *examples() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::TrainingExample>> *>(VT_EXAMPLES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::CollectionSession>> *sessions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::CollectionSession>> *>(VT_SESSIONS);
  }
  uint64_t total_examples() const {
    return GetField<uint64_t>(VT_TOTAL_EXAMPLES, 0);
  }
  uint64_t total_tokens() const {
    return GetField<uint64_t>(VT_TOTAL_TOKENS, 0);
  }
  uint32_t total_sources() const {
    return GetField<uint32_t>(VT_TOTAL_SOURCES, 0);
  }
  float avg_reliability_score() const {
    return GetField<float>(VT_AVG_RELIABILITY_SCORE, 0.0f);
  }
  const ::flatbuffers::Vector<uint32_t> *source_type_counts() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_SOURCE_TYPE_COUNTS);
  }
  uint32_t high_quality_count() const {
    return GetField<uint32_t>(VT_HIGH_QUALITY_COUNT, 0);
  }
  uint32_t medium_quality_count() const {
    return GetField<uint32_t>(VT_MEDIUM_QUALITY_COUNT, 0);
  }
  uint32_t low_quality_count() const {
    return GetField<uint32_t>(VT_LOW_QUALITY_COUNT, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::LanguageCount>> *language_counts() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::LanguageCount>> *>(VT_LANGUAGE_COUNTS);
  }
  const ::flatbuffers::String *split_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SPLIT_TYPE);
  }
  float train_ratio() const {
    return GetField<float>(VT_TRAIN_RATIO, 0.8f);
  }
  float val_ratio() const {
    return GetField<float>(VT_VAL_RATIO, 0.1f);
  }
  float test_ratio() const {
    return GetField<float>(VT_TEST_RATIO, 0.1f);
  }
  uint32_t vocab_size() const {
    return GetField<uint32_t>(VT_VOCAB_SIZE, 0);
  }
  uint32_t max_seq_length() const {
    return GetField<uint32_t>(VT_MAX_SEQ_LENGTH, 0);
  }
  const ::flatbuffers::String *tokenizer_version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TOKENIZER_VERSION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DATASET_ID) &&
           verifier.VerifyString(dataset_id()) &&
           VerifyOffset(verifier, VT_DATASET_NAME) &&
           verifier.VerifyString(dataset_name()) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyField<uint64_t>(verifier, VT_CREATED_DATE, 8) &&
           VerifyOffsetRequired(verifier, VT_EXAMPLES) &&
           verifier.VerifyVector(examples()) &&
           verifier.VerifyVectorOfTables(examples()) &&
           VerifyOffset(verifier, VT_SESSIONS) &&
           verifier.VerifyVector(sessions()) &&
           verifier.VerifyVectorOfTables(sessions()) &&
           VerifyField<uint64_t>(verifier, VT_TOTAL_EXAMPLES, 8) &&
           VerifyField<uint64_t>(verifier, VT_TOTAL_TOKENS, 8) &&
           VerifyField<uint32_t>(verifier, VT_TOTAL_SOURCES, 4) &&
           VerifyField<float>(verifier, VT_AVG_RELIABILITY_SCORE, 4) &&
           VerifyOffset(verifier, VT_SOURCE_TYPE_COUNTS) &&
           verifier.VerifyVector(source_type_counts()) &&
           VerifyField<uint32_t>(verifier, VT_HIGH_QUALITY_COUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_MEDIUM_QUALITY_COUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_LOW_QUALITY_COUNT, 4) &&
           VerifyOffset(verifier, VT_LANGUAGE_COUNTS) &&
           verifier.VerifyVector(language_counts()) &&
           verifier.VerifyVectorOfTables(language_counts()) &&
           VerifyOffset(verifier, VT_SPLIT_TYPE) &&
           verifier.VerifyString(split_type()) &&
           VerifyField<float>(verifier, VT_TRAIN_RATIO, 4) &&
           VerifyField<float>(verifier, VT_VAL_RATIO, 4) &&
           VerifyField<float>(verifier, VT_TEST_RATIO, 4) &&
           VerifyField<uint32_t>(verifier, VT_VOCAB_SIZE, 4) &&
           VerifyField<uint32_t>(verifier, VT_MAX_SEQ_LENGTH, 4) &&
           VerifyOffset(verifier, VT_TOKENIZER_VERSION) &&
           verifier.VerifyString(tokenizer_version()) &&
           verifier.EndTable();
  }
};

struct WebTrainingDatasetBuilder {
  typedef WebTrainingDataset Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_dataset_id(::flatbuffers::Offset<::flatbuffers::String> dataset_id) {
    fbb_.AddOffset(WebTrainingDataset::VT_DATASET_ID, dataset_id);
  }
  void add_dataset_name(::flatbuffers::Offset<::flatbuffers::String> dataset_name) {
    fbb_.AddOffset(WebTrainingDataset::VT_DATASET_NAME, dataset_name);
  }
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(WebTrainingDataset::VT_VERSION, version, 1);
  }
  void add_created_date(uint64_t created_date) {
    fbb_.AddElement<uint64_t>(WebTrainingDataset::VT_CREATED_DATE, created_date, 0);
  }
  void add_examples(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::TrainingExample>>> examples) {
    fbb_.AddOffset(WebTrainingDataset::VT_EXAMPLES, examples);
  }
  void add_sessions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::CollectionSession>>> sessions) {
    fbb_.AddOffset(WebTrainingDataset::VT_SESSIONS, sessions);
  }
  void add_total_examples(uint64_t total_examples) {
    fbb_.AddElement<uint64_t>(WebTrainingDataset::VT_TOTAL_EXAMPLES, total_examples, 0);
  }
  void add_total_tokens(uint64_t total_tokens) {
    fbb_.AddElement<uint64_t>(WebTrainingDataset::VT_TOTAL_TOKENS, total_tokens, 0);
  }
  void add_total_sources(uint32_t total_sources) {
    fbb_.AddElement<uint32_t>(WebTrainingDataset::VT_TOTAL_SOURCES, total_sources, 0);
  }
  void add_avg_reliability_score(float avg_reliability_score) {
    fbb_.AddElement<float>(WebTrainingDataset::VT_AVG_RELIABILITY_SCORE, avg_reliability_score, 0.0f);
  }
  void add_source_type_counts(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> source_type_counts) {
    fbb_.AddOffset(WebTrainingDataset::VT_SOURCE_TYPE_COUNTS, source_type_counts);
  }
  void add_high_quality_count(uint32_t high_quality_count) {
    fbb_.AddElement<uint32_t>(WebTrainingDataset::VT_HIGH_QUALITY_COUNT, high_quality_count, 0);
  }
  void add_medium_quality_count(uint32_t medium_quality_count) {
    fbb_.AddElement<uint32_t>(WebTrainingDataset::VT_MEDIUM_QUALITY_COUNT, medium_quality_count, 0);
  }
  void add_low_quality_count(uint32_t low_quality_count) {
    fbb_.AddElement<uint32_t>(WebTrainingDataset::VT_LOW_QUALITY_COUNT, low_quality_count, 0);
  }
  void add_language_counts(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::LanguageCount>>> language_counts) {
    fbb_.AddOffset(WebTrainingDataset::VT_LANGUAGE_COUNTS, language_counts);
  }
  void add_split_type(::flatbuffers::Offset<::flatbuffers::String> split_type) {
    fbb_.AddOffset(WebTrainingDataset::VT_SPLIT_TYPE, split_type);
  }
  void add_train_ratio(float train_ratio) {
    fbb_.AddElement<float>(WebTrainingDataset::VT_TRAIN_RATIO, train_ratio, 0.8f);
  }
  void add_val_ratio(float val_ratio) {
    fbb_.AddElement<float>(WebTrainingDataset::VT_VAL_RATIO, val_ratio, 0.1f);
  }
  void add_test_ratio(float test_ratio) {
    fbb_.AddElement<float>(WebTrainingDataset::VT_TEST_RATIO, test_ratio, 0.1f);
  }
  void add_vocab_size(uint32_t vocab_size) {
    fbb_.AddElement<uint32_t>(WebTrainingDataset::VT_VOCAB_SIZE, vocab_size, 0);
  }
  void add_max_seq_length(uint32_t max_seq_length) {
    fbb_.AddElement<uint32_t>(WebTrainingDataset::VT_MAX_SEQ_LENGTH, max_seq_length, 0);
  }
  void add_tokenizer_version(::flatbuffers::Offset<::flatbuffers::String> tokenizer_version) {
    fbb_.AddOffset(WebTrainingDataset::VT_TOKENIZER_VERSION, tokenizer_version);
  }
  explicit WebTrainingDatasetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WebTrainingDataset> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WebTrainingDataset>(end);
    fbb_.Required(o, WebTrainingDataset::VT_DATASET_ID);
    fbb_.Required(o, WebTrainingDataset::VT_EXAMPLES);
    return o;
  }
};

inline ::flatbuffers::Offset<WebTrainingDataset> CreateWebTrainingDataset(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> dataset_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> dataset_name = 0,
    uint32_t version = 1,
    uint64_t created_date = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::TrainingExample>>> examples = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::CollectionSession>>> sessions = 0,
    uint64_t total_examples = 0,
    uint64_t total_tokens = 0,
    uint32_t total_sources = 0,
    float avg_reliability_score = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> source_type_counts = 0,
    uint32_t high_quality_count = 0,
    uint32_t medium_quality_count = 0,
    uint32_t low_quality_count = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::LanguageCount>>> language_counts = 0,
    ::flatbuffers::Offset<::flatbuffers::String> split_type = 0,
    float train_ratio = 0.8f,
    float val_ratio = 0.1f,
    float test_ratio = 0.1f,
    uint32_t vocab_size = 0,
    uint32_t max_seq_length = 0,
    ::flatbuffers::Offset<::flatbuffers::String> tokenizer_version = 0) {
  WebTrainingDatasetBuilder builder_(_fbb);
  builder_.add_total_tokens(total_tokens);
  builder_.add_total_examples(total_examples);
  builder_.add_created_date(created_date);
  builder_.add_tokenizer_version(tokenizer_version);
  builder_.add_max_seq_length(max_seq_length);
  builder_.add_vocab_size(vocab_size);
  builder_.add_test_ratio(test_ratio);
  builder_.add_val_ratio(val_ratio);
  builder_.add_train_ratio(train_ratio);
  builder_.add_split_type(split_type);
  builder_.add_language_counts(language_counts);
  builder_.add_low_quality_count(low_quality_count);
  builder_.add_medium_quality_count(medium_quality_count);
  builder_.add_high_quality_count(high_quality_count);
  builder_.add_source_type_counts(source_type_counts);
  builder_.add_avg_reliability_score(avg_reliability_score);
  builder_.add_total_sources(total_sources);
  builder_.add_sessions(sessions);
  builder_.add_examples(examples);
  builder_.add_version(version);
  builder_.add_dataset_name(dataset_name);
  builder_.add_dataset_id(dataset_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WebTrainingDataset> CreateWebTrainingDatasetDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *dataset_id = nullptr,
    const char *dataset_name = nullptr,
    uint32_t version = 1,
    uint64_t created_date = 0,
    const std::vector<::flatbuffers::Offset<GRIMWebTraining::TrainingExample>> *examples = nullptr,
    const std::vector<::flatbuffers::Offset<GRIMWebTraining::CollectionSession>> *sessions = nullptr,
    uint64_t total_examples = 0,
    uint64_t total_tokens = 0,
    uint32_t total_sources = 0,
    float avg_reliability_score = 0.0f,
    const std::vector<uint32_t> *source_type_counts = nullptr,
    uint32_t high_quality_count = 0,
    uint32_t medium_quality_count = 0,
    uint32_t low_quality_count = 0,
    const std::vector<::flatbuffers::Offset<GRIMWebTraining::LanguageCount>> *language_counts = nullptr,
    const char *split_type = nullptr,
    float train_ratio = 0.8f,
    float val_ratio = 0.1f,
    float test_ratio = 0.1f,
    uint32_t vocab_size = 0,
    uint32_t max_seq_length = 0,
    const char *tokenizer_version = nullptr) {
  auto dataset_id__ = dataset_id ? _fbb.CreateString(dataset_id) : 0;
  auto dataset_name__ = dataset_name ? _fbb.CreateString(dataset_name) : 0;
  auto examples__ = examples ? _fbb.CreateVector<::flatbuffers::Offset<GRIMWebTraining::TrainingExample>>(*examples) : 0;
  auto sessions__ = sessions ? _fbb.CreateVector<::flatbuffers::Offset<GRIMWebTraining::CollectionSession>>(*sessions) : 0;
  auto source_type_counts__ = source_type_counts ? _fbb.CreateVector<uint32_t>(*source_type_counts) : 0;
  auto language_counts__ = language_counts ? _fbb.CreateVector<::flatbuffers::Offset<GRIMWebTraining::LanguageCount>>(*language_counts) : 0;
  auto split_type__ = split_type ? _fbb.CreateString(split_type) : 0;
  auto tokenizer_version__ = tokenizer_version ? _fbb.CreateString(tokenizer_version) : 0;
  return GRIMWebTraining::CreateWebTrainingDataset(
      _fbb,
      dataset_id__,
      dataset_name__,
      version,
      created_date,
      examples__,
      sessions__,
      total_examples,
      total_tokens,
      total_sources,
      avg_reliability_score,
      source_type_counts__,
      high_quality_count,
      medium_quality_count,
      low_quality_count,
      language_counts__,
      split_type__,
      train_ratio,
      val_ratio,
      test_ratio,
      vocab_size,
      max_seq_length,
      tokenizer_version__);
}

struct LanguageCount FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LanguageCountBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LANGUAGE_CODE = 4,
    VT_COUNT = 6
  };
  const ::flatbuffers::String *language_code() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LANGUAGE_CODE);
  }
  uint32_t count() const {
    return GetField<uint32_t>(VT_COUNT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_LANGUAGE_CODE) &&
           verifier.VerifyString(language_code()) &&
           VerifyField<uint32_t>(verifier, VT_COUNT, 4) &&
           verifier.EndTable();
  }
};

struct LanguageCountBuilder {
  typedef LanguageCount Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_language_code(::flatbuffers::Offset<::flatbuffers::String> language_code) {
    fbb_.AddOffset(LanguageCount::VT_LANGUAGE_CODE, language_code);
  }
  void add_count(uint32_t count) {
    fbb_.AddElement<uint32_t>(LanguageCount::VT_COUNT, count, 0);
  }
  explicit LanguageCountBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LanguageCount> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LanguageCount>(end);
    fbb_.Required(o, LanguageCount::VT_LANGUAGE_CODE);
    return o;
  }
};

inline ::flatbuffers::Offset<LanguageCount> CreateLanguageCount(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> language_code = 0,
    uint32_t count = 0) {
  LanguageCountBuilder builder_(_fbb);
  builder_.add_count(count);
  builder_.add_language_code(language_code);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LanguageCount> CreateLanguageCountDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *language_code = nullptr,
    uint32_t count = 0) {
  auto language_code__ = language_code ? _fbb.CreateString(language_code) : 0;
  return GRIMWebTraining::CreateLanguageCount(
      _fbb,
      language_code__,
      count);
}

struct ExampleIndex FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ExampleIndexBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EXAMPLE_ID = 4,
    VT_OFFSET = 6,
    VT_SIZE = 8,
    VT_SOURCE_TYPE = 10,
    VT_RELIABILITY_SCORE = 12,
    VT_TOKEN_COUNT = 14
  };
  const ::flatbuffers::String *example_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXAMPLE_ID);
  }
  uint64_t offset() const {
    return GetField<uint64_t>(VT_OFFSET, 0);
  }
  uint32_t size() const {
    return GetField<uint32_t>(VT_SIZE, 0);
  }
  GRIMWebTraining::SourceType source_type() const {
    return static_cast<GRIMWebTraining::SourceType>(GetField<int8_t>(VT_SOURCE_TYPE, 0));
  }
  float reliability_score() const {
    return GetField<float>(VT_RELIABILITY_SCORE, 0.0f);
  }
  uint32_t token_count() const {
    return GetField<uint32_t>(VT_TOKEN_COUNT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_EXAMPLE_ID) &&
           verifier.VerifyString(example_id()) &&
           VerifyField<uint64_t>(verifier, VT_OFFSET, 8) &&
           VerifyField<uint32_t>(verifier, VT_SIZE, 4) &&
           VerifyField<int8_t>(verifier, VT_SOURCE_TYPE, 1) &&
           VerifyField<float>(verifier, VT_RELIABILITY_SCORE, 4) &&
           VerifyField<uint32_t>(verifier, VT_TOKEN_COUNT, 4) &&
           verifier.EndTable();
  }
};

struct ExampleIndexBuilder {
  typedef ExampleIndex Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_example_id(::flatbuffers::Offset<::flatbuffers::String> example_id) {
    fbb_.AddOffset(ExampleIndex::VT_EXAMPLE_ID, example_id);
  }
  void add_offset(uint64_t offset) {
    fbb_.AddElement<uint64_t>(ExampleIndex::VT_OFFSET, offset, 0);
  }
  void add_size(uint32_t size) {
    fbb_.AddElement<uint32_t>(ExampleIndex::VT_SIZE, size, 0);
  }
  void add_source_type(GRIMWebTraining::SourceType source_type) {
    fbb_.AddElement<int8_t>(ExampleIndex::VT_SOURCE_TYPE, static_cast<int8_t>(source_type), 0);
  }
  void add_reliability_score(float reliability_score) {
    fbb_.AddElement<float>(ExampleIndex::VT_RELIABILITY_SCORE, reliability_score, 0.0f);
  }
  void add_token_count(uint32_t token_count) {
    fbb_.AddElement<uint32_t>(ExampleIndex::VT_TOKEN_COUNT, token_count, 0);
  }
  explicit ExampleIndexBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ExampleIndex> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ExampleIndex>(end);
    fbb_.Required(o, ExampleIndex::VT_EXAMPLE_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<ExampleIndex> CreateExampleIndex(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> example_id = 0,
    uint64_t offset = 0,
    uint32_t size = 0,
    GRIMWebTraining::SourceType source_type = GRIMWebTraining::SourceType_UNKNOWN,
    float reliability_score = 0.0f,
    uint32_t token_count = 0) {
  ExampleIndexBuilder builder_(_fbb);
  builder_.add_offset(offset);
  builder_.add_token_count(token_count);
  builder_.add_reliability_score(reliability_score);
  builder_.add_size(size);
  builder_.add_example_id(example_id);
  builder_.add_source_type(source_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ExampleIndex> CreateExampleIndexDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *example_id = nullptr,
    uint64_t offset = 0,
    uint32_t size = 0,
    GRIMWebTraining::SourceType source_type = GRIMWebTraining::SourceType_UNKNOWN,
    float reliability_score = 0.0f,
    uint32_t token_count = 0) {
  auto example_id__ = example_id ? _fbb.CreateString(example_id) : 0;
  return GRIMWebTraining::CreateExampleIndex(
      _fbb,
      example_id__,
      offset,
      size,
      source_type,
      reliability_score,
      token_count);
}

struct DatasetIndex FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DatasetIndexBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATASET_ID = 4,
    VT_INDICES = 6,
    VT_SORTED_BY_RELIABILITY = 8,
    VT_SORTED_BY_TOKEN_COUNT = 10,
    VT_SORTED_BY_SOURCE_TYPE = 12
  };
  const ::flatbuffers::String *dataset_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATASET_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::ExampleIndex>> *indices() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::ExampleIndex>> *>(VT_INDICES);
  }
  const ::flatbuffers::Vector<uint32_t> *sorted_by_reliability() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_SORTED_BY_RELIABILITY);
  }
  const ::flatbuffers::Vector<uint32_t> *sorted_by_token_count() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_SORTED_BY_TOKEN_COUNT);
  }
  const ::flatbuffers::Vector<uint32_t> *sorted_by_source_type() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_SORTED_BY_SOURCE_TYPE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DATASET_ID) &&
           verifier.VerifyString(dataset_id()) &&
           VerifyOffsetRequired(verifier, VT_INDICES) &&
           verifier.VerifyVector(indices()) &&
           verifier.VerifyVectorOfTables(indices()) &&
           VerifyOffset(verifier, VT_SORTED_BY_RELIABILITY) &&
           verifier.VerifyVector(sorted_by_reliability()) &&
           VerifyOffset(verifier, VT_SORTED_BY_TOKEN_COUNT) &&
           verifier.VerifyVector(sorted_by_token_count()) &&
           VerifyOffset(verifier, VT_SORTED_BY_SOURCE_TYPE) &&
           verifier.VerifyVector(sorted_by_source_type()) &&
           verifier.EndTable();
  }
};

struct DatasetIndexBuilder {
  typedef DatasetIndex Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_dataset_id(::flatbuffers::Offset<::flatbuffers::String> dataset_id) {
    fbb_.AddOffset(DatasetIndex::VT_DATASET_ID, dataset_id);
  }
  void add_indices(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::ExampleIndex>>> indices) {
    fbb_.AddOffset(DatasetIndex::VT_INDICES, indices);
  }
  void add_sorted_by_reliability(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> sorted_by_reliability) {
    fbb_.AddOffset(DatasetIndex::VT_SORTED_BY_RELIABILITY, sorted_by_reliability);
  }
  void add_sorted_by_token_count(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> sorted_by_token_count) {
    fbb_.AddOffset(DatasetIndex::VT_SORTED_BY_TOKEN_COUNT, sorted_by_token_count);
  }
  void add_sorted_by_source_type(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> sorted_by_source_type) {
    fbb_.AddOffset(DatasetIndex::VT_SORTED_BY_SOURCE_TYPE, sorted_by_source_type);
  }
  explicit DatasetIndexBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DatasetIndex> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DatasetIndex>(end);
    fbb_.Required(o, DatasetIndex::VT_DATASET_ID);
    fbb_.Required(o, DatasetIndex::VT_INDICES);
    return o;
  }
};

inline ::flatbuffers::Offset<DatasetIndex> CreateDatasetIndex(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> dataset_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMWebTraining::ExampleIndex>>> indices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> sorted_by_reliability = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> sorted_by_token_count = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> sorted_by_source_type = 0) {
  DatasetIndexBuilder builder_(_fbb);
  builder_.add_sorted_by_source_type(sorted_by_source_type);
  builder_.add_sorted_by_token_count(sorted_by_token_count);
  builder_.add_sorted_by_reliability(sorted_by_reliability);
  builder_.add_indices(indices);
  builder_.add_dataset_id(dataset_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DatasetIndex> CreateDatasetIndexDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *dataset_id = nullptr,
    const std::vector<::flatbuffers::Offset<GRIMWebTraining::ExampleIndex>> *indices = nullptr,
    const std::vector<uint32_t> *sorted_by_reliability = nullptr,
    const std::vector<uint32_t> *sorted_by_token_count = nullptr,
    const std::vector<uint32_t> *sorted_by_source_type = nullptr) {
  auto dataset_id__ = dataset_id ? _fbb.CreateString(dataset_id) : 0;
  auto indices__ = indices ? _fbb.CreateVector<::flatbuffers::Offset<GRIMWebTraining::ExampleIndex>>(*indices) : 0;
  auto sorted_by_reliability__ = sorted_by_reliability ? _fbb.CreateVector<uint32_t>(*sorted_by_reliability) : 0;
  auto sorted_by_token_count__ = sorted_by_token_count ? _fbb.CreateVector<uint32_t>(*sorted_by_token_count) : 0;
  auto sorted_by_source_type__ = sorted_by_source_type ? _fbb.CreateVector<uint32_t>(*sorted_by_source_type) : 0;
  return GRIMWebTraining::CreateDatasetIndex(
      _fbb,
      dataset_id__,
      indices__,
      sorted_by_reliability__,
      sorted_by_token_count__,
      sorted_by_source_type__);
}

inline const GRIMWebTraining::WebTrainingDataset *GetWebTrainingDataset(const void *buf) {
  return ::flatbuffers::GetRoot<GRIMWebTraining::WebTrainingDataset>(buf);
}

inline const GRIMWebTraining::WebTrainingDataset *GetSizePrefixedWebTrainingDataset(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GRIMWebTraining::WebTrainingDataset>(buf);
}

inline const char *WebTrainingDatasetIdentifier() {
  return "GWBT";
}

inline bool WebTrainingDatasetBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, WebTrainingDatasetIdentifier());
}

inline bool SizePrefixedWebTrainingDatasetBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, WebTrainingDatasetIdentifier(), true);
}

inline bool VerifyWebTrainingDatasetBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GRIMWebTraining::WebTrainingDataset>(WebTrainingDatasetIdentifier());
}

inline bool VerifySizePrefixedWebTrainingDatasetBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GRIMWebTraining::WebTrainingDataset>(WebTrainingDatasetIdentifier());
}

inline const char *WebTrainingDatasetExtension() {
  return "gwbt";
}

inline void FinishWebTrainingDatasetBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIMWebTraining::WebTrainingDataset> root) {
  fbb.Finish(root, WebTrainingDatasetIdentifier());
}

inline void FinishSizePrefixedWebTrainingDatasetBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIMWebTraining::WebTrainingDataset> root) {
  fbb.FinishSizePrefixed(root, WebTrainingDatasetIdentifier());
}

}  // namespace GRIMWebTraining

#endif  // FLATBUFFERS_GENERATED_WEBTRAININGDATA_GRIMWEBTRAINING_H_
