#pragma once
#include <string>
#include <vector>
#include <unordered_map>
#include <ctime>

namespace GRIM {



// ================================
// ENUM DEFINITIONS
// ================================

enum class SourceTag { UserVoice, UserText, SystemHW, SystemSW, NetworkAPI, GrimInternal };
enum class TypeTag   { Fact, Event, Command, Status, Summary, LearnedCommand, UnknownCommand, Prediction };
enum class IntentTag { Inform, Ask, SetPref, Correct, StatusUpdate, Query };
enum class ContextTag{ Conversation, Wake, DevMode, Monitor, SystemBoot,CommandLearning };
enum class ConfidenceTag { LowConf, HighConf, AutoGenerated, UserVerified };

// ================================
// STRING MAPS
// ================================

static const std::unordered_map<SourceTag, std::string> SourceNames = {
    {SourceTag::UserVoice, "user.voice"},
    {SourceTag::UserText, "user.text"},
    {SourceTag::SystemHW, "system.hw"},
    {SourceTag::SystemSW, "system.sw"},
    {SourceTag::NetworkAPI, "network.api"},
    {SourceTag::GrimInternal, "grim.internal"}
};

static const std::unordered_map<TypeTag, std::string> TypeNames = {
    {TypeTag::Fact, "fact"},
    {TypeTag::Event, "event"},
    {TypeTag::Command, "command"},
    {TypeTag::Status, "status"},
    {TypeTag::Summary, "summary"},
    {TypeTag::LearnedCommand, "learnedcommand"},
    {TypeTag::UnknownCommand, "unkowncommand"},
    {TypeTag::Prediction, "prediction"}
};

static const std::unordered_map<IntentTag, std::string> IntentNames = {
    {IntentTag::Inform, "inform"},
    {IntentTag::Ask, "ask"},
    {IntentTag::SetPref, "set_pref"},
    {IntentTag::Correct, "correct"},
    {IntentTag::StatusUpdate, "status_update"},
    {IntentTag::Query, "query"}
};

static const std::unordered_map<ContextTag, std::string> ContextNames = {
    {ContextTag::Conversation, "conversation"},
    {ContextTag::Wake, "wake"},
    {ContextTag::DevMode, "dev_mode"},
    {ContextTag::Monitor, "monitor"},
    {ContextTag::SystemBoot, "system_boot"}
};

static const std::unordered_map<ConfidenceTag, std::string> ConfidenceNames = {
    {ConfidenceTag::LowConf, "low_conf"},
    {ConfidenceTag::HighConf, "high_conf"},
    {ConfidenceTag::AutoGenerated, "auto_generated"},
    {ConfidenceTag::UserVerified, "user_verified"}
};

// ================================
// HELPER FUNCTIONS
// ================================

template<typename EnumType>
inline std::string toString(EnumType value, const std::unordered_map<EnumType, std::string>& map)
{
    auto it = map.find(value);
    if (it != map.end()) return it->second;
    return "unknown";
}

template<typename EnumType>
inline EnumType fromString(const std::string& s, const std::unordered_map<EnumType, std::string>& map, EnumType fallback)
{
    for (const auto& [k, v] : map)
        if (v == s) return k;
    return fallback;
}

// ================================
// MEMORY OBJECT CLASS
// ================================

class MemoryObject {
public:
    std::string id;
    std::time_t timestamp;

    SourceTag source;
    TypeTag type;
    IntentTag intent;
    ContextTag context;
    float confidence;

    std::string raw;
    std::string normalized;
    std::vector<std::string> tags;

    // Constructors
    MemoryObject()
        : id(""), timestamp(std::time(nullptr)),
          source(SourceTag::GrimInternal),
          type(TypeTag::Fact),
          intent(IntentTag::Inform),
          context(ContextTag::Conversation),
          confidence(1.0f) {}

    MemoryObject(SourceTag src, TypeTag t, IntentTag i, ContextTag c,
                 const std::string& rawInput, float conf = 1.0f)
        : id(generateUUID()),
          timestamp(std::time(nullptr)),
          source(src), type(t), intent(i), context(c),
          confidence(conf), raw(rawInput), normalized(rawInput) {}

    // Serialization helpers
    std::string toJSON() const;
    static MemoryObject fromJSON(const std::string& jsonStr);


    static std::string generateUUID();
};


} // namespace GRIM
