// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_UNIFIEDMEMORY_GRIM_MEMORY_H_
#define FLATBUFFERS_GENERATED_UNIFIEDMEMORY_GRIM_MEMORY_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25,
             "Non-compatible flatbuffers version included");

namespace GRIM {
namespace Memory {

struct MemoryRecord;
struct MemoryRecordBuilder;

struct IndexEntry;
struct IndexEntryBuilder;

struct TagIndex;
struct TagIndexBuilder;

struct MemoryMetadata;
struct MemoryMetadataBuilder;

struct MemoryStore;
struct MemoryStoreBuilder;

enum CommType : int8_t {
  CommType_COMMAND = 0,
  CommType_QUESTION = 1,
  CommType_BANTER = 2,
  CommType_UNKNOWN = 3,
  CommType_MIN = CommType_COMMAND,
  CommType_MAX = CommType_UNKNOWN
};

inline const CommType (&EnumValuesCommType())[4] {
  static const CommType values[] = {
    CommType_COMMAND,
    CommType_QUESTION,
    CommType_BANTER,
    CommType_UNKNOWN
  };
  return values;
}

inline const char * const *EnumNamesCommType() {
  static const char * const names[5] = {
    "COMMAND",
    "QUESTION",
    "BANTER",
    "UNKNOWN",
    nullptr
  };
  return names;
}

inline const char *EnumNameCommType(CommType e) {
  if (::flatbuffers::IsOutRange(e, CommType_COMMAND, CommType_UNKNOWN)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCommType()[index];
}

enum MemoryDomain : int8_t {
  MemoryDomain_BASE = 0,
  MemoryDomain_FIELD = 1,
  MemoryDomain_USER = 2,
  MemoryDomain_MIN = MemoryDomain_BASE,
  MemoryDomain_MAX = MemoryDomain_USER
};

inline const MemoryDomain (&EnumValuesMemoryDomain())[3] {
  static const MemoryDomain values[] = {
    MemoryDomain_BASE,
    MemoryDomain_FIELD,
    MemoryDomain_USER
  };
  return values;
}

inline const char * const *EnumNamesMemoryDomain() {
  static const char * const names[4] = {
    "BASE",
    "FIELD",
    "USER",
    nullptr
  };
  return names;
}

inline const char *EnumNameMemoryDomain(MemoryDomain e) {
  if (::flatbuffers::IsOutRange(e, MemoryDomain_BASE, MemoryDomain_USER)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMemoryDomain()[index];
}

enum TypeTag : int8_t {
  TypeTag_INT = 0,
  TypeTag_FLOAT = 1,
  TypeTag_STRING = 2,
  TypeTag_BOOL = 3,
  TypeTag_MIN = TypeTag_INT,
  TypeTag_MAX = TypeTag_BOOL
};

inline const TypeTag (&EnumValuesTypeTag())[4] {
  static const TypeTag values[] = {
    TypeTag_INT,
    TypeTag_FLOAT,
    TypeTag_STRING,
    TypeTag_BOOL
  };
  return values;
}

inline const char * const *EnumNamesTypeTag() {
  static const char * const names[5] = {
    "INT",
    "FLOAT",
    "STRING",
    "BOOL",
    nullptr
  };
  return names;
}

inline const char *EnumNameTypeTag(TypeTag e) {
  if (::flatbuffers::IsOutRange(e, TypeTag_INT, TypeTag_BOOL)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTypeTag()[index];
}

enum ContextType : int8_t {
  ContextType_CONVERSATION = 0,
  ContextType_WAKE = 1,
  ContextType_DEV_MODE = 2,
  ContextType_MIN = ContextType_CONVERSATION,
  ContextType_MAX = ContextType_DEV_MODE
};

inline const ContextType (&EnumValuesContextType())[3] {
  static const ContextType values[] = {
    ContextType_CONVERSATION,
    ContextType_WAKE,
    ContextType_DEV_MODE
  };
  return values;
}

inline const char * const *EnumNamesContextType() {
  static const char * const names[4] = {
    "CONVERSATION",
    "WAKE",
    "DEV_MODE",
    nullptr
  };
  return names;
}

inline const char *EnumNameContextType(ContextType e) {
  if (::flatbuffers::IsOutRange(e, ContextType_CONVERSATION, ContextType_DEV_MODE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesContextType()[index];
}

enum Modality : int8_t {
  Modality_TEXT = 0,
  Modality_AUDIO = 1,
  Modality_VISION = 2,
  Modality_SENSOR = 3,
  Modality_MIN = Modality_TEXT,
  Modality_MAX = Modality_SENSOR
};

inline const Modality (&EnumValuesModality())[4] {
  static const Modality values[] = {
    Modality_TEXT,
    Modality_AUDIO,
    Modality_VISION,
    Modality_SENSOR
  };
  return values;
}

inline const char * const *EnumNamesModality() {
  static const char * const names[5] = {
    "TEXT",
    "AUDIO",
    "VISION",
    "SENSOR",
    nullptr
  };
  return names;
}

inline const char *EnumNameModality(Modality e) {
  if (::flatbuffers::IsOutRange(e, Modality_TEXT, Modality_SENSOR)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesModality()[index];
}

struct MemoryRecord FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MemoryRecordBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TIMESTAMP = 6,
    VT_DOMAIN = 8,
    VT_TYPE = 10,
    VT_CONTEXT = 12,
    VT_COMM_TYPE = 14,
    VT_MODALITY = 16,
    VT_RAW = 18,
    VT_NORMALIZED = 20,
    VT_TAGS = 22,
    VT_CONFIDENCE = 24,
    VT_IMPORTANCE = 26,
    VT_RECENCY_WEIGHT = 28,
    VT_EMBEDDING = 30,
    VT_PARENT_ID = 32,
    VT_RELATED_IDS = 34
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  GRIM::Memory::MemoryDomain domain() const {
    return static_cast<GRIM::Memory::MemoryDomain>(GetField<int8_t>(VT_DOMAIN, 0));
  }
  GRIM::Memory::TypeTag type() const {
    return static_cast<GRIM::Memory::TypeTag>(GetField<int8_t>(VT_TYPE, 0));
  }
  GRIM::Memory::ContextType context() const {
    return static_cast<GRIM::Memory::ContextType>(GetField<int8_t>(VT_CONTEXT, 0));
  }
  GRIM::Memory::CommType comm_type() const {
    return static_cast<GRIM::Memory::CommType>(GetField<int8_t>(VT_COMM_TYPE, 0));
  }
  GRIM::Memory::Modality modality() const {
    return static_cast<GRIM::Memory::Modality>(GetField<int8_t>(VT_MODALITY, 0));
  }
  const ::flatbuffers::String *raw() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RAW);
  }
  const ::flatbuffers::String *normalized() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NORMALIZED);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *tags() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_TAGS);
  }
  float confidence() const {
    return GetField<float>(VT_CONFIDENCE, 0.0f);
  }
  float importance() const {
    return GetField<float>(VT_IMPORTANCE, 1.0f);
  }
  float recency_weight() const {
    return GetField<float>(VT_RECENCY_WEIGHT, 1.0f);
  }
  const ::flatbuffers::Vector<float> *embedding() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_EMBEDDING);
  }
  uint64_t parent_id() const {
    return GetField<uint64_t>(VT_PARENT_ID, 0);
  }
  const ::flatbuffers::Vector<uint64_t> *related_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_RELATED_IDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<int8_t>(verifier, VT_DOMAIN, 1) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_CONTEXT, 1) &&
           VerifyField<int8_t>(verifier, VT_COMM_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_MODALITY, 1) &&
           VerifyOffset(verifier, VT_RAW) &&
           verifier.VerifyString(raw()) &&
           VerifyOffset(verifier, VT_NORMALIZED) &&
           verifier.VerifyString(normalized()) &&
           VerifyOffset(verifier, VT_TAGS) &&
           verifier.VerifyVector(tags()) &&
           verifier.VerifyVectorOfStrings(tags()) &&
           VerifyField<float>(verifier, VT_CONFIDENCE, 4) &&
           VerifyField<float>(verifier, VT_IMPORTANCE, 4) &&
           VerifyField<float>(verifier, VT_RECENCY_WEIGHT, 4) &&
           VerifyOffset(verifier, VT_EMBEDDING) &&
           verifier.VerifyVector(embedding()) &&
           VerifyField<uint64_t>(verifier, VT_PARENT_ID, 8) &&
           VerifyOffset(verifier, VT_RELATED_IDS) &&
           verifier.VerifyVector(related_ids()) &&
           verifier.EndTable();
  }
};

struct MemoryRecordBuilder {
  typedef MemoryRecord Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(MemoryRecord::VT_ID, id, 0);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(MemoryRecord::VT_TIMESTAMP, timestamp, 0);
  }
  void add_domain(GRIM::Memory::MemoryDomain domain) {
    fbb_.AddElement<int8_t>(MemoryRecord::VT_DOMAIN, static_cast<int8_t>(domain), 0);
  }
  void add_type(GRIM::Memory::TypeTag type) {
    fbb_.AddElement<int8_t>(MemoryRecord::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_context(GRIM::Memory::ContextType context) {
    fbb_.AddElement<int8_t>(MemoryRecord::VT_CONTEXT, static_cast<int8_t>(context), 0);
  }
  void add_comm_type(GRIM::Memory::CommType comm_type) {
    fbb_.AddElement<int8_t>(MemoryRecord::VT_COMM_TYPE, static_cast<int8_t>(comm_type), 0);
  }
  void add_modality(GRIM::Memory::Modality modality) {
    fbb_.AddElement<int8_t>(MemoryRecord::VT_MODALITY, static_cast<int8_t>(modality), 0);
  }
  void add_raw(::flatbuffers::Offset<::flatbuffers::String> raw) {
    fbb_.AddOffset(MemoryRecord::VT_RAW, raw);
  }
  void add_normalized(::flatbuffers::Offset<::flatbuffers::String> normalized) {
    fbb_.AddOffset(MemoryRecord::VT_NORMALIZED, normalized);
  }
  void add_tags(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> tags) {
    fbb_.AddOffset(MemoryRecord::VT_TAGS, tags);
  }
  void add_confidence(float confidence) {
    fbb_.AddElement<float>(MemoryRecord::VT_CONFIDENCE, confidence, 0.0f);
  }
  void add_importance(float importance) {
    fbb_.AddElement<float>(MemoryRecord::VT_IMPORTANCE, importance, 1.0f);
  }
  void add_recency_weight(float recency_weight) {
    fbb_.AddElement<float>(MemoryRecord::VT_RECENCY_WEIGHT, recency_weight, 1.0f);
  }
  void add_embedding(::flatbuffers::Offset<::flatbuffers::Vector<float>> embedding) {
    fbb_.AddOffset(MemoryRecord::VT_EMBEDDING, embedding);
  }
  void add_parent_id(uint64_t parent_id) {
    fbb_.AddElement<uint64_t>(MemoryRecord::VT_PARENT_ID, parent_id, 0);
  }
  void add_related_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> related_ids) {
    fbb_.AddOffset(MemoryRecord::VT_RELATED_IDS, related_ids);
  }
  explicit MemoryRecordBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MemoryRecord> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MemoryRecord>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MemoryRecord> CreateMemoryRecord(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    uint64_t timestamp = 0,
    GRIM::Memory::MemoryDomain domain = GRIM::Memory::MemoryDomain_BASE,
    GRIM::Memory::TypeTag type = GRIM::Memory::TypeTag_STRING,
    GRIM::Memory::ContextType context = GRIM::Memory::ContextType_CONVERSATION,
    GRIM::Memory::CommType comm_type = GRIM::Memory::CommType_COMMAND,
    GRIM::Memory::Modality modality = GRIM::Memory::Modality_TEXT,
    ::flatbuffers::Offset<::flatbuffers::String> raw = 0,
    ::flatbuffers::Offset<::flatbuffers::String> normalized = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> tags = 0,
    float confidence = 0.0f,
    float importance = 1.0f,
    float recency_weight = 1.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> embedding = 0,
    uint64_t parent_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> related_ids = 0) {
  MemoryRecordBuilder builder_(_fbb);
  builder_.add_parent_id(parent_id);
  builder_.add_timestamp(timestamp);
  builder_.add_id(id);
  builder_.add_related_ids(related_ids);
  builder_.add_embedding(embedding);
  builder_.add_recency_weight(recency_weight);
  builder_.add_importance(importance);
  builder_.add_confidence(confidence);
  builder_.add_tags(tags);
  builder_.add_normalized(normalized);
  builder_.add_raw(raw);
  builder_.add_modality(modality);
  builder_.add_comm_type(comm_type);
  builder_.add_context(context);
  builder_.add_type(type);
  builder_.add_domain(domain);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MemoryRecord> CreateMemoryRecordDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    uint64_t timestamp = 0,
    GRIM::Memory::MemoryDomain domain = GRIM::Memory::MemoryDomain_BASE,
    GRIM::Memory::TypeTag type = GRIM::Memory::TypeTag_STRING,
    GRIM::Memory::ContextType context = GRIM::Memory::ContextType_CONVERSATION,
    GRIM::Memory::CommType comm_type = GRIM::Memory::CommType_COMMAND,
    GRIM::Memory::Modality modality = GRIM::Memory::Modality_TEXT,
    const char *raw = nullptr,
    const char *normalized = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *tags = nullptr,
    float confidence = 0.0f,
    float importance = 1.0f,
    float recency_weight = 1.0f,
    const std::vector<float> *embedding = nullptr,
    uint64_t parent_id = 0,
    const std::vector<uint64_t> *related_ids = nullptr) {
  auto raw__ = raw ? _fbb.CreateString(raw) : 0;
  auto normalized__ = normalized ? _fbb.CreateString(normalized) : 0;
  auto tags__ = tags ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*tags) : 0;
  auto embedding__ = embedding ? _fbb.CreateVector<float>(*embedding) : 0;
  auto related_ids__ = related_ids ? _fbb.CreateVector<uint64_t>(*related_ids) : 0;
  return GRIM::Memory::CreateMemoryRecord(
      _fbb,
      id,
      timestamp,
      domain,
      type,
      context,
      comm_type,
      modality,
      raw__,
      normalized__,
      tags__,
      confidence,
      importance,
      recency_weight,
      embedding__,
      parent_id,
      related_ids__);
}

struct IndexEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IndexEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_OFFSET = 6,
    VT_EMBEDDING = 8,
    VT_TYPE = 10,
    VT_DOMAIN = 12,
    VT_TIMESTAMP = 14,
    VT_CONFIDENCE = 16,
    VT_TAGS = 18
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  uint64_t offset() const {
    return GetField<uint64_t>(VT_OFFSET, 0);
  }
  const ::flatbuffers::Vector<float> *embedding() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_EMBEDDING);
  }
  GRIM::Memory::TypeTag type() const {
    return static_cast<GRIM::Memory::TypeTag>(GetField<int8_t>(VT_TYPE, 0));
  }
  GRIM::Memory::MemoryDomain domain() const {
    return static_cast<GRIM::Memory::MemoryDomain>(GetField<int8_t>(VT_DOMAIN, 0));
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  float confidence() const {
    return GetField<float>(VT_CONFIDENCE, 0.0f);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *tags() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_TAGS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_OFFSET, 8) &&
           VerifyOffset(verifier, VT_EMBEDDING) &&
           verifier.VerifyVector(embedding()) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_DOMAIN, 1) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<float>(verifier, VT_CONFIDENCE, 4) &&
           VerifyOffset(verifier, VT_TAGS) &&
           verifier.VerifyVector(tags()) &&
           verifier.VerifyVectorOfStrings(tags()) &&
           verifier.EndTable();
  }
};

struct IndexEntryBuilder {
  typedef IndexEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(IndexEntry::VT_ID, id, 0);
  }
  void add_offset(uint64_t offset) {
    fbb_.AddElement<uint64_t>(IndexEntry::VT_OFFSET, offset, 0);
  }
  void add_embedding(::flatbuffers::Offset<::flatbuffers::Vector<float>> embedding) {
    fbb_.AddOffset(IndexEntry::VT_EMBEDDING, embedding);
  }
  void add_type(GRIM::Memory::TypeTag type) {
    fbb_.AddElement<int8_t>(IndexEntry::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_domain(GRIM::Memory::MemoryDomain domain) {
    fbb_.AddElement<int8_t>(IndexEntry::VT_DOMAIN, static_cast<int8_t>(domain), 0);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(IndexEntry::VT_TIMESTAMP, timestamp, 0);
  }
  void add_confidence(float confidence) {
    fbb_.AddElement<float>(IndexEntry::VT_CONFIDENCE, confidence, 0.0f);
  }
  void add_tags(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> tags) {
    fbb_.AddOffset(IndexEntry::VT_TAGS, tags);
  }
  explicit IndexEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IndexEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IndexEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<IndexEntry> CreateIndexEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    uint64_t offset = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> embedding = 0,
    GRIM::Memory::TypeTag type = GRIM::Memory::TypeTag_STRING,
    GRIM::Memory::MemoryDomain domain = GRIM::Memory::MemoryDomain_BASE,
    uint64_t timestamp = 0,
    float confidence = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> tags = 0) {
  IndexEntryBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_offset(offset);
  builder_.add_id(id);
  builder_.add_tags(tags);
  builder_.add_confidence(confidence);
  builder_.add_embedding(embedding);
  builder_.add_domain(domain);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<IndexEntry> CreateIndexEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    uint64_t offset = 0,
    const std::vector<float> *embedding = nullptr,
    GRIM::Memory::TypeTag type = GRIM::Memory::TypeTag_STRING,
    GRIM::Memory::MemoryDomain domain = GRIM::Memory::MemoryDomain_BASE,
    uint64_t timestamp = 0,
    float confidence = 0.0f,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *tags = nullptr) {
  auto embedding__ = embedding ? _fbb.CreateVector<float>(*embedding) : 0;
  auto tags__ = tags ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*tags) : 0;
  return GRIM::Memory::CreateIndexEntry(
      _fbb,
      id,
      offset,
      embedding__,
      type,
      domain,
      timestamp,
      confidence,
      tags__);
}

struct TagIndex FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TagIndexBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TAG = 4,
    VT_MEMORY_IDS = 6
  };
  const ::flatbuffers::String *tag() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TAG);
  }
  const ::flatbuffers::Vector<uint64_t> *memory_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_MEMORY_IDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TAG) &&
           verifier.VerifyString(tag()) &&
           VerifyOffset(verifier, VT_MEMORY_IDS) &&
           verifier.VerifyVector(memory_ids()) &&
           verifier.EndTable();
  }
};

struct TagIndexBuilder {
  typedef TagIndex Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tag(::flatbuffers::Offset<::flatbuffers::String> tag) {
    fbb_.AddOffset(TagIndex::VT_TAG, tag);
  }
  void add_memory_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> memory_ids) {
    fbb_.AddOffset(TagIndex::VT_MEMORY_IDS, memory_ids);
  }
  explicit TagIndexBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TagIndex> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TagIndex>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TagIndex> CreateTagIndex(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> tag = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> memory_ids = 0) {
  TagIndexBuilder builder_(_fbb);
  builder_.add_memory_ids(memory_ids);
  builder_.add_tag(tag);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TagIndex> CreateTagIndexDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *tag = nullptr,
    const std::vector<uint64_t> *memory_ids = nullptr) {
  auto tag__ = tag ? _fbb.CreateString(tag) : 0;
  auto memory_ids__ = memory_ids ? _fbb.CreateVector<uint64_t>(*memory_ids) : 0;
  return GRIM::Memory::CreateTagIndex(
      _fbb,
      tag__,
      memory_ids__);
}

struct MemoryMetadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MemoryMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCHEMA_VERSION = 4,
    VT_BUILD_TIME = 6,
    VT_RECORD_COUNT = 8,
    VT_TOTAL_SIZE_BYTES = 10
  };
  uint32_t schema_version() const {
    return GetField<uint32_t>(VT_SCHEMA_VERSION, 1);
  }
  uint64_t build_time() const {
    return GetField<uint64_t>(VT_BUILD_TIME, 0);
  }
  uint64_t record_count() const {
    return GetField<uint64_t>(VT_RECORD_COUNT, 0);
  }
  uint64_t total_size_bytes() const {
    return GetField<uint64_t>(VT_TOTAL_SIZE_BYTES, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SCHEMA_VERSION, 4) &&
           VerifyField<uint64_t>(verifier, VT_BUILD_TIME, 8) &&
           VerifyField<uint64_t>(verifier, VT_RECORD_COUNT, 8) &&
           VerifyField<uint64_t>(verifier, VT_TOTAL_SIZE_BYTES, 8) &&
           verifier.EndTable();
  }
};

struct MemoryMetadataBuilder {
  typedef MemoryMetadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_schema_version(uint32_t schema_version) {
    fbb_.AddElement<uint32_t>(MemoryMetadata::VT_SCHEMA_VERSION, schema_version, 1);
  }
  void add_build_time(uint64_t build_time) {
    fbb_.AddElement<uint64_t>(MemoryMetadata::VT_BUILD_TIME, build_time, 0);
  }
  void add_record_count(uint64_t record_count) {
    fbb_.AddElement<uint64_t>(MemoryMetadata::VT_RECORD_COUNT, record_count, 0);
  }
  void add_total_size_bytes(uint64_t total_size_bytes) {
    fbb_.AddElement<uint64_t>(MemoryMetadata::VT_TOTAL_SIZE_BYTES, total_size_bytes, 0);
  }
  explicit MemoryMetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MemoryMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MemoryMetadata>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MemoryMetadata> CreateMemoryMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t schema_version = 1,
    uint64_t build_time = 0,
    uint64_t record_count = 0,
    uint64_t total_size_bytes = 0) {
  MemoryMetadataBuilder builder_(_fbb);
  builder_.add_total_size_bytes(total_size_bytes);
  builder_.add_record_count(record_count);
  builder_.add_build_time(build_time);
  builder_.add_schema_version(schema_version);
  return builder_.Finish();
}

struct MemoryStore FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MemoryStoreBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_METADATA = 4,
    VT_RECORDS = 6,
    VT_INDEX = 8,
    VT_TAG_INDEX = 10
  };
  const GRIM::Memory::MemoryMetadata *metadata() const {
    return GetPointer<const GRIM::Memory::MemoryMetadata *>(VT_METADATA);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIM::Memory::MemoryRecord>> *records() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIM::Memory::MemoryRecord>> *>(VT_RECORDS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIM::Memory::IndexEntry>> *index() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIM::Memory::IndexEntry>> *>(VT_INDEX);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIM::Memory::TagIndex>> *tag_index() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIM::Memory::TagIndex>> *>(VT_TAG_INDEX);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_METADATA) &&
           verifier.VerifyTable(metadata()) &&
           VerifyOffset(verifier, VT_RECORDS) &&
           verifier.VerifyVector(records()) &&
           verifier.VerifyVectorOfTables(records()) &&
           VerifyOffset(verifier, VT_INDEX) &&
           verifier.VerifyVector(index()) &&
           verifier.VerifyVectorOfTables(index()) &&
           VerifyOffset(verifier, VT_TAG_INDEX) &&
           verifier.VerifyVector(tag_index()) &&
           verifier.VerifyVectorOfTables(tag_index()) &&
           verifier.EndTable();
  }
};

struct MemoryStoreBuilder {
  typedef MemoryStore Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_metadata(::flatbuffers::Offset<GRIM::Memory::MemoryMetadata> metadata) {
    fbb_.AddOffset(MemoryStore::VT_METADATA, metadata);
  }
  void add_records(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIM::Memory::MemoryRecord>>> records) {
    fbb_.AddOffset(MemoryStore::VT_RECORDS, records);
  }
  void add_index(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIM::Memory::IndexEntry>>> index) {
    fbb_.AddOffset(MemoryStore::VT_INDEX, index);
  }
  void add_tag_index(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIM::Memory::TagIndex>>> tag_index) {
    fbb_.AddOffset(MemoryStore::VT_TAG_INDEX, tag_index);
  }
  explicit MemoryStoreBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MemoryStore> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MemoryStore>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MemoryStore> CreateMemoryStore(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<GRIM::Memory::MemoryMetadata> metadata = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIM::Memory::MemoryRecord>>> records = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIM::Memory::IndexEntry>>> index = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIM::Memory::TagIndex>>> tag_index = 0) {
  MemoryStoreBuilder builder_(_fbb);
  builder_.add_tag_index(tag_index);
  builder_.add_index(index);
  builder_.add_records(records);
  builder_.add_metadata(metadata);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MemoryStore> CreateMemoryStoreDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<GRIM::Memory::MemoryMetadata> metadata = 0,
    const std::vector<::flatbuffers::Offset<GRIM::Memory::MemoryRecord>> *records = nullptr,
    const std::vector<::flatbuffers::Offset<GRIM::Memory::IndexEntry>> *index = nullptr,
    const std::vector<::flatbuffers::Offset<GRIM::Memory::TagIndex>> *tag_index = nullptr) {
  auto records__ = records ? _fbb.CreateVector<::flatbuffers::Offset<GRIM::Memory::MemoryRecord>>(*records) : 0;
  auto index__ = index ? _fbb.CreateVector<::flatbuffers::Offset<GRIM::Memory::IndexEntry>>(*index) : 0;
  auto tag_index__ = tag_index ? _fbb.CreateVector<::flatbuffers::Offset<GRIM::Memory::TagIndex>>(*tag_index) : 0;
  return GRIM::Memory::CreateMemoryStore(
      _fbb,
      metadata,
      records__,
      index__,
      tag_index__);
}

inline const GRIM::Memory::MemoryStore *GetMemoryStore(const void *buf) {
  return ::flatbuffers::GetRoot<GRIM::Memory::MemoryStore>(buf);
}

inline const GRIM::Memory::MemoryStore *GetSizePrefixedMemoryStore(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GRIM::Memory::MemoryStore>(buf);
}

inline bool VerifyMemoryStoreBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GRIM::Memory::MemoryStore>(nullptr);
}

inline bool VerifySizePrefixedMemoryStoreBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GRIM::Memory::MemoryStore>(nullptr);
}

inline void FinishMemoryStoreBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIM::Memory::MemoryStore> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMemoryStoreBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIM::Memory::MemoryStore> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Memory
}  // namespace GRIM

#endif  // FLATBUFFERS_GENERATED_UNIFIEDMEMORY_GRIM_MEMORY_H_
