// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CHECKPOINTDATA_GRIMCHECKPOINT_H_
#define FLATBUFFERS_GENERATED_CHECKPOINTDATA_GRIMCHECKPOINT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25,
             "Non-compatible flatbuffers version included");

namespace GRIMCheckpoint {

struct CheckpointEntry;
struct CheckpointEntryBuilder;

struct Checkpoint;
struct CheckpointBuilder;

struct CheckpointEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CheckpointEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTENT = 4,
    VT_SOURCE_URL = 6,
    VT_SOURCE_TYPE = 8,
    VT_RELIABILITY_SCORE = 10,
    VT_FETCH_TIMESTAMP = 12,
    VT_CONTENT_HASH = 14
  };
  const ::flatbuffers::String *content() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONTENT);
  }
  const ::flatbuffers::String *source_url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_URL);
  }
  const ::flatbuffers::String *source_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_TYPE);
  }
  float reliability_score() const {
    return GetField<float>(VT_RELIABILITY_SCORE, 0.7f);
  }
  uint64_t fetch_timestamp() const {
    return GetField<uint64_t>(VT_FETCH_TIMESTAMP, 0);
  }
  uint64_t content_hash() const {
    return GetField<uint64_t>(VT_CONTENT_HASH, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CONTENT) &&
           verifier.VerifyString(content()) &&
           VerifyOffsetRequired(verifier, VT_SOURCE_URL) &&
           verifier.VerifyString(source_url()) &&
           VerifyOffset(verifier, VT_SOURCE_TYPE) &&
           verifier.VerifyString(source_type()) &&
           VerifyField<float>(verifier, VT_RELIABILITY_SCORE, 4) &&
           VerifyField<uint64_t>(verifier, VT_FETCH_TIMESTAMP, 8) &&
           VerifyField<uint64_t>(verifier, VT_CONTENT_HASH, 8) &&
           verifier.EndTable();
  }
};

struct CheckpointEntryBuilder {
  typedef CheckpointEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_content(::flatbuffers::Offset<::flatbuffers::String> content) {
    fbb_.AddOffset(CheckpointEntry::VT_CONTENT, content);
  }
  void add_source_url(::flatbuffers::Offset<::flatbuffers::String> source_url) {
    fbb_.AddOffset(CheckpointEntry::VT_SOURCE_URL, source_url);
  }
  void add_source_type(::flatbuffers::Offset<::flatbuffers::String> source_type) {
    fbb_.AddOffset(CheckpointEntry::VT_SOURCE_TYPE, source_type);
  }
  void add_reliability_score(float reliability_score) {
    fbb_.AddElement<float>(CheckpointEntry::VT_RELIABILITY_SCORE, reliability_score, 0.7f);
  }
  void add_fetch_timestamp(uint64_t fetch_timestamp) {
    fbb_.AddElement<uint64_t>(CheckpointEntry::VT_FETCH_TIMESTAMP, fetch_timestamp, 0);
  }
  void add_content_hash(uint64_t content_hash) {
    fbb_.AddElement<uint64_t>(CheckpointEntry::VT_CONTENT_HASH, content_hash, 0);
  }
  explicit CheckpointEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CheckpointEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CheckpointEntry>(end);
    fbb_.Required(o, CheckpointEntry::VT_CONTENT);
    fbb_.Required(o, CheckpointEntry::VT_SOURCE_URL);
    return o;
  }
};

inline ::flatbuffers::Offset<CheckpointEntry> CreateCheckpointEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> content = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_url = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_type = 0,
    float reliability_score = 0.7f,
    uint64_t fetch_timestamp = 0,
    uint64_t content_hash = 0) {
  CheckpointEntryBuilder builder_(_fbb);
  builder_.add_content_hash(content_hash);
  builder_.add_fetch_timestamp(fetch_timestamp);
  builder_.add_reliability_score(reliability_score);
  builder_.add_source_type(source_type);
  builder_.add_source_url(source_url);
  builder_.add_content(content);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CheckpointEntry> CreateCheckpointEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *content = nullptr,
    const char *source_url = nullptr,
    const char *source_type = nullptr,
    float reliability_score = 0.7f,
    uint64_t fetch_timestamp = 0,
    uint64_t content_hash = 0) {
  auto content__ = content ? _fbb.CreateString(content) : 0;
  auto source_url__ = source_url ? _fbb.CreateString(source_url) : 0;
  auto source_type__ = source_type ? _fbb.CreateString(source_type) : 0;
  return GRIMCheckpoint::CreateCheckpointEntry(
      _fbb,
      content__,
      source_url__,
      source_type__,
      reliability_score,
      fetch_timestamp,
      content_hash);
}

struct Checkpoint FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CheckpointBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTRIES = 4,
    VT_CHECKPOINT_ID = 6,
    VT_TOTAL_ENTRIES = 8,
    VT_CREATED_TIMESTAMP = 10,
    VT_COLLECTION_SESSION_ID = 12
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMCheckpoint::CheckpointEntry>> *entries() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMCheckpoint::CheckpointEntry>> *>(VT_ENTRIES);
  }
  uint32_t checkpoint_id() const {
    return GetField<uint32_t>(VT_CHECKPOINT_ID, 0);
  }
  uint32_t total_entries() const {
    return GetField<uint32_t>(VT_TOTAL_ENTRIES, 0);
  }
  uint64_t created_timestamp() const {
    return GetField<uint64_t>(VT_CREATED_TIMESTAMP, 0);
  }
  const ::flatbuffers::String *collection_session_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COLLECTION_SESSION_ID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENTRIES) &&
           verifier.VerifyVector(entries()) &&
           verifier.VerifyVectorOfTables(entries()) &&
           VerifyField<uint32_t>(verifier, VT_CHECKPOINT_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_TOTAL_ENTRIES, 4) &&
           VerifyField<uint64_t>(verifier, VT_CREATED_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_COLLECTION_SESSION_ID) &&
           verifier.VerifyString(collection_session_id()) &&
           verifier.EndTable();
  }
};

struct CheckpointBuilder {
  typedef Checkpoint Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entries(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMCheckpoint::CheckpointEntry>>> entries) {
    fbb_.AddOffset(Checkpoint::VT_ENTRIES, entries);
  }
  void add_checkpoint_id(uint32_t checkpoint_id) {
    fbb_.AddElement<uint32_t>(Checkpoint::VT_CHECKPOINT_ID, checkpoint_id, 0);
  }
  void add_total_entries(uint32_t total_entries) {
    fbb_.AddElement<uint32_t>(Checkpoint::VT_TOTAL_ENTRIES, total_entries, 0);
  }
  void add_created_timestamp(uint64_t created_timestamp) {
    fbb_.AddElement<uint64_t>(Checkpoint::VT_CREATED_TIMESTAMP, created_timestamp, 0);
  }
  void add_collection_session_id(::flatbuffers::Offset<::flatbuffers::String> collection_session_id) {
    fbb_.AddOffset(Checkpoint::VT_COLLECTION_SESSION_ID, collection_session_id);
  }
  explicit CheckpointBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Checkpoint> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Checkpoint>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Checkpoint> CreateCheckpoint(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMCheckpoint::CheckpointEntry>>> entries = 0,
    uint32_t checkpoint_id = 0,
    uint32_t total_entries = 0,
    uint64_t created_timestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::String> collection_session_id = 0) {
  CheckpointBuilder builder_(_fbb);
  builder_.add_created_timestamp(created_timestamp);
  builder_.add_collection_session_id(collection_session_id);
  builder_.add_total_entries(total_entries);
  builder_.add_checkpoint_id(checkpoint_id);
  builder_.add_entries(entries);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Checkpoint> CreateCheckpointDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<GRIMCheckpoint::CheckpointEntry>> *entries = nullptr,
    uint32_t checkpoint_id = 0,
    uint32_t total_entries = 0,
    uint64_t created_timestamp = 0,
    const char *collection_session_id = nullptr) {
  auto entries__ = entries ? _fbb.CreateVector<::flatbuffers::Offset<GRIMCheckpoint::CheckpointEntry>>(*entries) : 0;
  auto collection_session_id__ = collection_session_id ? _fbb.CreateString(collection_session_id) : 0;
  return GRIMCheckpoint::CreateCheckpoint(
      _fbb,
      entries__,
      checkpoint_id,
      total_entries,
      created_timestamp,
      collection_session_id__);
}

inline const GRIMCheckpoint::Checkpoint *GetCheckpoint(const void *buf) {
  return ::flatbuffers::GetRoot<GRIMCheckpoint::Checkpoint>(buf);
}

inline const GRIMCheckpoint::Checkpoint *GetSizePrefixedCheckpoint(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GRIMCheckpoint::Checkpoint>(buf);
}

inline const char *CheckpointIdentifier() {
  return "GRIM";
}

inline bool CheckpointBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, CheckpointIdentifier());
}

inline bool SizePrefixedCheckpointBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, CheckpointIdentifier(), true);
}

inline bool VerifyCheckpointBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GRIMCheckpoint::Checkpoint>(CheckpointIdentifier());
}

inline bool VerifySizePrefixedCheckpointBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GRIMCheckpoint::Checkpoint>(CheckpointIdentifier());
}

inline const char *CheckpointExtension() {
  return "ckpt";
}

inline void FinishCheckpointBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIMCheckpoint::Checkpoint> root) {
  fbb.Finish(root, CheckpointIdentifier());
}

inline void FinishSizePrefixedCheckpointBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIMCheckpoint::Checkpoint> root) {
  fbb.FinishSizePrefixed(root, CheckpointIdentifier());
}

}  // namespace GRIMCheckpoint

#endif  // FLATBUFFERS_GENERATED_CHECKPOINTDATA_GRIMCHECKPOINT_H_
