// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CONCEPTBLOCK_GRIMCONCEPT_H_
#define FLATBUFFERS_GENERATED_CONCEPTBLOCK_GRIMCONCEPT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace GRIMConcept {

struct ConceptExecutionStep;
struct ConceptExecutionStepBuilder;

struct SuccessCriterion;
struct SuccessCriterionBuilder;

struct Goal;
struct GoalBuilder;

struct ConceptBlock;
struct ConceptBlockBuilder;

struct ConceptBlockDataset;
struct ConceptBlockDatasetBuilder;

struct ConceptExecutionStep FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConceptExecutionStepBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OP = 4,
    VT_ARGS = 6,
    VT_ARG_SLOTS = 8,
    VT_RESULT = 10
  };
  const ::flatbuffers::String *op() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OP);
  }
  const ::flatbuffers::Vector<double> *args() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_ARGS);
  }
  const ::flatbuffers::Vector<int32_t> *arg_slots() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_ARG_SLOTS);
  }
  double result() const {
    return GetField<double>(VT_RESULT, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_OP) &&
           verifier.VerifyString(op()) &&
           VerifyOffset(verifier, VT_ARGS) &&
           verifier.VerifyVector(args()) &&
           VerifyOffset(verifier, VT_ARG_SLOTS) &&
           verifier.VerifyVector(arg_slots()) &&
           VerifyField<double>(verifier, VT_RESULT, 8) &&
           verifier.EndTable();
  }
};

struct ConceptExecutionStepBuilder {
  typedef ConceptExecutionStep Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_op(::flatbuffers::Offset<::flatbuffers::String> op) {
    fbb_.AddOffset(ConceptExecutionStep::VT_OP, op);
  }
  void add_args(::flatbuffers::Offset<::flatbuffers::Vector<double>> args) {
    fbb_.AddOffset(ConceptExecutionStep::VT_ARGS, args);
  }
  void add_arg_slots(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> arg_slots) {
    fbb_.AddOffset(ConceptExecutionStep::VT_ARG_SLOTS, arg_slots);
  }
  void add_result(double result) {
    fbb_.AddElement<double>(ConceptExecutionStep::VT_RESULT, result, 0.0);
  }
  explicit ConceptExecutionStepBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ConceptExecutionStep> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ConceptExecutionStep>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ConceptExecutionStep> CreateConceptExecutionStep(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> op = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> args = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> arg_slots = 0,
    double result = 0.0) {
  ConceptExecutionStepBuilder builder_(_fbb);
  builder_.add_result(result);
  builder_.add_arg_slots(arg_slots);
  builder_.add_args(args);
  builder_.add_op(op);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ConceptExecutionStep> CreateConceptExecutionStepDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *op = nullptr,
    const std::vector<double> *args = nullptr,
    const std::vector<int32_t> *arg_slots = nullptr,
    double result = 0.0) {
  auto op__ = op ? _fbb.CreateString(op) : 0;
  auto args__ = args ? _fbb.CreateVector<double>(*args) : 0;
  auto arg_slots__ = arg_slots ? _fbb.CreateVector<int32_t>(*arg_slots) : 0;
  return GRIMConcept::CreateConceptExecutionStep(
      _fbb,
      op__,
      args__,
      arg_slots__,
      result);
}

struct SuccessCriterion FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SuccessCriterionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CRITERION = 4,
    VT_EVIDENCE = 6
  };
  const ::flatbuffers::String *criterion() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CRITERION);
  }
  const ::flatbuffers::String *evidence() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EVIDENCE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CRITERION) &&
           verifier.VerifyString(criterion()) &&
           VerifyOffset(verifier, VT_EVIDENCE) &&
           verifier.VerifyString(evidence()) &&
           verifier.EndTable();
  }
};

struct SuccessCriterionBuilder {
  typedef SuccessCriterion Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_criterion(::flatbuffers::Offset<::flatbuffers::String> criterion) {
    fbb_.AddOffset(SuccessCriterion::VT_CRITERION, criterion);
  }
  void add_evidence(::flatbuffers::Offset<::flatbuffers::String> evidence) {
    fbb_.AddOffset(SuccessCriterion::VT_EVIDENCE, evidence);
  }
  explicit SuccessCriterionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SuccessCriterion> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SuccessCriterion>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SuccessCriterion> CreateSuccessCriterion(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> criterion = 0,
    ::flatbuffers::Offset<::flatbuffers::String> evidence = 0) {
  SuccessCriterionBuilder builder_(_fbb);
  builder_.add_evidence(evidence);
  builder_.add_criterion(criterion);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SuccessCriterion> CreateSuccessCriterionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *criterion = nullptr,
    const char *evidence = nullptr) {
  auto criterion__ = criterion ? _fbb.CreateString(criterion) : 0;
  auto evidence__ = evidence ? _fbb.CreateString(evidence) : 0;
  return GRIMConcept::CreateSuccessCriterion(
      _fbb,
      criterion__,
      evidence__);
}

struct Goal FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GoalBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_STATE = 4,
    VT_SUCCESS_CRITERIA = 6,
    VT_CONSTRAINTS = 8
  };
  const ::flatbuffers::String *target_state() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TARGET_STATE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMConcept::SuccessCriterion>> *success_criteria() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMConcept::SuccessCriterion>> *>(VT_SUCCESS_CRITERIA);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *constraints() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_CONSTRAINTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TARGET_STATE) &&
           verifier.VerifyString(target_state()) &&
           VerifyOffset(verifier, VT_SUCCESS_CRITERIA) &&
           verifier.VerifyVector(success_criteria()) &&
           verifier.VerifyVectorOfTables(success_criteria()) &&
           VerifyOffset(verifier, VT_CONSTRAINTS) &&
           verifier.VerifyVector(constraints()) &&
           verifier.VerifyVectorOfStrings(constraints()) &&
           verifier.EndTable();
  }
};

struct GoalBuilder {
  typedef Goal Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_state(::flatbuffers::Offset<::flatbuffers::String> target_state) {
    fbb_.AddOffset(Goal::VT_TARGET_STATE, target_state);
  }
  void add_success_criteria(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMConcept::SuccessCriterion>>> success_criteria) {
    fbb_.AddOffset(Goal::VT_SUCCESS_CRITERIA, success_criteria);
  }
  void add_constraints(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> constraints) {
    fbb_.AddOffset(Goal::VT_CONSTRAINTS, constraints);
  }
  explicit GoalBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Goal> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Goal>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Goal> CreateGoal(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> target_state = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMConcept::SuccessCriterion>>> success_criteria = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> constraints = 0) {
  GoalBuilder builder_(_fbb);
  builder_.add_constraints(constraints);
  builder_.add_success_criteria(success_criteria);
  builder_.add_target_state(target_state);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Goal> CreateGoalDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *target_state = nullptr,
    const std::vector<::flatbuffers::Offset<GRIMConcept::SuccessCriterion>> *success_criteria = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *constraints = nullptr) {
  auto target_state__ = target_state ? _fbb.CreateString(target_state) : 0;
  auto success_criteria__ = success_criteria ? _fbb.CreateVector<::flatbuffers::Offset<GRIMConcept::SuccessCriterion>>(*success_criteria) : 0;
  auto constraints__ = constraints ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*constraints) : 0;
  return GRIMConcept::CreateGoal(
      _fbb,
      target_state__,
      success_criteria__,
      constraints__);
}

struct ConceptBlock FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConceptBlockBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_PROMPT = 8,
    VT_INTERMEDIATES = 10,
    VT_ANSWER = 12,
    VT_EXPLANATION = 14,
    VT_EXECUTION = 16,
    VT_INTERMEDIATE_COUNT = 18,
    VT_STEP_INDEX = 20,
    VT_FORMAT_TYPE = 22,
    VT_SOURCE_SEQUENCE_ID = 24,
    VT_TIMESTAMP = 26,
    VT_GOAL = 28,
    VT_RAW = 30,
    VT_KNOWNS = 32,
    VT_UNKNOWNS = 34
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *prompt() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROMPT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *intermediates() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_INTERMEDIATES);
  }
  const ::flatbuffers::String *answer() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ANSWER);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *explanation() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_EXPLANATION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMConcept::ConceptExecutionStep>> *execution() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMConcept::ConceptExecutionStep>> *>(VT_EXECUTION);
  }
  int32_t intermediate_count() const {
    return GetField<int32_t>(VT_INTERMEDIATE_COUNT, 0);
  }
  const ::flatbuffers::Vector<int32_t> *step_index() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_STEP_INDEX);
  }
  const ::flatbuffers::String *format_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FORMAT_TYPE);
  }
  const ::flatbuffers::String *source_sequence_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_SEQUENCE_ID);
  }
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  const GRIMConcept::Goal *goal() const {
    return GetPointer<const GRIMConcept::Goal *>(VT_GOAL);
  }
  const ::flatbuffers::String *raw() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RAW);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *knowns() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_KNOWNS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *unknowns() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_UNKNOWNS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_PROMPT) &&
           verifier.VerifyString(prompt()) &&
           VerifyOffset(verifier, VT_INTERMEDIATES) &&
           verifier.VerifyVector(intermediates()) &&
           verifier.VerifyVectorOfStrings(intermediates()) &&
           VerifyOffset(verifier, VT_ANSWER) &&
           verifier.VerifyString(answer()) &&
           VerifyOffset(verifier, VT_EXPLANATION) &&
           verifier.VerifyVector(explanation()) &&
           verifier.VerifyVectorOfStrings(explanation()) &&
           VerifyOffset(verifier, VT_EXECUTION) &&
           verifier.VerifyVector(execution()) &&
           verifier.VerifyVectorOfTables(execution()) &&
           VerifyField<int32_t>(verifier, VT_INTERMEDIATE_COUNT, 4) &&
           VerifyOffset(verifier, VT_STEP_INDEX) &&
           verifier.VerifyVector(step_index()) &&
           VerifyOffset(verifier, VT_FORMAT_TYPE) &&
           verifier.VerifyString(format_type()) &&
           VerifyOffset(verifier, VT_SOURCE_SEQUENCE_ID) &&
           verifier.VerifyString(source_sequence_id()) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_GOAL) &&
           verifier.VerifyTable(goal()) &&
           VerifyOffset(verifier, VT_RAW) &&
           verifier.VerifyString(raw()) &&
           VerifyOffset(verifier, VT_KNOWNS) &&
           verifier.VerifyVector(knowns()) &&
           verifier.VerifyVectorOfStrings(knowns()) &&
           VerifyOffset(verifier, VT_UNKNOWNS) &&
           verifier.VerifyVector(unknowns()) &&
           verifier.VerifyVectorOfStrings(unknowns()) &&
           verifier.EndTable();
  }
};

struct ConceptBlockBuilder {
  typedef ConceptBlock Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(ConceptBlock::VT_ID, id);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(ConceptBlock::VT_NAME, name);
  }
  void add_prompt(::flatbuffers::Offset<::flatbuffers::String> prompt) {
    fbb_.AddOffset(ConceptBlock::VT_PROMPT, prompt);
  }
  void add_intermediates(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> intermediates) {
    fbb_.AddOffset(ConceptBlock::VT_INTERMEDIATES, intermediates);
  }
  void add_answer(::flatbuffers::Offset<::flatbuffers::String> answer) {
    fbb_.AddOffset(ConceptBlock::VT_ANSWER, answer);
  }
  void add_explanation(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> explanation) {
    fbb_.AddOffset(ConceptBlock::VT_EXPLANATION, explanation);
  }
  void add_execution(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMConcept::ConceptExecutionStep>>> execution) {
    fbb_.AddOffset(ConceptBlock::VT_EXECUTION, execution);
  }
  void add_intermediate_count(int32_t intermediate_count) {
    fbb_.AddElement<int32_t>(ConceptBlock::VT_INTERMEDIATE_COUNT, intermediate_count, 0);
  }
  void add_step_index(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> step_index) {
    fbb_.AddOffset(ConceptBlock::VT_STEP_INDEX, step_index);
  }
  void add_format_type(::flatbuffers::Offset<::flatbuffers::String> format_type) {
    fbb_.AddOffset(ConceptBlock::VT_FORMAT_TYPE, format_type);
  }
  void add_source_sequence_id(::flatbuffers::Offset<::flatbuffers::String> source_sequence_id) {
    fbb_.AddOffset(ConceptBlock::VT_SOURCE_SEQUENCE_ID, source_sequence_id);
  }
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(ConceptBlock::VT_TIMESTAMP, timestamp, 0);
  }
  void add_goal(::flatbuffers::Offset<GRIMConcept::Goal> goal) {
    fbb_.AddOffset(ConceptBlock::VT_GOAL, goal);
  }
  void add_raw(::flatbuffers::Offset<::flatbuffers::String> raw) {
    fbb_.AddOffset(ConceptBlock::VT_RAW, raw);
  }
  void add_knowns(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> knowns) {
    fbb_.AddOffset(ConceptBlock::VT_KNOWNS, knowns);
  }
  void add_unknowns(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> unknowns) {
    fbb_.AddOffset(ConceptBlock::VT_UNKNOWNS, unknowns);
  }
  explicit ConceptBlockBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ConceptBlock> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ConceptBlock>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ConceptBlock> CreateConceptBlock(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> prompt = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> intermediates = 0,
    ::flatbuffers::Offset<::flatbuffers::String> answer = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> explanation = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMConcept::ConceptExecutionStep>>> execution = 0,
    int32_t intermediate_count = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> step_index = 0,
    ::flatbuffers::Offset<::flatbuffers::String> format_type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_sequence_id = 0,
    int64_t timestamp = 0,
    ::flatbuffers::Offset<GRIMConcept::Goal> goal = 0,
    ::flatbuffers::Offset<::flatbuffers::String> raw = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> knowns = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> unknowns = 0) {
  ConceptBlockBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_unknowns(unknowns);
  builder_.add_knowns(knowns);
  builder_.add_raw(raw);
  builder_.add_goal(goal);
  builder_.add_source_sequence_id(source_sequence_id);
  builder_.add_format_type(format_type);
  builder_.add_step_index(step_index);
  builder_.add_intermediate_count(intermediate_count);
  builder_.add_execution(execution);
  builder_.add_explanation(explanation);
  builder_.add_answer(answer);
  builder_.add_intermediates(intermediates);
  builder_.add_prompt(prompt);
  builder_.add_name(name);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ConceptBlock> CreateConceptBlockDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *name = nullptr,
    const char *prompt = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *intermediates = nullptr,
    const char *answer = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *explanation = nullptr,
    const std::vector<::flatbuffers::Offset<GRIMConcept::ConceptExecutionStep>> *execution = nullptr,
    int32_t intermediate_count = 0,
    const std::vector<int32_t> *step_index = nullptr,
    const char *format_type = nullptr,
    const char *source_sequence_id = nullptr,
    int64_t timestamp = 0,
    ::flatbuffers::Offset<GRIMConcept::Goal> goal = 0,
    const char *raw = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *knowns = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *unknowns = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto prompt__ = prompt ? _fbb.CreateString(prompt) : 0;
  auto intermediates__ = intermediates ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*intermediates) : 0;
  auto answer__ = answer ? _fbb.CreateString(answer) : 0;
  auto explanation__ = explanation ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*explanation) : 0;
  auto execution__ = execution ? _fbb.CreateVector<::flatbuffers::Offset<GRIMConcept::ConceptExecutionStep>>(*execution) : 0;
  auto step_index__ = step_index ? _fbb.CreateVector<int32_t>(*step_index) : 0;
  auto format_type__ = format_type ? _fbb.CreateString(format_type) : 0;
  auto source_sequence_id__ = source_sequence_id ? _fbb.CreateString(source_sequence_id) : 0;
  auto raw__ = raw ? _fbb.CreateString(raw) : 0;
  auto knowns__ = knowns ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*knowns) : 0;
  auto unknowns__ = unknowns ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*unknowns) : 0;
  return GRIMConcept::CreateConceptBlock(
      _fbb,
      id__,
      name__,
      prompt__,
      intermediates__,
      answer__,
      explanation__,
      execution__,
      intermediate_count,
      step_index__,
      format_type__,
      source_sequence_id__,
      timestamp,
      goal,
      raw__,
      knowns__,
      unknowns__);
}

struct ConceptBlockDataset FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConceptBlockDatasetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCHEMA_VERSION = 4,
    VT_BLOCKS = 6
  };
  uint32_t schema_version() const {
    return GetField<uint32_t>(VT_SCHEMA_VERSION, 1);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMConcept::ConceptBlock>> *blocks() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMConcept::ConceptBlock>> *>(VT_BLOCKS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SCHEMA_VERSION, 4) &&
           VerifyOffset(verifier, VT_BLOCKS) &&
           verifier.VerifyVector(blocks()) &&
           verifier.VerifyVectorOfTables(blocks()) &&
           verifier.EndTable();
  }
};

struct ConceptBlockDatasetBuilder {
  typedef ConceptBlockDataset Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_schema_version(uint32_t schema_version) {
    fbb_.AddElement<uint32_t>(ConceptBlockDataset::VT_SCHEMA_VERSION, schema_version, 1);
  }
  void add_blocks(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMConcept::ConceptBlock>>> blocks) {
    fbb_.AddOffset(ConceptBlockDataset::VT_BLOCKS, blocks);
  }
  explicit ConceptBlockDatasetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ConceptBlockDataset> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ConceptBlockDataset>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ConceptBlockDataset> CreateConceptBlockDataset(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t schema_version = 1,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMConcept::ConceptBlock>>> blocks = 0) {
  ConceptBlockDatasetBuilder builder_(_fbb);
  builder_.add_blocks(blocks);
  builder_.add_schema_version(schema_version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ConceptBlockDataset> CreateConceptBlockDatasetDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t schema_version = 1,
    const std::vector<::flatbuffers::Offset<GRIMConcept::ConceptBlock>> *blocks = nullptr) {
  auto blocks__ = blocks ? _fbb.CreateVector<::flatbuffers::Offset<GRIMConcept::ConceptBlock>>(*blocks) : 0;
  return GRIMConcept::CreateConceptBlockDataset(
      _fbb,
      schema_version,
      blocks__);
}

inline const GRIMConcept::ConceptBlockDataset *GetConceptBlockDataset(const void *buf) {
  return ::flatbuffers::GetRoot<GRIMConcept::ConceptBlockDataset>(buf);
}

inline const GRIMConcept::ConceptBlockDataset *GetSizePrefixedConceptBlockDataset(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GRIMConcept::ConceptBlockDataset>(buf);
}

inline const char *ConceptBlockDatasetIdentifier() {
  return "GRCB";
}

inline bool ConceptBlockDatasetBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, ConceptBlockDatasetIdentifier());
}

inline bool SizePrefixedConceptBlockDatasetBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, ConceptBlockDatasetIdentifier(), true);
}

inline bool VerifyConceptBlockDatasetBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GRIMConcept::ConceptBlockDataset>(ConceptBlockDatasetIdentifier());
}

inline bool VerifySizePrefixedConceptBlockDatasetBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GRIMConcept::ConceptBlockDataset>(ConceptBlockDatasetIdentifier());
}

inline const char *ConceptBlockDatasetExtension() {
  return "fb";
}

inline void FinishConceptBlockDatasetBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIMConcept::ConceptBlockDataset> root) {
  fbb.Finish(root, ConceptBlockDatasetIdentifier());
}

inline void FinishSizePrefixedConceptBlockDatasetBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIMConcept::ConceptBlockDataset> root) {
  fbb.FinishSizePrefixed(root, ConceptBlockDatasetIdentifier());
}

}  // namespace GRIMConcept

#endif  // FLATBUFFERS_GENERATED_CONCEPTBLOCK_GRIMCONCEPT_H_
