#include "popup_3d_shaders.hpp"
#include <bgfx/bgfx.h>
#include <bgfx/embedded_shader.h>
#include <stdexcept>

// ===========================================================
// Popup 3D Shaders — custom popup model shaders compiled via
// shaderc from resources/shaders/vs_popup_model.sc and
// fs_popup_model.sc.  Provides: MVP + world-space normals +
// Blinn-Phong directional lighting + texture sampling.
// ===========================================================

// Per-profile compiled shader bytecodes (generated by cmake/Shaders.cmake)
#include "vs_popup_model.bin.h"
#include "fs_popup_model.bin.h"

static const bgfx::EmbeddedShader s_popupEmbeddedShaders[] =
{
    BGFX_EMBEDDED_SHADER(vs_popup_model),
    BGFX_EMBEDDED_SHADER(fs_popup_model),
    BGFX_EMBEDDED_SHADER_END()
};

struct PopupShaderState
{
    bgfx::ProgramHandle program = BGFX_INVALID_HANDLE;
    bgfx::UniformHandle u_lightDir    = BGFX_INVALID_HANDLE;
    bgfx::UniformHandle u_lightParams = BGFX_INVALID_HANDLE;
    bgfx::UniformHandle u_alpha       = BGFX_INVALID_HANDLE;
    bgfx::UniformHandle u_emissive    = BGFX_INVALID_HANDLE;
    bgfx::UniformHandle s_albedo      = BGFX_INVALID_HANDLE;
    bgfx::UniformHandle s_normal      = BGFX_INVALID_HANDLE;
    bgfx::UniformHandle s_packed      = BGFX_INVALID_HANDLE;
};

PopupShaderState* popupShadersCreate()
{
    bgfx::RendererType::Enum type = bgfx::getRendererType();

    bgfx::ShaderHandle vsh = bgfx::createEmbeddedShader(
        s_popupEmbeddedShaders, type, "vs_popup_model");
    if (!bgfx::isValid(vsh))
        throw std::runtime_error("popupShadersCreate: failed to create vertex shader (vs_popup_model)");

    bgfx::ShaderHandle fsh = bgfx::createEmbeddedShader(
        s_popupEmbeddedShaders, type, "fs_popup_model");
    if (!bgfx::isValid(fsh))
    {
        bgfx::destroy(vsh);
        throw std::runtime_error("popupShadersCreate: failed to create fragment shader (fs_popup_model)");
    }

    auto* state = new PopupShaderState();
    state->program = bgfx::createProgram(vsh, fsh, true);
    if (!bgfx::isValid(state->program))
    {
        delete state;
        throw std::runtime_error("popupShadersCreate: bgfx::createProgram failed");
    }

    // Create uniform handles matching the fragment shader
    state->u_lightDir    = bgfx::createUniform("u_lightDir",    bgfx::UniformType::Vec4);
    state->u_lightParams = bgfx::createUniform("u_lightParams", bgfx::UniformType::Vec4);
    state->u_alpha       = bgfx::createUniform("u_alpha",       bgfx::UniformType::Vec4);
    state->u_emissive    = bgfx::createUniform("u_emissive",    bgfx::UniformType::Vec4);
    state->s_albedo      = bgfx::createUniform("s_albedo",      bgfx::UniformType::Sampler);
    state->s_normal      = bgfx::createUniform("s_normal",      bgfx::UniformType::Sampler);
    state->s_packed      = bgfx::createUniform("s_packed",      bgfx::UniformType::Sampler);

    return state;
}

void popupShadersDestroy(PopupShaderState* shaders)
{
    if (!shaders) return;
    if (bgfx::isValid(shaders->program))     bgfx::destroy(shaders->program);
    if (bgfx::isValid(shaders->u_lightDir))    bgfx::destroy(shaders->u_lightDir);
    if (bgfx::isValid(shaders->u_lightParams)) bgfx::destroy(shaders->u_lightParams);
    if (bgfx::isValid(shaders->u_alpha))       bgfx::destroy(shaders->u_alpha);
    if (bgfx::isValid(shaders->u_emissive))    bgfx::destroy(shaders->u_emissive);
    if (bgfx::isValid(shaders->s_albedo))      bgfx::destroy(shaders->s_albedo);
    if (bgfx::isValid(shaders->s_normal))      bgfx::destroy(shaders->s_normal);
    if (bgfx::isValid(shaders->s_packed))      bgfx::destroy(shaders->s_packed);
    delete shaders;
}

bgfx::ProgramHandle popupShadersGetProgram(const PopupShaderState* shaders)
{
    if (!shaders)
        throw std::runtime_error("popupShadersGetProgram: shaders is NULL");
    return shaders->program;
}

bgfx::UniformHandle popupShadersGetUniform(const PopupShaderState* shaders, PopupShaderUniform u)
{
    if (!shaders)
        throw std::runtime_error("popupShadersGetUniform: shaders is NULL");
    switch (u)
    {
        case PopupShaderUniform::LightDir:    return shaders->u_lightDir;
        case PopupShaderUniform::LightParams: return shaders->u_lightParams;
        case PopupShaderUniform::Alpha:       return shaders->u_alpha;
        case PopupShaderUniform::Emissive:    return shaders->u_emissive;
        case PopupShaderUniform::AlbedoSampler: return shaders->s_albedo;
        case PopupShaderUniform::NormalSampler:  return shaders->s_normal;
        case PopupShaderUniform::PackedSampler:  return shaders->s_packed;
    }
    throw std::runtime_error("popupShadersGetUniform: unknown uniform");
}
