// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DATACOLLECTIONPROTOCOL_GRIM_DATACOLLECTION_H_
#define FLATBUFFERS_GENERATED_DATACOLLECTIONPROTOCOL_GRIM_DATACOLLECTION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25,
             "Non-compatible flatbuffers version included");

namespace GRIM {
namespace DataCollection {

struct DataCollectionRequest;
struct DataCollectionRequestBuilder;

struct DataCollectionResponse;
struct DataCollectionResponseBuilder;

struct StatusResponse;
struct StatusResponseBuilder;

struct VerificationLogEntry;
struct VerificationLogEntryBuilder;

struct VerificationStats;
struct VerificationStatsBuilder;

struct CollectionLogEntry;
struct CollectionLogEntryBuilder;

struct CollectionStats;
struct CollectionStatsBuilder;

struct MergeStats;
struct MergeStatsBuilder;

struct PipelineReport;
struct PipelineReportBuilder;

struct HealthResponse;
struct HealthResponseBuilder;

enum class CollectionMode : int8_t {
  Full = 0,
  CollectOnly = 1,
  VerifyOnly = 2,
  MergeOnly = 3,
  MIN = Full,
  MAX = MergeOnly
};

inline const CollectionMode (&EnumValuesCollectionMode())[4] {
  static const CollectionMode values[] = {
    CollectionMode::Full,
    CollectionMode::CollectOnly,
    CollectionMode::VerifyOnly,
    CollectionMode::MergeOnly
  };
  return values;
}

inline const char * const *EnumNamesCollectionMode() {
  static const char * const names[5] = {
    "Full",
    "CollectOnly",
    "VerifyOnly",
    "MergeOnly",
    nullptr
  };
  return names;
}

inline const char *EnumNameCollectionMode(CollectionMode e) {
  if (::flatbuffers::IsOutRange(e, CollectionMode::Full, CollectionMode::MergeOnly)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCollectionMode()[index];
}

enum class CollectionStatus : int8_t {
  Idle = 0,
  Collecting = 1,
  Verifying = 2,
  Merging = 3,
  Complete = 4,
  Failed = 5,
  MIN = Idle,
  MAX = Failed
};

inline const CollectionStatus (&EnumValuesCollectionStatus())[6] {
  static const CollectionStatus values[] = {
    CollectionStatus::Idle,
    CollectionStatus::Collecting,
    CollectionStatus::Verifying,
    CollectionStatus::Merging,
    CollectionStatus::Complete,
    CollectionStatus::Failed
  };
  return values;
}

inline const char * const *EnumNamesCollectionStatus() {
  static const char * const names[7] = {
    "Idle",
    "Collecting",
    "Verifying",
    "Merging",
    "Complete",
    "Failed",
    nullptr
  };
  return names;
}

inline const char *EnumNameCollectionStatus(CollectionStatus e) {
  if (::flatbuffers::IsOutRange(e, CollectionStatus::Idle, CollectionStatus::Failed)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCollectionStatus()[index];
}

struct DataCollectionRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DataCollectionRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MODE = 4
  };
  const ::flatbuffers::String *mode() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MODE) &&
           verifier.VerifyString(mode()) &&
           verifier.EndTable();
  }
};

struct DataCollectionRequestBuilder {
  typedef DataCollectionRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mode(::flatbuffers::Offset<::flatbuffers::String> mode) {
    fbb_.AddOffset(DataCollectionRequest::VT_MODE, mode);
  }
  explicit DataCollectionRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DataCollectionRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DataCollectionRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DataCollectionRequest> CreateDataCollectionRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> mode = 0) {
  DataCollectionRequestBuilder builder_(_fbb);
  builder_.add_mode(mode);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DataCollectionRequest> CreateDataCollectionRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *mode = nullptr) {
  auto mode__ = mode ? _fbb.CreateString(mode) : 0;
  return GRIM::DataCollection::CreateDataCollectionRequest(
      _fbb,
      mode__);
}

struct DataCollectionResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DataCollectionResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUCCESS = 4,
    VT_MESSAGE = 6,
    VT_ERROR = 8
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  const ::flatbuffers::String *error() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_ERROR) &&
           verifier.VerifyString(error()) &&
           verifier.EndTable();
  }
};

struct DataCollectionResponseBuilder {
  typedef DataCollectionResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(DataCollectionResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(DataCollectionResponse::VT_MESSAGE, message);
  }
  void add_error(::flatbuffers::Offset<::flatbuffers::String> error) {
    fbb_.AddOffset(DataCollectionResponse::VT_ERROR, error);
  }
  explicit DataCollectionResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DataCollectionResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DataCollectionResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DataCollectionResponse> CreateDataCollectionResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error = 0) {
  DataCollectionResponseBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_message(message);
  builder_.add_success(success);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DataCollectionResponse> CreateDataCollectionResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    const char *message = nullptr,
    const char *error = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto error__ = error ? _fbb.CreateString(error) : 0;
  return GRIM::DataCollection::CreateDataCollectionResponse(
      _fbb,
      success,
      message__,
      error__);
}

struct StatusResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StatusResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATUS = 4,
    VT_PROGRESS = 6,
    VT_CURRENT_PHASE = 8,
    VT_ERROR_MESSAGE = 10,
    VT_IS_COLLECTING = 12
  };
  GRIM::DataCollection::CollectionStatus status() const {
    return static_cast<GRIM::DataCollection::CollectionStatus>(GetField<int8_t>(VT_STATUS, 0));
  }
  float progress() const {
    return GetField<float>(VT_PROGRESS, 0.0f);
  }
  const ::flatbuffers::String *current_phase() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CURRENT_PHASE);
  }
  const ::flatbuffers::String *error_message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR_MESSAGE);
  }
  bool is_collecting() const {
    return GetField<uint8_t>(VT_IS_COLLECTING, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_STATUS, 1) &&
           VerifyField<float>(verifier, VT_PROGRESS, 4) &&
           VerifyOffset(verifier, VT_CURRENT_PHASE) &&
           verifier.VerifyString(current_phase()) &&
           VerifyOffset(verifier, VT_ERROR_MESSAGE) &&
           verifier.VerifyString(error_message()) &&
           VerifyField<uint8_t>(verifier, VT_IS_COLLECTING, 1) &&
           verifier.EndTable();
  }
};

struct StatusResponseBuilder {
  typedef StatusResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_status(GRIM::DataCollection::CollectionStatus status) {
    fbb_.AddElement<int8_t>(StatusResponse::VT_STATUS, static_cast<int8_t>(status), 0);
  }
  void add_progress(float progress) {
    fbb_.AddElement<float>(StatusResponse::VT_PROGRESS, progress, 0.0f);
  }
  void add_current_phase(::flatbuffers::Offset<::flatbuffers::String> current_phase) {
    fbb_.AddOffset(StatusResponse::VT_CURRENT_PHASE, current_phase);
  }
  void add_error_message(::flatbuffers::Offset<::flatbuffers::String> error_message) {
    fbb_.AddOffset(StatusResponse::VT_ERROR_MESSAGE, error_message);
  }
  void add_is_collecting(bool is_collecting) {
    fbb_.AddElement<uint8_t>(StatusResponse::VT_IS_COLLECTING, static_cast<uint8_t>(is_collecting), 0);
  }
  explicit StatusResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StatusResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StatusResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StatusResponse> CreateStatusResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GRIM::DataCollection::CollectionStatus status = GRIM::DataCollection::CollectionStatus::Idle,
    float progress = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::String> current_phase = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error_message = 0,
    bool is_collecting = false) {
  StatusResponseBuilder builder_(_fbb);
  builder_.add_error_message(error_message);
  builder_.add_current_phase(current_phase);
  builder_.add_progress(progress);
  builder_.add_is_collecting(is_collecting);
  builder_.add_status(status);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StatusResponse> CreateStatusResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GRIM::DataCollection::CollectionStatus status = GRIM::DataCollection::CollectionStatus::Idle,
    float progress = 0.0f,
    const char *current_phase = nullptr,
    const char *error_message = nullptr,
    bool is_collecting = false) {
  auto current_phase__ = current_phase ? _fbb.CreateString(current_phase) : 0;
  auto error_message__ = error_message ? _fbb.CreateString(error_message) : 0;
  return GRIM::DataCollection::CreateStatusResponse(
      _fbb,
      status,
      progress,
      current_phase__,
      error_message__,
      is_collecting);
}

struct VerificationLogEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VerificationLogEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_FILE_PATH = 6,
    VT_ENTRY_ID = 8,
    VT_PASSED = 10,
    VT_ERROR_MESSAGE = 12,
    VT_VALIDATION_ISSUES = 14
  };
  const ::flatbuffers::String *timestamp() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TIMESTAMP);
  }
  const ::flatbuffers::String *file_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILE_PATH);
  }
  uint64_t entry_id() const {
    return GetField<uint64_t>(VT_ENTRY_ID, 0);
  }
  bool passed() const {
    return GetField<uint8_t>(VT_PASSED, 0) != 0;
  }
  const ::flatbuffers::String *error_message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR_MESSAGE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *validation_issues() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_VALIDATION_ISSUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TIMESTAMP) &&
           verifier.VerifyString(timestamp()) &&
           VerifyOffset(verifier, VT_FILE_PATH) &&
           verifier.VerifyString(file_path()) &&
           VerifyField<uint64_t>(verifier, VT_ENTRY_ID, 8) &&
           VerifyField<uint8_t>(verifier, VT_PASSED, 1) &&
           VerifyOffset(verifier, VT_ERROR_MESSAGE) &&
           verifier.VerifyString(error_message()) &&
           VerifyOffset(verifier, VT_VALIDATION_ISSUES) &&
           verifier.VerifyVector(validation_issues()) &&
           verifier.VerifyVectorOfStrings(validation_issues()) &&
           verifier.EndTable();
  }
};

struct VerificationLogEntryBuilder {
  typedef VerificationLogEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(::flatbuffers::Offset<::flatbuffers::String> timestamp) {
    fbb_.AddOffset(VerificationLogEntry::VT_TIMESTAMP, timestamp);
  }
  void add_file_path(::flatbuffers::Offset<::flatbuffers::String> file_path) {
    fbb_.AddOffset(VerificationLogEntry::VT_FILE_PATH, file_path);
  }
  void add_entry_id(uint64_t entry_id) {
    fbb_.AddElement<uint64_t>(VerificationLogEntry::VT_ENTRY_ID, entry_id, 0);
  }
  void add_passed(bool passed) {
    fbb_.AddElement<uint8_t>(VerificationLogEntry::VT_PASSED, static_cast<uint8_t>(passed), 0);
  }
  void add_error_message(::flatbuffers::Offset<::flatbuffers::String> error_message) {
    fbb_.AddOffset(VerificationLogEntry::VT_ERROR_MESSAGE, error_message);
  }
  void add_validation_issues(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> validation_issues) {
    fbb_.AddOffset(VerificationLogEntry::VT_VALIDATION_ISSUES, validation_issues);
  }
  explicit VerificationLogEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VerificationLogEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VerificationLogEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VerificationLogEntry> CreateVerificationLogEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> timestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::String> file_path = 0,
    uint64_t entry_id = 0,
    bool passed = false,
    ::flatbuffers::Offset<::flatbuffers::String> error_message = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> validation_issues = 0) {
  VerificationLogEntryBuilder builder_(_fbb);
  builder_.add_entry_id(entry_id);
  builder_.add_validation_issues(validation_issues);
  builder_.add_error_message(error_message);
  builder_.add_file_path(file_path);
  builder_.add_timestamp(timestamp);
  builder_.add_passed(passed);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VerificationLogEntry> CreateVerificationLogEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *timestamp = nullptr,
    const char *file_path = nullptr,
    uint64_t entry_id = 0,
    bool passed = false,
    const char *error_message = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *validation_issues = nullptr) {
  auto timestamp__ = timestamp ? _fbb.CreateString(timestamp) : 0;
  auto file_path__ = file_path ? _fbb.CreateString(file_path) : 0;
  auto error_message__ = error_message ? _fbb.CreateString(error_message) : 0;
  auto validation_issues__ = validation_issues ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*validation_issues) : 0;
  return GRIM::DataCollection::CreateVerificationLogEntry(
      _fbb,
      timestamp__,
      file_path__,
      entry_id,
      passed,
      error_message__,
      validation_issues__);
}

struct VerificationStats FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VerificationStatsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOTAL_ENTRIES = 4,
    VT_PASSED = 6,
    VT_FAILED = 8,
    VT_WARNINGS = 10,
    VT_START_TIME = 12,
    VT_END_TIME = 14,
    VT_DURATION_SECONDS = 16
  };
  uint64_t total_entries() const {
    return GetField<uint64_t>(VT_TOTAL_ENTRIES, 0);
  }
  uint64_t passed() const {
    return GetField<uint64_t>(VT_PASSED, 0);
  }
  uint64_t failed() const {
    return GetField<uint64_t>(VT_FAILED, 0);
  }
  uint64_t warnings() const {
    return GetField<uint64_t>(VT_WARNINGS, 0);
  }
  const ::flatbuffers::String *start_time() const {
    return GetPointer<const ::flatbuffers::String *>(VT_START_TIME);
  }
  const ::flatbuffers::String *end_time() const {
    return GetPointer<const ::flatbuffers::String *>(VT_END_TIME);
  }
  float duration_seconds() const {
    return GetField<float>(VT_DURATION_SECONDS, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TOTAL_ENTRIES, 8) &&
           VerifyField<uint64_t>(verifier, VT_PASSED, 8) &&
           VerifyField<uint64_t>(verifier, VT_FAILED, 8) &&
           VerifyField<uint64_t>(verifier, VT_WARNINGS, 8) &&
           VerifyOffset(verifier, VT_START_TIME) &&
           verifier.VerifyString(start_time()) &&
           VerifyOffset(verifier, VT_END_TIME) &&
           verifier.VerifyString(end_time()) &&
           VerifyField<float>(verifier, VT_DURATION_SECONDS, 4) &&
           verifier.EndTable();
  }
};

struct VerificationStatsBuilder {
  typedef VerificationStats Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_total_entries(uint64_t total_entries) {
    fbb_.AddElement<uint64_t>(VerificationStats::VT_TOTAL_ENTRIES, total_entries, 0);
  }
  void add_passed(uint64_t passed) {
    fbb_.AddElement<uint64_t>(VerificationStats::VT_PASSED, passed, 0);
  }
  void add_failed(uint64_t failed) {
    fbb_.AddElement<uint64_t>(VerificationStats::VT_FAILED, failed, 0);
  }
  void add_warnings(uint64_t warnings) {
    fbb_.AddElement<uint64_t>(VerificationStats::VT_WARNINGS, warnings, 0);
  }
  void add_start_time(::flatbuffers::Offset<::flatbuffers::String> start_time) {
    fbb_.AddOffset(VerificationStats::VT_START_TIME, start_time);
  }
  void add_end_time(::flatbuffers::Offset<::flatbuffers::String> end_time) {
    fbb_.AddOffset(VerificationStats::VT_END_TIME, end_time);
  }
  void add_duration_seconds(float duration_seconds) {
    fbb_.AddElement<float>(VerificationStats::VT_DURATION_SECONDS, duration_seconds, 0.0f);
  }
  explicit VerificationStatsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VerificationStats> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VerificationStats>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VerificationStats> CreateVerificationStats(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t total_entries = 0,
    uint64_t passed = 0,
    uint64_t failed = 0,
    uint64_t warnings = 0,
    ::flatbuffers::Offset<::flatbuffers::String> start_time = 0,
    ::flatbuffers::Offset<::flatbuffers::String> end_time = 0,
    float duration_seconds = 0.0f) {
  VerificationStatsBuilder builder_(_fbb);
  builder_.add_warnings(warnings);
  builder_.add_failed(failed);
  builder_.add_passed(passed);
  builder_.add_total_entries(total_entries);
  builder_.add_duration_seconds(duration_seconds);
  builder_.add_end_time(end_time);
  builder_.add_start_time(start_time);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VerificationStats> CreateVerificationStatsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t total_entries = 0,
    uint64_t passed = 0,
    uint64_t failed = 0,
    uint64_t warnings = 0,
    const char *start_time = nullptr,
    const char *end_time = nullptr,
    float duration_seconds = 0.0f) {
  auto start_time__ = start_time ? _fbb.CreateString(start_time) : 0;
  auto end_time__ = end_time ? _fbb.CreateString(end_time) : 0;
  return GRIM::DataCollection::CreateVerificationStats(
      _fbb,
      total_entries,
      passed,
      failed,
      warnings,
      start_time__,
      end_time__,
      duration_seconds);
}

struct CollectionLogEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CollectionLogEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_SOURCE = 6,
    VT_ENTRIES_COLLECTED = 8,
    VT_BYTES_COLLECTED = 10,
    VT_SUCCESS = 12,
    VT_ERROR_MESSAGE = 14
  };
  const ::flatbuffers::String *timestamp() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TIMESTAMP);
  }
  const ::flatbuffers::String *source() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE);
  }
  uint64_t entries_collected() const {
    return GetField<uint64_t>(VT_ENTRIES_COLLECTED, 0);
  }
  uint64_t bytes_collected() const {
    return GetField<uint64_t>(VT_BYTES_COLLECTED, 0);
  }
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  const ::flatbuffers::String *error_message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR_MESSAGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TIMESTAMP) &&
           verifier.VerifyString(timestamp()) &&
           VerifyOffset(verifier, VT_SOURCE) &&
           verifier.VerifyString(source()) &&
           VerifyField<uint64_t>(verifier, VT_ENTRIES_COLLECTED, 8) &&
           VerifyField<uint64_t>(verifier, VT_BYTES_COLLECTED, 8) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           VerifyOffset(verifier, VT_ERROR_MESSAGE) &&
           verifier.VerifyString(error_message()) &&
           verifier.EndTable();
  }
};

struct CollectionLogEntryBuilder {
  typedef CollectionLogEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(::flatbuffers::Offset<::flatbuffers::String> timestamp) {
    fbb_.AddOffset(CollectionLogEntry::VT_TIMESTAMP, timestamp);
  }
  void add_source(::flatbuffers::Offset<::flatbuffers::String> source) {
    fbb_.AddOffset(CollectionLogEntry::VT_SOURCE, source);
  }
  void add_entries_collected(uint64_t entries_collected) {
    fbb_.AddElement<uint64_t>(CollectionLogEntry::VT_ENTRIES_COLLECTED, entries_collected, 0);
  }
  void add_bytes_collected(uint64_t bytes_collected) {
    fbb_.AddElement<uint64_t>(CollectionLogEntry::VT_BYTES_COLLECTED, bytes_collected, 0);
  }
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(CollectionLogEntry::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  void add_error_message(::flatbuffers::Offset<::flatbuffers::String> error_message) {
    fbb_.AddOffset(CollectionLogEntry::VT_ERROR_MESSAGE, error_message);
  }
  explicit CollectionLogEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CollectionLogEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CollectionLogEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CollectionLogEntry> CreateCollectionLogEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> timestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source = 0,
    uint64_t entries_collected = 0,
    uint64_t bytes_collected = 0,
    bool success = false,
    ::flatbuffers::Offset<::flatbuffers::String> error_message = 0) {
  CollectionLogEntryBuilder builder_(_fbb);
  builder_.add_bytes_collected(bytes_collected);
  builder_.add_entries_collected(entries_collected);
  builder_.add_error_message(error_message);
  builder_.add_source(source);
  builder_.add_timestamp(timestamp);
  builder_.add_success(success);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CollectionLogEntry> CreateCollectionLogEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *timestamp = nullptr,
    const char *source = nullptr,
    uint64_t entries_collected = 0,
    uint64_t bytes_collected = 0,
    bool success = false,
    const char *error_message = nullptr) {
  auto timestamp__ = timestamp ? _fbb.CreateString(timestamp) : 0;
  auto source__ = source ? _fbb.CreateString(source) : 0;
  auto error_message__ = error_message ? _fbb.CreateString(error_message) : 0;
  return GRIM::DataCollection::CreateCollectionLogEntry(
      _fbb,
      timestamp__,
      source__,
      entries_collected,
      bytes_collected,
      success,
      error_message__);
}

struct CollectionStats FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CollectionStatsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOTAL_SOURCES = 4,
    VT_SOURCES_PROCESSED = 6,
    VT_TOTAL_ENTRIES = 8,
    VT_TOTAL_BYTES = 10,
    VT_FAILED_SOURCES = 12,
    VT_START_TIME = 14,
    VT_END_TIME = 16,
    VT_DURATION_SECONDS = 18
  };
  uint64_t total_sources() const {
    return GetField<uint64_t>(VT_TOTAL_SOURCES, 0);
  }
  uint64_t sources_processed() const {
    return GetField<uint64_t>(VT_SOURCES_PROCESSED, 0);
  }
  uint64_t total_entries() const {
    return GetField<uint64_t>(VT_TOTAL_ENTRIES, 0);
  }
  uint64_t total_bytes() const {
    return GetField<uint64_t>(VT_TOTAL_BYTES, 0);
  }
  uint64_t failed_sources() const {
    return GetField<uint64_t>(VT_FAILED_SOURCES, 0);
  }
  const ::flatbuffers::String *start_time() const {
    return GetPointer<const ::flatbuffers::String *>(VT_START_TIME);
  }
  const ::flatbuffers::String *end_time() const {
    return GetPointer<const ::flatbuffers::String *>(VT_END_TIME);
  }
  float duration_seconds() const {
    return GetField<float>(VT_DURATION_SECONDS, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TOTAL_SOURCES, 8) &&
           VerifyField<uint64_t>(verifier, VT_SOURCES_PROCESSED, 8) &&
           VerifyField<uint64_t>(verifier, VT_TOTAL_ENTRIES, 8) &&
           VerifyField<uint64_t>(verifier, VT_TOTAL_BYTES, 8) &&
           VerifyField<uint64_t>(verifier, VT_FAILED_SOURCES, 8) &&
           VerifyOffset(verifier, VT_START_TIME) &&
           verifier.VerifyString(start_time()) &&
           VerifyOffset(verifier, VT_END_TIME) &&
           verifier.VerifyString(end_time()) &&
           VerifyField<float>(verifier, VT_DURATION_SECONDS, 4) &&
           verifier.EndTable();
  }
};

struct CollectionStatsBuilder {
  typedef CollectionStats Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_total_sources(uint64_t total_sources) {
    fbb_.AddElement<uint64_t>(CollectionStats::VT_TOTAL_SOURCES, total_sources, 0);
  }
  void add_sources_processed(uint64_t sources_processed) {
    fbb_.AddElement<uint64_t>(CollectionStats::VT_SOURCES_PROCESSED, sources_processed, 0);
  }
  void add_total_entries(uint64_t total_entries) {
    fbb_.AddElement<uint64_t>(CollectionStats::VT_TOTAL_ENTRIES, total_entries, 0);
  }
  void add_total_bytes(uint64_t total_bytes) {
    fbb_.AddElement<uint64_t>(CollectionStats::VT_TOTAL_BYTES, total_bytes, 0);
  }
  void add_failed_sources(uint64_t failed_sources) {
    fbb_.AddElement<uint64_t>(CollectionStats::VT_FAILED_SOURCES, failed_sources, 0);
  }
  void add_start_time(::flatbuffers::Offset<::flatbuffers::String> start_time) {
    fbb_.AddOffset(CollectionStats::VT_START_TIME, start_time);
  }
  void add_end_time(::flatbuffers::Offset<::flatbuffers::String> end_time) {
    fbb_.AddOffset(CollectionStats::VT_END_TIME, end_time);
  }
  void add_duration_seconds(float duration_seconds) {
    fbb_.AddElement<float>(CollectionStats::VT_DURATION_SECONDS, duration_seconds, 0.0f);
  }
  explicit CollectionStatsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CollectionStats> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CollectionStats>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CollectionStats> CreateCollectionStats(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t total_sources = 0,
    uint64_t sources_processed = 0,
    uint64_t total_entries = 0,
    uint64_t total_bytes = 0,
    uint64_t failed_sources = 0,
    ::flatbuffers::Offset<::flatbuffers::String> start_time = 0,
    ::flatbuffers::Offset<::flatbuffers::String> end_time = 0,
    float duration_seconds = 0.0f) {
  CollectionStatsBuilder builder_(_fbb);
  builder_.add_failed_sources(failed_sources);
  builder_.add_total_bytes(total_bytes);
  builder_.add_total_entries(total_entries);
  builder_.add_sources_processed(sources_processed);
  builder_.add_total_sources(total_sources);
  builder_.add_duration_seconds(duration_seconds);
  builder_.add_end_time(end_time);
  builder_.add_start_time(start_time);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CollectionStats> CreateCollectionStatsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t total_sources = 0,
    uint64_t sources_processed = 0,
    uint64_t total_entries = 0,
    uint64_t total_bytes = 0,
    uint64_t failed_sources = 0,
    const char *start_time = nullptr,
    const char *end_time = nullptr,
    float duration_seconds = 0.0f) {
  auto start_time__ = start_time ? _fbb.CreateString(start_time) : 0;
  auto end_time__ = end_time ? _fbb.CreateString(end_time) : 0;
  return GRIM::DataCollection::CreateCollectionStats(
      _fbb,
      total_sources,
      sources_processed,
      total_entries,
      total_bytes,
      failed_sources,
      start_time__,
      end_time__,
      duration_seconds);
}

struct MergeStats FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MergeStatsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INPUT_FILES = 4,
    VT_OUTPUT_ENTRIES = 6,
    VT_DUPLICATES_REMOVED = 8,
    VT_BYTES_WRITTEN = 10,
    VT_START_TIME = 12,
    VT_END_TIME = 14,
    VT_DURATION_SECONDS = 16
  };
  uint64_t input_files() const {
    return GetField<uint64_t>(VT_INPUT_FILES, 0);
  }
  uint64_t output_entries() const {
    return GetField<uint64_t>(VT_OUTPUT_ENTRIES, 0);
  }
  uint64_t duplicates_removed() const {
    return GetField<uint64_t>(VT_DUPLICATES_REMOVED, 0);
  }
  uint64_t bytes_written() const {
    return GetField<uint64_t>(VT_BYTES_WRITTEN, 0);
  }
  const ::flatbuffers::String *start_time() const {
    return GetPointer<const ::flatbuffers::String *>(VT_START_TIME);
  }
  const ::flatbuffers::String *end_time() const {
    return GetPointer<const ::flatbuffers::String *>(VT_END_TIME);
  }
  float duration_seconds() const {
    return GetField<float>(VT_DURATION_SECONDS, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_INPUT_FILES, 8) &&
           VerifyField<uint64_t>(verifier, VT_OUTPUT_ENTRIES, 8) &&
           VerifyField<uint64_t>(verifier, VT_DUPLICATES_REMOVED, 8) &&
           VerifyField<uint64_t>(verifier, VT_BYTES_WRITTEN, 8) &&
           VerifyOffset(verifier, VT_START_TIME) &&
           verifier.VerifyString(start_time()) &&
           VerifyOffset(verifier, VT_END_TIME) &&
           verifier.VerifyString(end_time()) &&
           VerifyField<float>(verifier, VT_DURATION_SECONDS, 4) &&
           verifier.EndTable();
  }
};

struct MergeStatsBuilder {
  typedef MergeStats Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_input_files(uint64_t input_files) {
    fbb_.AddElement<uint64_t>(MergeStats::VT_INPUT_FILES, input_files, 0);
  }
  void add_output_entries(uint64_t output_entries) {
    fbb_.AddElement<uint64_t>(MergeStats::VT_OUTPUT_ENTRIES, output_entries, 0);
  }
  void add_duplicates_removed(uint64_t duplicates_removed) {
    fbb_.AddElement<uint64_t>(MergeStats::VT_DUPLICATES_REMOVED, duplicates_removed, 0);
  }
  void add_bytes_written(uint64_t bytes_written) {
    fbb_.AddElement<uint64_t>(MergeStats::VT_BYTES_WRITTEN, bytes_written, 0);
  }
  void add_start_time(::flatbuffers::Offset<::flatbuffers::String> start_time) {
    fbb_.AddOffset(MergeStats::VT_START_TIME, start_time);
  }
  void add_end_time(::flatbuffers::Offset<::flatbuffers::String> end_time) {
    fbb_.AddOffset(MergeStats::VT_END_TIME, end_time);
  }
  void add_duration_seconds(float duration_seconds) {
    fbb_.AddElement<float>(MergeStats::VT_DURATION_SECONDS, duration_seconds, 0.0f);
  }
  explicit MergeStatsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MergeStats> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MergeStats>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MergeStats> CreateMergeStats(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t input_files = 0,
    uint64_t output_entries = 0,
    uint64_t duplicates_removed = 0,
    uint64_t bytes_written = 0,
    ::flatbuffers::Offset<::flatbuffers::String> start_time = 0,
    ::flatbuffers::Offset<::flatbuffers::String> end_time = 0,
    float duration_seconds = 0.0f) {
  MergeStatsBuilder builder_(_fbb);
  builder_.add_bytes_written(bytes_written);
  builder_.add_duplicates_removed(duplicates_removed);
  builder_.add_output_entries(output_entries);
  builder_.add_input_files(input_files);
  builder_.add_duration_seconds(duration_seconds);
  builder_.add_end_time(end_time);
  builder_.add_start_time(start_time);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MergeStats> CreateMergeStatsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t input_files = 0,
    uint64_t output_entries = 0,
    uint64_t duplicates_removed = 0,
    uint64_t bytes_written = 0,
    const char *start_time = nullptr,
    const char *end_time = nullptr,
    float duration_seconds = 0.0f) {
  auto start_time__ = start_time ? _fbb.CreateString(start_time) : 0;
  auto end_time__ = end_time ? _fbb.CreateString(end_time) : 0;
  return GRIM::DataCollection::CreateMergeStats(
      _fbb,
      input_files,
      output_entries,
      duplicates_removed,
      bytes_written,
      start_time__,
      end_time__,
      duration_seconds);
}

struct PipelineReport FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PipelineReportBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COLLECTION_STATS = 4,
    VT_VERIFICATION_STATS = 6,
    VT_MERGE_STATS = 8,
    VT_COLLECTION_LOGS = 10,
    VT_VERIFICATION_LOGS = 12,
    VT_OVERALL_SUCCESS = 14,
    VT_TOTAL_DURATION_SECONDS = 16
  };
  const GRIM::DataCollection::CollectionStats *collection_stats() const {
    return GetPointer<const GRIM::DataCollection::CollectionStats *>(VT_COLLECTION_STATS);
  }
  const GRIM::DataCollection::VerificationStats *verification_stats() const {
    return GetPointer<const GRIM::DataCollection::VerificationStats *>(VT_VERIFICATION_STATS);
  }
  const GRIM::DataCollection::MergeStats *merge_stats() const {
    return GetPointer<const GRIM::DataCollection::MergeStats *>(VT_MERGE_STATS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIM::DataCollection::CollectionLogEntry>> *collection_logs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIM::DataCollection::CollectionLogEntry>> *>(VT_COLLECTION_LOGS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIM::DataCollection::VerificationLogEntry>> *verification_logs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIM::DataCollection::VerificationLogEntry>> *>(VT_VERIFICATION_LOGS);
  }
  bool overall_success() const {
    return GetField<uint8_t>(VT_OVERALL_SUCCESS, 0) != 0;
  }
  float total_duration_seconds() const {
    return GetField<float>(VT_TOTAL_DURATION_SECONDS, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COLLECTION_STATS) &&
           verifier.VerifyTable(collection_stats()) &&
           VerifyOffset(verifier, VT_VERIFICATION_STATS) &&
           verifier.VerifyTable(verification_stats()) &&
           VerifyOffset(verifier, VT_MERGE_STATS) &&
           verifier.VerifyTable(merge_stats()) &&
           VerifyOffset(verifier, VT_COLLECTION_LOGS) &&
           verifier.VerifyVector(collection_logs()) &&
           verifier.VerifyVectorOfTables(collection_logs()) &&
           VerifyOffset(verifier, VT_VERIFICATION_LOGS) &&
           verifier.VerifyVector(verification_logs()) &&
           verifier.VerifyVectorOfTables(verification_logs()) &&
           VerifyField<uint8_t>(verifier, VT_OVERALL_SUCCESS, 1) &&
           VerifyField<float>(verifier, VT_TOTAL_DURATION_SECONDS, 4) &&
           verifier.EndTable();
  }
};

struct PipelineReportBuilder {
  typedef PipelineReport Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_collection_stats(::flatbuffers::Offset<GRIM::DataCollection::CollectionStats> collection_stats) {
    fbb_.AddOffset(PipelineReport::VT_COLLECTION_STATS, collection_stats);
  }
  void add_verification_stats(::flatbuffers::Offset<GRIM::DataCollection::VerificationStats> verification_stats) {
    fbb_.AddOffset(PipelineReport::VT_VERIFICATION_STATS, verification_stats);
  }
  void add_merge_stats(::flatbuffers::Offset<GRIM::DataCollection::MergeStats> merge_stats) {
    fbb_.AddOffset(PipelineReport::VT_MERGE_STATS, merge_stats);
  }
  void add_collection_logs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIM::DataCollection::CollectionLogEntry>>> collection_logs) {
    fbb_.AddOffset(PipelineReport::VT_COLLECTION_LOGS, collection_logs);
  }
  void add_verification_logs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIM::DataCollection::VerificationLogEntry>>> verification_logs) {
    fbb_.AddOffset(PipelineReport::VT_VERIFICATION_LOGS, verification_logs);
  }
  void add_overall_success(bool overall_success) {
    fbb_.AddElement<uint8_t>(PipelineReport::VT_OVERALL_SUCCESS, static_cast<uint8_t>(overall_success), 0);
  }
  void add_total_duration_seconds(float total_duration_seconds) {
    fbb_.AddElement<float>(PipelineReport::VT_TOTAL_DURATION_SECONDS, total_duration_seconds, 0.0f);
  }
  explicit PipelineReportBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PipelineReport> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PipelineReport>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PipelineReport> CreatePipelineReport(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<GRIM::DataCollection::CollectionStats> collection_stats = 0,
    ::flatbuffers::Offset<GRIM::DataCollection::VerificationStats> verification_stats = 0,
    ::flatbuffers::Offset<GRIM::DataCollection::MergeStats> merge_stats = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIM::DataCollection::CollectionLogEntry>>> collection_logs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIM::DataCollection::VerificationLogEntry>>> verification_logs = 0,
    bool overall_success = false,
    float total_duration_seconds = 0.0f) {
  PipelineReportBuilder builder_(_fbb);
  builder_.add_total_duration_seconds(total_duration_seconds);
  builder_.add_verification_logs(verification_logs);
  builder_.add_collection_logs(collection_logs);
  builder_.add_merge_stats(merge_stats);
  builder_.add_verification_stats(verification_stats);
  builder_.add_collection_stats(collection_stats);
  builder_.add_overall_success(overall_success);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PipelineReport> CreatePipelineReportDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<GRIM::DataCollection::CollectionStats> collection_stats = 0,
    ::flatbuffers::Offset<GRIM::DataCollection::VerificationStats> verification_stats = 0,
    ::flatbuffers::Offset<GRIM::DataCollection::MergeStats> merge_stats = 0,
    const std::vector<::flatbuffers::Offset<GRIM::DataCollection::CollectionLogEntry>> *collection_logs = nullptr,
    const std::vector<::flatbuffers::Offset<GRIM::DataCollection::VerificationLogEntry>> *verification_logs = nullptr,
    bool overall_success = false,
    float total_duration_seconds = 0.0f) {
  auto collection_logs__ = collection_logs ? _fbb.CreateVector<::flatbuffers::Offset<GRIM::DataCollection::CollectionLogEntry>>(*collection_logs) : 0;
  auto verification_logs__ = verification_logs ? _fbb.CreateVector<::flatbuffers::Offset<GRIM::DataCollection::VerificationLogEntry>>(*verification_logs) : 0;
  return GRIM::DataCollection::CreatePipelineReport(
      _fbb,
      collection_stats,
      verification_stats,
      merge_stats,
      collection_logs__,
      verification_logs__,
      overall_success,
      total_duration_seconds);
}

struct HealthResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HealthResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATUS = 4,
    VT_UPTIME_SECONDS = 6,
    VT_CURRENT_OPERATION = 8
  };
  const ::flatbuffers::String *status() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STATUS);
  }
  float uptime_seconds() const {
    return GetField<float>(VT_UPTIME_SECONDS, 0.0f);
  }
  const ::flatbuffers::String *current_operation() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CURRENT_OPERATION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_STATUS) &&
           verifier.VerifyString(status()) &&
           VerifyField<float>(verifier, VT_UPTIME_SECONDS, 4) &&
           VerifyOffset(verifier, VT_CURRENT_OPERATION) &&
           verifier.VerifyString(current_operation()) &&
           verifier.EndTable();
  }
};

struct HealthResponseBuilder {
  typedef HealthResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_status(::flatbuffers::Offset<::flatbuffers::String> status) {
    fbb_.AddOffset(HealthResponse::VT_STATUS, status);
  }
  void add_uptime_seconds(float uptime_seconds) {
    fbb_.AddElement<float>(HealthResponse::VT_UPTIME_SECONDS, uptime_seconds, 0.0f);
  }
  void add_current_operation(::flatbuffers::Offset<::flatbuffers::String> current_operation) {
    fbb_.AddOffset(HealthResponse::VT_CURRENT_OPERATION, current_operation);
  }
  explicit HealthResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HealthResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HealthResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HealthResponse> CreateHealthResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> status = 0,
    float uptime_seconds = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::String> current_operation = 0) {
  HealthResponseBuilder builder_(_fbb);
  builder_.add_current_operation(current_operation);
  builder_.add_uptime_seconds(uptime_seconds);
  builder_.add_status(status);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<HealthResponse> CreateHealthResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *status = nullptr,
    float uptime_seconds = 0.0f,
    const char *current_operation = nullptr) {
  auto status__ = status ? _fbb.CreateString(status) : 0;
  auto current_operation__ = current_operation ? _fbb.CreateString(current_operation) : 0;
  return GRIM::DataCollection::CreateHealthResponse(
      _fbb,
      status__,
      uptime_seconds,
      current_operation__);
}

inline const GRIM::DataCollection::DataCollectionRequest *GetDataCollectionRequest(const void *buf) {
  return ::flatbuffers::GetRoot<GRIM::DataCollection::DataCollectionRequest>(buf);
}

inline const GRIM::DataCollection::DataCollectionRequest *GetSizePrefixedDataCollectionRequest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GRIM::DataCollection::DataCollectionRequest>(buf);
}

inline bool VerifyDataCollectionRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GRIM::DataCollection::DataCollectionRequest>(nullptr);
}

inline bool VerifySizePrefixedDataCollectionRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GRIM::DataCollection::DataCollectionRequest>(nullptr);
}

inline void FinishDataCollectionRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIM::DataCollection::DataCollectionRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDataCollectionRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIM::DataCollection::DataCollectionRequest> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace DataCollection
}  // namespace GRIM

#endif  // FLATBUFFERS_GENERATED_DATACOLLECTIONPROTOCOL_GRIM_DATACOLLECTION_H_
