// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TRAININGCONTROL_GRIMTEXT_CONTROL_H_
#define FLATBUFFERS_GENERATED_TRAININGCONTROL_GRIMTEXT_CONTROL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 && FLATBUFFERS_VERSION_MINOR >= 2,
             "Non-compatible flatbuffers version included (need 25.2.x)");

namespace GRIMText {
namespace Control {

struct TrainingStats;
struct TrainingStatsBuilder;

struct TrainingConfig;
struct TrainingConfigBuilder;

struct StatusResponse;
struct StatusResponseBuilder;

struct StartTrainingRequest;
struct StartTrainingRequestBuilder;

struct StartTrainingResponse;
struct StartTrainingResponseBuilder;

struct StopTrainingRequest;
struct StopTrainingRequestBuilder;

struct StopTrainingResponse;
struct StopTrainingResponseBuilder;

struct UpdateConfigRequest;
struct UpdateConfigRequestBuilder;

struct UpdateConfigResponse;
struct UpdateConfigResponseBuilder;

struct HealthCheckResponse;
struct HealthCheckResponseBuilder;

struct CheckpointInfo;
struct CheckpointInfoBuilder;

struct CheckpointDetectRequest;
struct CheckpointDetectRequestBuilder;

struct CheckpointDetectResponse;
struct CheckpointDetectResponseBuilder;

struct CheckpointMergeRequest;
struct CheckpointMergeRequestBuilder;

struct CheckpointMergeResponse;
struct CheckpointMergeResponseBuilder;

struct DataCollectionRequest;
struct DataCollectionRequestBuilder;

struct DataCollectionResponse;
struct DataCollectionResponseBuilder;

struct ServerShutdownRequest;
struct ServerShutdownRequestBuilder;

struct ServerShutdownResponse;
struct ServerShutdownResponseBuilder;

enum TrainingState : int8_t {
  TrainingState_Idle = 0,
  TrainingState_Collecting = 1,
  TrainingState_Verifying = 2,
  TrainingState_Training = 3,
  TrainingState_Paused = 4,
  TrainingState_Completed = 5,
  TrainingState_Error = 6,
  TrainingState_MIN = TrainingState_Idle,
  TrainingState_MAX = TrainingState_Error
};

inline const TrainingState (&EnumValuesTrainingState())[7] {
  static const TrainingState values[] = {
    TrainingState_Idle,
    TrainingState_Collecting,
    TrainingState_Verifying,
    TrainingState_Training,
    TrainingState_Paused,
    TrainingState_Completed,
    TrainingState_Error
  };
  return values;
}

inline const char * const *EnumNamesTrainingState() {
  static const char * const names[8] = {
    "Idle",
    "Collecting",
    "Verifying",
    "Training",
    "Paused",
    "Completed",
    "Error",
    nullptr
  };
  return names;
}

inline const char *EnumNameTrainingState(TrainingState e) {
  if (::flatbuffers::IsOutRange(e, TrainingState_Idle, TrainingState_Error)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTrainingState()[index];
}

struct TrainingStats FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrainingStatsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CURRENT_EPOCH = 4,
    VT_TOTAL_EPOCHS = 6,
    VT_CURRENT_BATCH = 8,
    VT_TOTAL_BATCHES = 10,
    VT_CURRENT_LOSS = 12,
    VT_AVG_LOSS = 14,
    VT_PERPLEXITY = 16,
    VT_TOKENS_PER_SEC = 18,
    VT_GPU_MEMORY_USED = 20,
    VT_GPU_MEMORY_TOTAL = 22,
    VT_TRAINING_PROGRESS = 24,
    VT_COLLECTION_PROGRESS = 26,
    VT_CURRENT_PHASE = 28,
    VT_LAST_ERROR = 30,
    VT_START_TIME = 32,
    VT_ELAPSED_TIME = 34
  };
  int32_t current_epoch() const {
    return GetField<int32_t>(VT_CURRENT_EPOCH, 0);
  }
  int32_t total_epochs() const {
    return GetField<int32_t>(VT_TOTAL_EPOCHS, 3);
  }
  int32_t current_batch() const {
    return GetField<int32_t>(VT_CURRENT_BATCH, 0);
  }
  int32_t total_batches() const {
    return GetField<int32_t>(VT_TOTAL_BATCHES, 0);
  }
  float current_loss() const {
    return GetField<float>(VT_CURRENT_LOSS, 0.0f);
  }
  float avg_loss() const {
    return GetField<float>(VT_AVG_LOSS, 0.0f);
  }
  float perplexity() const {
    return GetField<float>(VT_PERPLEXITY, 0.0f);
  }
  float tokens_per_sec() const {
    return GetField<float>(VT_TOKENS_PER_SEC, 0.0f);
  }
  float gpu_memory_used() const {
    return GetField<float>(VT_GPU_MEMORY_USED, 0.0f);
  }
  float gpu_memory_total() const {
    return GetField<float>(VT_GPU_MEMORY_TOTAL, 0.0f);
  }
  float training_progress() const {
    return GetField<float>(VT_TRAINING_PROGRESS, 0.0f);
  }
  float collection_progress() const {
    return GetField<float>(VT_COLLECTION_PROGRESS, 0.0f);
  }
  const ::flatbuffers::String *current_phase() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CURRENT_PHASE);
  }
  const ::flatbuffers::String *last_error() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LAST_ERROR);
  }
  int64_t start_time() const {
    return GetField<int64_t>(VT_START_TIME, 0);
  }
  int64_t elapsed_time() const {
    return GetField<int64_t>(VT_ELAPSED_TIME, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_CURRENT_EPOCH, 4) &&
           VerifyField<int32_t>(verifier, VT_TOTAL_EPOCHS, 4) &&
           VerifyField<int32_t>(verifier, VT_CURRENT_BATCH, 4) &&
           VerifyField<int32_t>(verifier, VT_TOTAL_BATCHES, 4) &&
           VerifyField<float>(verifier, VT_CURRENT_LOSS, 4) &&
           VerifyField<float>(verifier, VT_AVG_LOSS, 4) &&
           VerifyField<float>(verifier, VT_PERPLEXITY, 4) &&
           VerifyField<float>(verifier, VT_TOKENS_PER_SEC, 4) &&
           VerifyField<float>(verifier, VT_GPU_MEMORY_USED, 4) &&
           VerifyField<float>(verifier, VT_GPU_MEMORY_TOTAL, 4) &&
           VerifyField<float>(verifier, VT_TRAINING_PROGRESS, 4) &&
           VerifyField<float>(verifier, VT_COLLECTION_PROGRESS, 4) &&
           VerifyOffset(verifier, VT_CURRENT_PHASE) &&
           verifier.VerifyString(current_phase()) &&
           VerifyOffset(verifier, VT_LAST_ERROR) &&
           verifier.VerifyString(last_error()) &&
           VerifyField<int64_t>(verifier, VT_START_TIME, 8) &&
           VerifyField<int64_t>(verifier, VT_ELAPSED_TIME, 8) &&
           verifier.EndTable();
  }
};

struct TrainingStatsBuilder {
  typedef TrainingStats Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_current_epoch(int32_t current_epoch) {
    fbb_.AddElement<int32_t>(TrainingStats::VT_CURRENT_EPOCH, current_epoch, 0);
  }
  void add_total_epochs(int32_t total_epochs) {
    fbb_.AddElement<int32_t>(TrainingStats::VT_TOTAL_EPOCHS, total_epochs, 3);
  }
  void add_current_batch(int32_t current_batch) {
    fbb_.AddElement<int32_t>(TrainingStats::VT_CURRENT_BATCH, current_batch, 0);
  }
  void add_total_batches(int32_t total_batches) {
    fbb_.AddElement<int32_t>(TrainingStats::VT_TOTAL_BATCHES, total_batches, 0);
  }
  void add_current_loss(float current_loss) {
    fbb_.AddElement<float>(TrainingStats::VT_CURRENT_LOSS, current_loss, 0.0f);
  }
  void add_avg_loss(float avg_loss) {
    fbb_.AddElement<float>(TrainingStats::VT_AVG_LOSS, avg_loss, 0.0f);
  }
  void add_perplexity(float perplexity) {
    fbb_.AddElement<float>(TrainingStats::VT_PERPLEXITY, perplexity, 0.0f);
  }
  void add_tokens_per_sec(float tokens_per_sec) {
    fbb_.AddElement<float>(TrainingStats::VT_TOKENS_PER_SEC, tokens_per_sec, 0.0f);
  }
  void add_gpu_memory_used(float gpu_memory_used) {
    fbb_.AddElement<float>(TrainingStats::VT_GPU_MEMORY_USED, gpu_memory_used, 0.0f);
  }
  void add_gpu_memory_total(float gpu_memory_total) {
    fbb_.AddElement<float>(TrainingStats::VT_GPU_MEMORY_TOTAL, gpu_memory_total, 0.0f);
  }
  void add_training_progress(float training_progress) {
    fbb_.AddElement<float>(TrainingStats::VT_TRAINING_PROGRESS, training_progress, 0.0f);
  }
  void add_collection_progress(float collection_progress) {
    fbb_.AddElement<float>(TrainingStats::VT_COLLECTION_PROGRESS, collection_progress, 0.0f);
  }
  void add_current_phase(::flatbuffers::Offset<::flatbuffers::String> current_phase) {
    fbb_.AddOffset(TrainingStats::VT_CURRENT_PHASE, current_phase);
  }
  void add_last_error(::flatbuffers::Offset<::flatbuffers::String> last_error) {
    fbb_.AddOffset(TrainingStats::VT_LAST_ERROR, last_error);
  }
  void add_start_time(int64_t start_time) {
    fbb_.AddElement<int64_t>(TrainingStats::VT_START_TIME, start_time, 0);
  }
  void add_elapsed_time(int64_t elapsed_time) {
    fbb_.AddElement<int64_t>(TrainingStats::VT_ELAPSED_TIME, elapsed_time, 0);
  }
  explicit TrainingStatsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrainingStats> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrainingStats>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TrainingStats> CreateTrainingStats(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t current_epoch = 0,
    int32_t total_epochs = 3,
    int32_t current_batch = 0,
    int32_t total_batches = 0,
    float current_loss = 0.0f,
    float avg_loss = 0.0f,
    float perplexity = 0.0f,
    float tokens_per_sec = 0.0f,
    float gpu_memory_used = 0.0f,
    float gpu_memory_total = 0.0f,
    float training_progress = 0.0f,
    float collection_progress = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::String> current_phase = 0,
    ::flatbuffers::Offset<::flatbuffers::String> last_error = 0,
    int64_t start_time = 0,
    int64_t elapsed_time = 0) {
  TrainingStatsBuilder builder_(_fbb);
  builder_.add_elapsed_time(elapsed_time);
  builder_.add_start_time(start_time);
  builder_.add_last_error(last_error);
  builder_.add_current_phase(current_phase);
  builder_.add_collection_progress(collection_progress);
  builder_.add_training_progress(training_progress);
  builder_.add_gpu_memory_total(gpu_memory_total);
  builder_.add_gpu_memory_used(gpu_memory_used);
  builder_.add_tokens_per_sec(tokens_per_sec);
  builder_.add_perplexity(perplexity);
  builder_.add_avg_loss(avg_loss);
  builder_.add_current_loss(current_loss);
  builder_.add_total_batches(total_batches);
  builder_.add_current_batch(current_batch);
  builder_.add_total_epochs(total_epochs);
  builder_.add_current_epoch(current_epoch);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TrainingStats> CreateTrainingStatsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t current_epoch = 0,
    int32_t total_epochs = 3,
    int32_t current_batch = 0,
    int32_t total_batches = 0,
    float current_loss = 0.0f,
    float avg_loss = 0.0f,
    float perplexity = 0.0f,
    float tokens_per_sec = 0.0f,
    float gpu_memory_used = 0.0f,
    float gpu_memory_total = 0.0f,
    float training_progress = 0.0f,
    float collection_progress = 0.0f,
    const char *current_phase = nullptr,
    const char *last_error = nullptr,
    int64_t start_time = 0,
    int64_t elapsed_time = 0) {
  auto current_phase__ = current_phase ? _fbb.CreateString(current_phase) : 0;
  auto last_error__ = last_error ? _fbb.CreateString(last_error) : 0;
  return GRIMText::Control::CreateTrainingStats(
      _fbb,
      current_epoch,
      total_epochs,
      current_batch,
      total_batches,
      current_loss,
      avg_loss,
      perplexity,
      tokens_per_sec,
      gpu_memory_used,
      gpu_memory_total,
      training_progress,
      collection_progress,
      current_phase__,
      last_error__,
      start_time,
      elapsed_time);
}

struct TrainingConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrainingConfigBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EPOCHS = 4,
    VT_BATCH_SIZE = 6,
    VT_LEARNING_RATE = 8,
    VT_MAX_SEQ_LEN = 10,
    VT_WARMUP_STEPS = 12,
    VT_USE_GPU = 14,
    VT_USE_FLASH_ATTENTION = 16,
    VT_DATA_PATH = 18,
    VT_VOCAB_PATH = 20,
    VT_OUTPUT_PATH = 22
  };
  int32_t epochs() const {
    return GetField<int32_t>(VT_EPOCHS, 3);
  }
  int32_t batch_size() const {
    return GetField<int32_t>(VT_BATCH_SIZE, 8);
  }
  float learning_rate() const {
    return GetField<float>(VT_LEARNING_RATE, 0.0001f);
  }
  int32_t max_seq_len() const {
    return GetField<int32_t>(VT_MAX_SEQ_LEN, 8192);
  }
  int32_t warmup_steps() const {
    return GetField<int32_t>(VT_WARMUP_STEPS, 1000);
  }
  bool use_gpu() const {
    return GetField<uint8_t>(VT_USE_GPU, 1) != 0;
  }
  bool use_flash_attention() const {
    return GetField<uint8_t>(VT_USE_FLASH_ATTENTION, 1) != 0;
  }
  const ::flatbuffers::String *data_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATA_PATH);
  }
  const ::flatbuffers::String *vocab_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VOCAB_PATH);
  }
  const ::flatbuffers::String *output_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OUTPUT_PATH);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_EPOCHS, 4) &&
           VerifyField<int32_t>(verifier, VT_BATCH_SIZE, 4) &&
           VerifyField<float>(verifier, VT_LEARNING_RATE, 4) &&
           VerifyField<int32_t>(verifier, VT_MAX_SEQ_LEN, 4) &&
           VerifyField<int32_t>(verifier, VT_WARMUP_STEPS, 4) &&
           VerifyField<uint8_t>(verifier, VT_USE_GPU, 1) &&
           VerifyField<uint8_t>(verifier, VT_USE_FLASH_ATTENTION, 1) &&
           VerifyOffset(verifier, VT_DATA_PATH) &&
           verifier.VerifyString(data_path()) &&
           VerifyOffset(verifier, VT_VOCAB_PATH) &&
           verifier.VerifyString(vocab_path()) &&
           VerifyOffset(verifier, VT_OUTPUT_PATH) &&
           verifier.VerifyString(output_path()) &&
           verifier.EndTable();
  }
};

struct TrainingConfigBuilder {
  typedef TrainingConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_epochs(int32_t epochs) {
    fbb_.AddElement<int32_t>(TrainingConfig::VT_EPOCHS, epochs, 3);
  }
  void add_batch_size(int32_t batch_size) {
    fbb_.AddElement<int32_t>(TrainingConfig::VT_BATCH_SIZE, batch_size, 8);
  }
  void add_learning_rate(float learning_rate) {
    fbb_.AddElement<float>(TrainingConfig::VT_LEARNING_RATE, learning_rate, 0.0001f);
  }
  void add_max_seq_len(int32_t max_seq_len) {
    fbb_.AddElement<int32_t>(TrainingConfig::VT_MAX_SEQ_LEN, max_seq_len, 8192);
  }
  void add_warmup_steps(int32_t warmup_steps) {
    fbb_.AddElement<int32_t>(TrainingConfig::VT_WARMUP_STEPS, warmup_steps, 1000);
  }
  void add_use_gpu(bool use_gpu) {
    fbb_.AddElement<uint8_t>(TrainingConfig::VT_USE_GPU, static_cast<uint8_t>(use_gpu), 1);
  }
  void add_use_flash_attention(bool use_flash_attention) {
    fbb_.AddElement<uint8_t>(TrainingConfig::VT_USE_FLASH_ATTENTION, static_cast<uint8_t>(use_flash_attention), 1);
  }
  void add_data_path(::flatbuffers::Offset<::flatbuffers::String> data_path) {
    fbb_.AddOffset(TrainingConfig::VT_DATA_PATH, data_path);
  }
  void add_vocab_path(::flatbuffers::Offset<::flatbuffers::String> vocab_path) {
    fbb_.AddOffset(TrainingConfig::VT_VOCAB_PATH, vocab_path);
  }
  void add_output_path(::flatbuffers::Offset<::flatbuffers::String> output_path) {
    fbb_.AddOffset(TrainingConfig::VT_OUTPUT_PATH, output_path);
  }
  explicit TrainingConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrainingConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrainingConfig>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TrainingConfig> CreateTrainingConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t epochs = 3,
    int32_t batch_size = 8,
    float learning_rate = 0.0001f,
    int32_t max_seq_len = 8192,
    int32_t warmup_steps = 1000,
    bool use_gpu = true,
    bool use_flash_attention = true,
    ::flatbuffers::Offset<::flatbuffers::String> data_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> vocab_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> output_path = 0) {
  TrainingConfigBuilder builder_(_fbb);
  builder_.add_output_path(output_path);
  builder_.add_vocab_path(vocab_path);
  builder_.add_data_path(data_path);
  builder_.add_warmup_steps(warmup_steps);
  builder_.add_max_seq_len(max_seq_len);
  builder_.add_learning_rate(learning_rate);
  builder_.add_batch_size(batch_size);
  builder_.add_epochs(epochs);
  builder_.add_use_flash_attention(use_flash_attention);
  builder_.add_use_gpu(use_gpu);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TrainingConfig> CreateTrainingConfigDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t epochs = 3,
    int32_t batch_size = 8,
    float learning_rate = 0.0001f,
    int32_t max_seq_len = 8192,
    int32_t warmup_steps = 1000,
    bool use_gpu = true,
    bool use_flash_attention = true,
    const char *data_path = nullptr,
    const char *vocab_path = nullptr,
    const char *output_path = nullptr) {
  auto data_path__ = data_path ? _fbb.CreateString(data_path) : 0;
  auto vocab_path__ = vocab_path ? _fbb.CreateString(vocab_path) : 0;
  auto output_path__ = output_path ? _fbb.CreateString(output_path) : 0;
  return GRIMText::Control::CreateTrainingConfig(
      _fbb,
      epochs,
      batch_size,
      learning_rate,
      max_seq_len,
      warmup_steps,
      use_gpu,
      use_flash_attention,
      data_path__,
      vocab_path__,
      output_path__);
}

struct StatusResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StatusResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATE = 4,
    VT_STATS = 6,
    VT_CONFIG = 8,
    VT_PROCESS_RUNNING = 10,
    VT_TIMESTAMP = 12
  };
  GRIMText::Control::TrainingState state() const {
    return static_cast<GRIMText::Control::TrainingState>(GetField<int8_t>(VT_STATE, 0));
  }
  const GRIMText::Control::TrainingStats *stats() const {
    return GetPointer<const GRIMText::Control::TrainingStats *>(VT_STATS);
  }
  const GRIMText::Control::TrainingConfig *config() const {
    return GetPointer<const GRIMText::Control::TrainingConfig *>(VT_CONFIG);
  }
  bool process_running() const {
    return GetField<uint8_t>(VT_PROCESS_RUNNING, 0) != 0;
  }
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_STATE, 1) &&
           VerifyOffset(verifier, VT_STATS) &&
           verifier.VerifyTable(stats()) &&
           VerifyOffset(verifier, VT_CONFIG) &&
           verifier.VerifyTable(config()) &&
           VerifyField<uint8_t>(verifier, VT_PROCESS_RUNNING, 1) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct StatusResponseBuilder {
  typedef StatusResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_state(GRIMText::Control::TrainingState state) {
    fbb_.AddElement<int8_t>(StatusResponse::VT_STATE, static_cast<int8_t>(state), 0);
  }
  void add_stats(::flatbuffers::Offset<GRIMText::Control::TrainingStats> stats) {
    fbb_.AddOffset(StatusResponse::VT_STATS, stats);
  }
  void add_config(::flatbuffers::Offset<GRIMText::Control::TrainingConfig> config) {
    fbb_.AddOffset(StatusResponse::VT_CONFIG, config);
  }
  void add_process_running(bool process_running) {
    fbb_.AddElement<uint8_t>(StatusResponse::VT_PROCESS_RUNNING, static_cast<uint8_t>(process_running), 0);
  }
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(StatusResponse::VT_TIMESTAMP, timestamp, 0);
  }
  explicit StatusResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StatusResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StatusResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StatusResponse> CreateStatusResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GRIMText::Control::TrainingState state = GRIMText::Control::TrainingState_Idle,
    ::flatbuffers::Offset<GRIMText::Control::TrainingStats> stats = 0,
    ::flatbuffers::Offset<GRIMText::Control::TrainingConfig> config = 0,
    bool process_running = false,
    int64_t timestamp = 0) {
  StatusResponseBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_config(config);
  builder_.add_stats(stats);
  builder_.add_process_running(process_running);
  builder_.add_state(state);
  return builder_.Finish();
}

struct StartTrainingRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StartTrainingRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONFIG = 4
  };
  const GRIMText::Control::TrainingConfig *config() const {
    return GetPointer<const GRIMText::Control::TrainingConfig *>(VT_CONFIG);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CONFIG) &&
           verifier.VerifyTable(config()) &&
           verifier.EndTable();
  }
};

struct StartTrainingRequestBuilder {
  typedef StartTrainingRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_config(::flatbuffers::Offset<GRIMText::Control::TrainingConfig> config) {
    fbb_.AddOffset(StartTrainingRequest::VT_CONFIG, config);
  }
  explicit StartTrainingRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StartTrainingRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StartTrainingRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StartTrainingRequest> CreateStartTrainingRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<GRIMText::Control::TrainingConfig> config = 0) {
  StartTrainingRequestBuilder builder_(_fbb);
  builder_.add_config(config);
  return builder_.Finish();
}

struct StartTrainingResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StartTrainingResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUCCESS = 4,
    VT_MESSAGE = 6,
    VT_ERROR = 8
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  const ::flatbuffers::String *error() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_ERROR) &&
           verifier.VerifyString(error()) &&
           verifier.EndTable();
  }
};

struct StartTrainingResponseBuilder {
  typedef StartTrainingResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(StartTrainingResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(StartTrainingResponse::VT_MESSAGE, message);
  }
  void add_error(::flatbuffers::Offset<::flatbuffers::String> error) {
    fbb_.AddOffset(StartTrainingResponse::VT_ERROR, error);
  }
  explicit StartTrainingResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StartTrainingResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StartTrainingResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StartTrainingResponse> CreateStartTrainingResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error = 0) {
  StartTrainingResponseBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_message(message);
  builder_.add_success(success);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StartTrainingResponse> CreateStartTrainingResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    const char *message = nullptr,
    const char *error = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto error__ = error ? _fbb.CreateString(error) : 0;
  return GRIMText::Control::CreateStartTrainingResponse(
      _fbb,
      success,
      message__,
      error__);
}

struct StopTrainingRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StopTrainingRequestBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct StopTrainingRequestBuilder {
  typedef StopTrainingRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit StopTrainingRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StopTrainingRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StopTrainingRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StopTrainingRequest> CreateStopTrainingRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  StopTrainingRequestBuilder builder_(_fbb);
  return builder_.Finish();
}

struct StopTrainingResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StopTrainingResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUCCESS = 4,
    VT_MESSAGE = 6
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
};

struct StopTrainingResponseBuilder {
  typedef StopTrainingResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(StopTrainingResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(StopTrainingResponse::VT_MESSAGE, message);
  }
  explicit StopTrainingResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StopTrainingResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StopTrainingResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StopTrainingResponse> CreateStopTrainingResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  StopTrainingResponseBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_success(success);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StopTrainingResponse> CreateStopTrainingResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return GRIMText::Control::CreateStopTrainingResponse(
      _fbb,
      success,
      message__);
}

struct UpdateConfigRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateConfigRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONFIG = 4
  };
  const GRIMText::Control::TrainingConfig *config() const {
    return GetPointer<const GRIMText::Control::TrainingConfig *>(VT_CONFIG);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CONFIG) &&
           verifier.VerifyTable(config()) &&
           verifier.EndTable();
  }
};

struct UpdateConfigRequestBuilder {
  typedef UpdateConfigRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_config(::flatbuffers::Offset<GRIMText::Control::TrainingConfig> config) {
    fbb_.AddOffset(UpdateConfigRequest::VT_CONFIG, config);
  }
  explicit UpdateConfigRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdateConfigRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdateConfigRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdateConfigRequest> CreateUpdateConfigRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<GRIMText::Control::TrainingConfig> config = 0) {
  UpdateConfigRequestBuilder builder_(_fbb);
  builder_.add_config(config);
  return builder_.Finish();
}

struct UpdateConfigResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateConfigResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUCCESS = 4,
    VT_MESSAGE = 6,
    VT_ERROR = 8
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  const ::flatbuffers::String *error() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_ERROR) &&
           verifier.VerifyString(error()) &&
           verifier.EndTable();
  }
};

struct UpdateConfigResponseBuilder {
  typedef UpdateConfigResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(UpdateConfigResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(UpdateConfigResponse::VT_MESSAGE, message);
  }
  void add_error(::flatbuffers::Offset<::flatbuffers::String> error) {
    fbb_.AddOffset(UpdateConfigResponse::VT_ERROR, error);
  }
  explicit UpdateConfigResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdateConfigResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdateConfigResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdateConfigResponse> CreateUpdateConfigResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error = 0) {
  UpdateConfigResponseBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_message(message);
  builder_.add_success(success);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UpdateConfigResponse> CreateUpdateConfigResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    const char *message = nullptr,
    const char *error = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto error__ = error ? _fbb.CreateString(error) : 0;
  return GRIMText::Control::CreateUpdateConfigResponse(
      _fbb,
      success,
      message__,
      error__);
}

struct HealthCheckResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HealthCheckResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATUS = 4,
    VT_SERVICE = 6,
    VT_VERSION = 8
  };
  const ::flatbuffers::String *status() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STATUS);
  }
  const ::flatbuffers::String *service() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SERVICE);
  }
  const ::flatbuffers::String *version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VERSION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_STATUS) &&
           verifier.VerifyString(status()) &&
           VerifyOffset(verifier, VT_SERVICE) &&
           verifier.VerifyString(service()) &&
           VerifyOffset(verifier, VT_VERSION) &&
           verifier.VerifyString(version()) &&
           verifier.EndTable();
  }
};

struct HealthCheckResponseBuilder {
  typedef HealthCheckResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_status(::flatbuffers::Offset<::flatbuffers::String> status) {
    fbb_.AddOffset(HealthCheckResponse::VT_STATUS, status);
  }
  void add_service(::flatbuffers::Offset<::flatbuffers::String> service) {
    fbb_.AddOffset(HealthCheckResponse::VT_SERVICE, service);
  }
  void add_version(::flatbuffers::Offset<::flatbuffers::String> version) {
    fbb_.AddOffset(HealthCheckResponse::VT_VERSION, version);
  }
  explicit HealthCheckResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HealthCheckResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HealthCheckResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HealthCheckResponse> CreateHealthCheckResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> status = 0,
    ::flatbuffers::Offset<::flatbuffers::String> service = 0,
    ::flatbuffers::Offset<::flatbuffers::String> version = 0) {
  HealthCheckResponseBuilder builder_(_fbb);
  builder_.add_version(version);
  builder_.add_service(service);
  builder_.add_status(status);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<HealthCheckResponse> CreateHealthCheckResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *status = nullptr,
    const char *service = nullptr,
    const char *version = nullptr) {
  auto status__ = status ? _fbb.CreateString(status) : 0;
  auto service__ = service ? _fbb.CreateString(service) : 0;
  auto version__ = version ? _fbb.CreateString(version) : 0;
  return GRIMText::Control::CreateHealthCheckResponse(
      _fbb,
      status__,
      service__,
      version__);
}

struct CheckpointInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CheckpointInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATH = 4,
    VT_SIZE = 6,
    VT_ENTRY_COUNT = 8
  };
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  int64_t size() const {
    return GetField<int64_t>(VT_SIZE, 0);
  }
  int32_t entry_count() const {
    return GetField<int32_t>(VT_ENTRY_COUNT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           VerifyField<int64_t>(verifier, VT_SIZE, 8) &&
           VerifyField<int32_t>(verifier, VT_ENTRY_COUNT, 4) &&
           verifier.EndTable();
  }
};

struct CheckpointInfoBuilder {
  typedef CheckpointInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(CheckpointInfo::VT_PATH, path);
  }
  void add_size(int64_t size) {
    fbb_.AddElement<int64_t>(CheckpointInfo::VT_SIZE, size, 0);
  }
  void add_entry_count(int32_t entry_count) {
    fbb_.AddElement<int32_t>(CheckpointInfo::VT_ENTRY_COUNT, entry_count, 0);
  }
  explicit CheckpointInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CheckpointInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CheckpointInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CheckpointInfo> CreateCheckpointInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0,
    int64_t size = 0,
    int32_t entry_count = 0) {
  CheckpointInfoBuilder builder_(_fbb);
  builder_.add_size(size);
  builder_.add_entry_count(entry_count);
  builder_.add_path(path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CheckpointInfo> CreateCheckpointInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr,
    int64_t size = 0,
    int32_t entry_count = 0) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  return GRIMText::Control::CreateCheckpointInfo(
      _fbb,
      path__,
      size,
      entry_count);
}

struct CheckpointDetectRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CheckpointDetectRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHECKPOINT_DIR = 4
  };
  const ::flatbuffers::String *checkpoint_dir() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CHECKPOINT_DIR);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CHECKPOINT_DIR) &&
           verifier.VerifyString(checkpoint_dir()) &&
           verifier.EndTable();
  }
};

struct CheckpointDetectRequestBuilder {
  typedef CheckpointDetectRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_checkpoint_dir(::flatbuffers::Offset<::flatbuffers::String> checkpoint_dir) {
    fbb_.AddOffset(CheckpointDetectRequest::VT_CHECKPOINT_DIR, checkpoint_dir);
  }
  explicit CheckpointDetectRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CheckpointDetectRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CheckpointDetectRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CheckpointDetectRequest> CreateCheckpointDetectRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> checkpoint_dir = 0) {
  CheckpointDetectRequestBuilder builder_(_fbb);
  builder_.add_checkpoint_dir(checkpoint_dir);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CheckpointDetectRequest> CreateCheckpointDetectRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *checkpoint_dir = nullptr) {
  auto checkpoint_dir__ = checkpoint_dir ? _fbb.CreateString(checkpoint_dir) : 0;
  return GRIMText::Control::CreateCheckpointDetectRequest(
      _fbb,
      checkpoint_dir__);
}

struct CheckpointDetectResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CheckpointDetectResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUCCESS = 4,
    VT_CHECKPOINT_COUNT = 6,
    VT_TOTAL_ENTRIES = 8,
    VT_TOTAL_SIZE = 10,
    VT_CHECKPOINTS = 12,
    VT_MESSAGE = 14,
    VT_ERROR = 16
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  int32_t checkpoint_count() const {
    return GetField<int32_t>(VT_CHECKPOINT_COUNT, 0);
  }
  int32_t total_entries() const {
    return GetField<int32_t>(VT_TOTAL_ENTRIES, 0);
  }
  int64_t total_size() const {
    return GetField<int64_t>(VT_TOTAL_SIZE, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMText::Control::CheckpointInfo>> *checkpoints() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMText::Control::CheckpointInfo>> *>(VT_CHECKPOINTS);
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  const ::flatbuffers::String *error() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           VerifyField<int32_t>(verifier, VT_CHECKPOINT_COUNT, 4) &&
           VerifyField<int32_t>(verifier, VT_TOTAL_ENTRIES, 4) &&
           VerifyField<int64_t>(verifier, VT_TOTAL_SIZE, 8) &&
           VerifyOffset(verifier, VT_CHECKPOINTS) &&
           verifier.VerifyVector(checkpoints()) &&
           verifier.VerifyVectorOfTables(checkpoints()) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_ERROR) &&
           verifier.VerifyString(error()) &&
           verifier.EndTable();
  }
};

struct CheckpointDetectResponseBuilder {
  typedef CheckpointDetectResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(CheckpointDetectResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  void add_checkpoint_count(int32_t checkpoint_count) {
    fbb_.AddElement<int32_t>(CheckpointDetectResponse::VT_CHECKPOINT_COUNT, checkpoint_count, 0);
  }
  void add_total_entries(int32_t total_entries) {
    fbb_.AddElement<int32_t>(CheckpointDetectResponse::VT_TOTAL_ENTRIES, total_entries, 0);
  }
  void add_total_size(int64_t total_size) {
    fbb_.AddElement<int64_t>(CheckpointDetectResponse::VT_TOTAL_SIZE, total_size, 0);
  }
  void add_checkpoints(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMText::Control::CheckpointInfo>>> checkpoints) {
    fbb_.AddOffset(CheckpointDetectResponse::VT_CHECKPOINTS, checkpoints);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(CheckpointDetectResponse::VT_MESSAGE, message);
  }
  void add_error(::flatbuffers::Offset<::flatbuffers::String> error) {
    fbb_.AddOffset(CheckpointDetectResponse::VT_ERROR, error);
  }
  explicit CheckpointDetectResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CheckpointDetectResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CheckpointDetectResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CheckpointDetectResponse> CreateCheckpointDetectResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    int32_t checkpoint_count = 0,
    int32_t total_entries = 0,
    int64_t total_size = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMText::Control::CheckpointInfo>>> checkpoints = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error = 0) {
  CheckpointDetectResponseBuilder builder_(_fbb);
  builder_.add_total_size(total_size);
  builder_.add_error(error);
  builder_.add_message(message);
  builder_.add_checkpoints(checkpoints);
  builder_.add_total_entries(total_entries);
  builder_.add_checkpoint_count(checkpoint_count);
  builder_.add_success(success);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CheckpointDetectResponse> CreateCheckpointDetectResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    int32_t checkpoint_count = 0,
    int32_t total_entries = 0,
    int64_t total_size = 0,
    const std::vector<::flatbuffers::Offset<GRIMText::Control::CheckpointInfo>> *checkpoints = nullptr,
    const char *message = nullptr,
    const char *error = nullptr) {
  auto checkpoints__ = checkpoints ? _fbb.CreateVector<::flatbuffers::Offset<GRIMText::Control::CheckpointInfo>>(*checkpoints) : 0;
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto error__ = error ? _fbb.CreateString(error) : 0;
  return GRIMText::Control::CreateCheckpointDetectResponse(
      _fbb,
      success,
      checkpoint_count,
      total_entries,
      total_size,
      checkpoints__,
      message__,
      error__);
}

struct CheckpointMergeRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CheckpointMergeRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHECKPOINT_DIR = 4,
    VT_VERIFIED_DIR = 6,
    VT_OUTPUT_DIR = 8,
    VT_SKIP_VERIFICATION = 10
  };
  const ::flatbuffers::String *checkpoint_dir() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CHECKPOINT_DIR);
  }
  const ::flatbuffers::String *verified_dir() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VERIFIED_DIR);
  }
  const ::flatbuffers::String *output_dir() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OUTPUT_DIR);
  }
  bool skip_verification() const {
    return GetField<uint8_t>(VT_SKIP_VERIFICATION, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CHECKPOINT_DIR) &&
           verifier.VerifyString(checkpoint_dir()) &&
           VerifyOffset(verifier, VT_VERIFIED_DIR) &&
           verifier.VerifyString(verified_dir()) &&
           VerifyOffset(verifier, VT_OUTPUT_DIR) &&
           verifier.VerifyString(output_dir()) &&
           VerifyField<uint8_t>(verifier, VT_SKIP_VERIFICATION, 1) &&
           verifier.EndTable();
  }
};

struct CheckpointMergeRequestBuilder {
  typedef CheckpointMergeRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_checkpoint_dir(::flatbuffers::Offset<::flatbuffers::String> checkpoint_dir) {
    fbb_.AddOffset(CheckpointMergeRequest::VT_CHECKPOINT_DIR, checkpoint_dir);
  }
  void add_verified_dir(::flatbuffers::Offset<::flatbuffers::String> verified_dir) {
    fbb_.AddOffset(CheckpointMergeRequest::VT_VERIFIED_DIR, verified_dir);
  }
  void add_output_dir(::flatbuffers::Offset<::flatbuffers::String> output_dir) {
    fbb_.AddOffset(CheckpointMergeRequest::VT_OUTPUT_DIR, output_dir);
  }
  void add_skip_verification(bool skip_verification) {
    fbb_.AddElement<uint8_t>(CheckpointMergeRequest::VT_SKIP_VERIFICATION, static_cast<uint8_t>(skip_verification), 0);
  }
  explicit CheckpointMergeRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CheckpointMergeRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CheckpointMergeRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CheckpointMergeRequest> CreateCheckpointMergeRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> checkpoint_dir = 0,
    ::flatbuffers::Offset<::flatbuffers::String> verified_dir = 0,
    ::flatbuffers::Offset<::flatbuffers::String> output_dir = 0,
    bool skip_verification = false) {
  CheckpointMergeRequestBuilder builder_(_fbb);
  builder_.add_output_dir(output_dir);
  builder_.add_verified_dir(verified_dir);
  builder_.add_checkpoint_dir(checkpoint_dir);
  builder_.add_skip_verification(skip_verification);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CheckpointMergeRequest> CreateCheckpointMergeRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *checkpoint_dir = nullptr,
    const char *verified_dir = nullptr,
    const char *output_dir = nullptr,
    bool skip_verification = false) {
  auto checkpoint_dir__ = checkpoint_dir ? _fbb.CreateString(checkpoint_dir) : 0;
  auto verified_dir__ = verified_dir ? _fbb.CreateString(verified_dir) : 0;
  auto output_dir__ = output_dir ? _fbb.CreateString(output_dir) : 0;
  return GRIMText::Control::CreateCheckpointMergeRequest(
      _fbb,
      checkpoint_dir__,
      verified_dir__,
      output_dir__,
      skip_verification);
}

struct CheckpointMergeResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CheckpointMergeResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUCCESS = 4,
    VT_MESSAGE = 6,
    VT_ERROR = 8,
    VT_CHECKPOINT_ENTRIES = 10,
    VT_VERIFIED_ENTRIES = 12,
    VT_FINAL_ENTRIES = 14,
    VT_OUTPUT_GRMT_PATH = 16
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  const ::flatbuffers::String *error() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR);
  }
  int32_t checkpoint_entries() const {
    return GetField<int32_t>(VT_CHECKPOINT_ENTRIES, 0);
  }
  int32_t verified_entries() const {
    return GetField<int32_t>(VT_VERIFIED_ENTRIES, 0);
  }
  int32_t final_entries() const {
    return GetField<int32_t>(VT_FINAL_ENTRIES, 0);
  }
  const ::flatbuffers::String *output_grmt_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OUTPUT_GRMT_PATH);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_ERROR) &&
           verifier.VerifyString(error()) &&
           VerifyField<int32_t>(verifier, VT_CHECKPOINT_ENTRIES, 4) &&
           VerifyField<int32_t>(verifier, VT_VERIFIED_ENTRIES, 4) &&
           VerifyField<int32_t>(verifier, VT_FINAL_ENTRIES, 4) &&
           VerifyOffset(verifier, VT_OUTPUT_GRMT_PATH) &&
           verifier.VerifyString(output_grmt_path()) &&
           verifier.EndTable();
  }
};

struct CheckpointMergeResponseBuilder {
  typedef CheckpointMergeResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(CheckpointMergeResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(CheckpointMergeResponse::VT_MESSAGE, message);
  }
  void add_error(::flatbuffers::Offset<::flatbuffers::String> error) {
    fbb_.AddOffset(CheckpointMergeResponse::VT_ERROR, error);
  }
  void add_checkpoint_entries(int32_t checkpoint_entries) {
    fbb_.AddElement<int32_t>(CheckpointMergeResponse::VT_CHECKPOINT_ENTRIES, checkpoint_entries, 0);
  }
  void add_verified_entries(int32_t verified_entries) {
    fbb_.AddElement<int32_t>(CheckpointMergeResponse::VT_VERIFIED_ENTRIES, verified_entries, 0);
  }
  void add_final_entries(int32_t final_entries) {
    fbb_.AddElement<int32_t>(CheckpointMergeResponse::VT_FINAL_ENTRIES, final_entries, 0);
  }
  void add_output_grmt_path(::flatbuffers::Offset<::flatbuffers::String> output_grmt_path) {
    fbb_.AddOffset(CheckpointMergeResponse::VT_OUTPUT_GRMT_PATH, output_grmt_path);
  }
  explicit CheckpointMergeResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CheckpointMergeResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CheckpointMergeResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CheckpointMergeResponse> CreateCheckpointMergeResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error = 0,
    int32_t checkpoint_entries = 0,
    int32_t verified_entries = 0,
    int32_t final_entries = 0,
    ::flatbuffers::Offset<::flatbuffers::String> output_grmt_path = 0) {
  CheckpointMergeResponseBuilder builder_(_fbb);
  builder_.add_output_grmt_path(output_grmt_path);
  builder_.add_final_entries(final_entries);
  builder_.add_verified_entries(verified_entries);
  builder_.add_checkpoint_entries(checkpoint_entries);
  builder_.add_error(error);
  builder_.add_message(message);
  builder_.add_success(success);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CheckpointMergeResponse> CreateCheckpointMergeResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    const char *message = nullptr,
    const char *error = nullptr,
    int32_t checkpoint_entries = 0,
    int32_t verified_entries = 0,
    int32_t final_entries = 0,
    const char *output_grmt_path = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto error__ = error ? _fbb.CreateString(error) : 0;
  auto output_grmt_path__ = output_grmt_path ? _fbb.CreateString(output_grmt_path) : 0;
  return GRIMText::Control::CreateCheckpointMergeResponse(
      _fbb,
      success,
      message__,
      error__,
      checkpoint_entries,
      verified_entries,
      final_entries,
      output_grmt_path__);
}

struct DataCollectionRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DataCollectionRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MODE = 4
  };
  const ::flatbuffers::String *mode() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MODE) &&
           verifier.VerifyString(mode()) &&
           verifier.EndTable();
  }
};

struct DataCollectionRequestBuilder {
  typedef DataCollectionRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mode(::flatbuffers::Offset<::flatbuffers::String> mode) {
    fbb_.AddOffset(DataCollectionRequest::VT_MODE, mode);
  }
  explicit DataCollectionRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DataCollectionRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DataCollectionRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DataCollectionRequest> CreateDataCollectionRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> mode = 0) {
  DataCollectionRequestBuilder builder_(_fbb);
  builder_.add_mode(mode);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DataCollectionRequest> CreateDataCollectionRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *mode = nullptr) {
  auto mode__ = mode ? _fbb.CreateString(mode) : 0;
  return GRIMText::Control::CreateDataCollectionRequest(
      _fbb,
      mode__);
}

struct DataCollectionResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DataCollectionResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUCCESS = 4,
    VT_MESSAGE = 6,
    VT_ERROR = 8
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  const ::flatbuffers::String *error() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_ERROR) &&
           verifier.VerifyString(error()) &&
           verifier.EndTable();
  }
};

struct DataCollectionResponseBuilder {
  typedef DataCollectionResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(DataCollectionResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(DataCollectionResponse::VT_MESSAGE, message);
  }
  void add_error(::flatbuffers::Offset<::flatbuffers::String> error) {
    fbb_.AddOffset(DataCollectionResponse::VT_ERROR, error);
  }
  explicit DataCollectionResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DataCollectionResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DataCollectionResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DataCollectionResponse> CreateDataCollectionResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error = 0) {
  DataCollectionResponseBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_message(message);
  builder_.add_success(success);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DataCollectionResponse> CreateDataCollectionResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    const char *message = nullptr,
    const char *error = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto error__ = error ? _fbb.CreateString(error) : 0;
  return GRIMText::Control::CreateDataCollectionResponse(
      _fbb,
      success,
      message__,
      error__);
}

struct ServerShutdownRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerShutdownRequestBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct ServerShutdownRequestBuilder {
  typedef ServerShutdownRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ServerShutdownRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerShutdownRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerShutdownRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerShutdownRequest> CreateServerShutdownRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ServerShutdownRequestBuilder builder_(_fbb);
  return builder_.Finish();
}

struct ServerShutdownResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerShutdownResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUCCESS = 4,
    VT_MESSAGE = 6
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
};

struct ServerShutdownResponseBuilder {
  typedef ServerShutdownResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(ServerShutdownResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(ServerShutdownResponse::VT_MESSAGE, message);
  }
  explicit ServerShutdownResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerShutdownResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerShutdownResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerShutdownResponse> CreateServerShutdownResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  ServerShutdownResponseBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_success(success);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ServerShutdownResponse> CreateServerShutdownResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return GRIMText::Control::CreateServerShutdownResponse(
      _fbb,
      success,
      message__);
}

inline const GRIMText::Control::StatusResponse *GetStatusResponse(const void *buf) {
  return ::flatbuffers::GetRoot<GRIMText::Control::StatusResponse>(buf);
}

inline const GRIMText::Control::StatusResponse *GetSizePrefixedStatusResponse(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GRIMText::Control::StatusResponse>(buf);
}

inline bool VerifyStatusResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GRIMText::Control::StatusResponse>(nullptr);
}

inline bool VerifySizePrefixedStatusResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GRIMText::Control::StatusResponse>(nullptr);
}

inline void FinishStatusResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIMText::Control::StatusResponse> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedStatusResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIMText::Control::StatusResponse> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Control
}  // namespace GRIMText

#endif  // FLATBUFFERS_GENERATED_TRAININGCONTROL_GRIMTEXT_CONTROL_H_
