// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GRIMEMBEDDINGWEIGHTS_GRIMEMBEDDING_H_
#define FLATBUFFERS_GENERATED_GRIMEMBEDDINGWEIGHTS_GRIMEMBEDDING_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace GRIMEmbedding {

struct TrainingMetadata;
struct TrainingMetadataBuilder;

struct ModelConfig;
struct ModelConfigBuilder;

struct EmbeddingStats;
struct EmbeddingStatsBuilder;

struct EmbeddingWeights;
struct EmbeddingWeightsBuilder;

struct PositionalWeights;
struct PositionalWeightsBuilder;

struct LayerNormParams;
struct LayerNormParamsBuilder;

struct VocabMetadata;
struct VocabMetadataBuilder;

struct ChecksumData;
struct ChecksumDataBuilder;

struct EmbeddingModel;
struct EmbeddingModelBuilder;

enum CompressionType : int8_t {
  CompressionType_None = 0,
  CompressionType_Zlib = 1,
  CompressionType_Zstd = 2,
  CompressionType_LZ4 = 3,
  CompressionType_MIN = CompressionType_None,
  CompressionType_MAX = CompressionType_LZ4
};

inline const CompressionType (&EnumValuesCompressionType())[4] {
  static const CompressionType values[] = {
    CompressionType_None,
    CompressionType_Zlib,
    CompressionType_Zstd,
    CompressionType_LZ4
  };
  return values;
}

inline const char * const *EnumNamesCompressionType() {
  static const char * const names[5] = {
    "None",
    "Zlib",
    "Zstd",
    "LZ4",
    nullptr
  };
  return names;
}

inline const char *EnumNameCompressionType(CompressionType e) {
  if (::flatbuffers::IsOutRange(e, CompressionType_None, CompressionType_LZ4)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCompressionType()[index];
}

enum QuantizationType : int8_t {
  QuantizationType_None = 0,
  QuantizationType_INT8 = 1,
  QuantizationType_INT16 = 2,
  QuantizationType_FP16 = 3,
  QuantizationType_MIN = QuantizationType_None,
  QuantizationType_MAX = QuantizationType_FP16
};

inline const QuantizationType (&EnumValuesQuantizationType())[4] {
  static const QuantizationType values[] = {
    QuantizationType_None,
    QuantizationType_INT8,
    QuantizationType_INT16,
    QuantizationType_FP16
  };
  return values;
}

inline const char * const *EnumNamesQuantizationType() {
  static const char * const names[5] = {
    "None",
    "INT8",
    "INT16",
    "FP16",
    nullptr
  };
  return names;
}

inline const char *EnumNameQuantizationType(QuantizationType e) {
  if (::flatbuffers::IsOutRange(e, QuantizationType_None, QuantizationType_FP16)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesQuantizationType()[index];
}

struct TrainingMetadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrainingMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OPTIMIZER = 4,
    VT_LEARNING_RATE = 6,
    VT_BATCH_SIZE = 8,
    VT_TRAINING_STEPS = 10,
    VT_FINAL_LOSS = 12,
    VT_GRADIENT_NORM = 14,
    VT_TIMESTAMP = 16,
    VT_TRAINING_DURATION_SECONDS = 18
  };
  const ::flatbuffers::String *optimizer() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OPTIMIZER);
  }
  float learning_rate() const {
    return GetField<float>(VT_LEARNING_RATE, 0.0f);
  }
  uint32_t batch_size() const {
    return GetField<uint32_t>(VT_BATCH_SIZE, 0);
  }
  uint64_t training_steps() const {
    return GetField<uint64_t>(VT_TRAINING_STEPS, 0);
  }
  float final_loss() const {
    return GetField<float>(VT_FINAL_LOSS, 0.0f);
  }
  float gradient_norm() const {
    return GetField<float>(VT_GRADIENT_NORM, 0.0f);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint64_t training_duration_seconds() const {
    return GetField<uint64_t>(VT_TRAINING_DURATION_SECONDS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_OPTIMIZER) &&
           verifier.VerifyString(optimizer()) &&
           VerifyField<float>(verifier, VT_LEARNING_RATE, 4) &&
           VerifyField<uint32_t>(verifier, VT_BATCH_SIZE, 4) &&
           VerifyField<uint64_t>(verifier, VT_TRAINING_STEPS, 8) &&
           VerifyField<float>(verifier, VT_FINAL_LOSS, 4) &&
           VerifyField<float>(verifier, VT_GRADIENT_NORM, 4) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint64_t>(verifier, VT_TRAINING_DURATION_SECONDS, 8) &&
           verifier.EndTable();
  }
};

struct TrainingMetadataBuilder {
  typedef TrainingMetadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_optimizer(::flatbuffers::Offset<::flatbuffers::String> optimizer) {
    fbb_.AddOffset(TrainingMetadata::VT_OPTIMIZER, optimizer);
  }
  void add_learning_rate(float learning_rate) {
    fbb_.AddElement<float>(TrainingMetadata::VT_LEARNING_RATE, learning_rate, 0.0f);
  }
  void add_batch_size(uint32_t batch_size) {
    fbb_.AddElement<uint32_t>(TrainingMetadata::VT_BATCH_SIZE, batch_size, 0);
  }
  void add_training_steps(uint64_t training_steps) {
    fbb_.AddElement<uint64_t>(TrainingMetadata::VT_TRAINING_STEPS, training_steps, 0);
  }
  void add_final_loss(float final_loss) {
    fbb_.AddElement<float>(TrainingMetadata::VT_FINAL_LOSS, final_loss, 0.0f);
  }
  void add_gradient_norm(float gradient_norm) {
    fbb_.AddElement<float>(TrainingMetadata::VT_GRADIENT_NORM, gradient_norm, 0.0f);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(TrainingMetadata::VT_TIMESTAMP, timestamp, 0);
  }
  void add_training_duration_seconds(uint64_t training_duration_seconds) {
    fbb_.AddElement<uint64_t>(TrainingMetadata::VT_TRAINING_DURATION_SECONDS, training_duration_seconds, 0);
  }
  explicit TrainingMetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrainingMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrainingMetadata>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TrainingMetadata> CreateTrainingMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> optimizer = 0,
    float learning_rate = 0.0f,
    uint32_t batch_size = 0,
    uint64_t training_steps = 0,
    float final_loss = 0.0f,
    float gradient_norm = 0.0f,
    uint64_t timestamp = 0,
    uint64_t training_duration_seconds = 0) {
  TrainingMetadataBuilder builder_(_fbb);
  builder_.add_training_duration_seconds(training_duration_seconds);
  builder_.add_timestamp(timestamp);
  builder_.add_training_steps(training_steps);
  builder_.add_gradient_norm(gradient_norm);
  builder_.add_final_loss(final_loss);
  builder_.add_batch_size(batch_size);
  builder_.add_learning_rate(learning_rate);
  builder_.add_optimizer(optimizer);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TrainingMetadata> CreateTrainingMetadataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *optimizer = nullptr,
    float learning_rate = 0.0f,
    uint32_t batch_size = 0,
    uint64_t training_steps = 0,
    float final_loss = 0.0f,
    float gradient_norm = 0.0f,
    uint64_t timestamp = 0,
    uint64_t training_duration_seconds = 0) {
  auto optimizer__ = optimizer ? _fbb.CreateString(optimizer) : 0;
  return GRIMEmbedding::CreateTrainingMetadata(
      _fbb,
      optimizer__,
      learning_rate,
      batch_size,
      training_steps,
      final_loss,
      gradient_norm,
      timestamp,
      training_duration_seconds);
}

struct ModelConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelConfigBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VOCAB_SIZE = 4,
    VT_EMBEDDING_DIM = 6,
    VT_MAX_SEQUENCE_LENGTH = 8,
    VT_PAD_TOKEN_ID = 10,
    VT_UNK_TOKEN_ID = 12,
    VT_USE_LAYER_NORM = 14,
    VT_USE_POSITIONAL_ENCODING = 16
  };
  uint32_t vocab_size() const {
    return GetField<uint32_t>(VT_VOCAB_SIZE, 0);
  }
  uint32_t embedding_dim() const {
    return GetField<uint32_t>(VT_EMBEDDING_DIM, 0);
  }
  uint32_t max_sequence_length() const {
    return GetField<uint32_t>(VT_MAX_SEQUENCE_LENGTH, 0);
  }
  uint32_t pad_token_id() const {
    return GetField<uint32_t>(VT_PAD_TOKEN_ID, 0);
  }
  uint32_t unk_token_id() const {
    return GetField<uint32_t>(VT_UNK_TOKEN_ID, 0);
  }
  bool use_layer_norm() const {
    return GetField<uint8_t>(VT_USE_LAYER_NORM, 0) != 0;
  }
  bool use_positional_encoding() const {
    return GetField<uint8_t>(VT_USE_POSITIONAL_ENCODING, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VOCAB_SIZE, 4) &&
           VerifyField<uint32_t>(verifier, VT_EMBEDDING_DIM, 4) &&
           VerifyField<uint32_t>(verifier, VT_MAX_SEQUENCE_LENGTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_PAD_TOKEN_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_UNK_TOKEN_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_USE_LAYER_NORM, 1) &&
           VerifyField<uint8_t>(verifier, VT_USE_POSITIONAL_ENCODING, 1) &&
           verifier.EndTable();
  }
};

struct ModelConfigBuilder {
  typedef ModelConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vocab_size(uint32_t vocab_size) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_VOCAB_SIZE, vocab_size, 0);
  }
  void add_embedding_dim(uint32_t embedding_dim) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_EMBEDDING_DIM, embedding_dim, 0);
  }
  void add_max_sequence_length(uint32_t max_sequence_length) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_MAX_SEQUENCE_LENGTH, max_sequence_length, 0);
  }
  void add_pad_token_id(uint32_t pad_token_id) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_PAD_TOKEN_ID, pad_token_id, 0);
  }
  void add_unk_token_id(uint32_t unk_token_id) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_UNK_TOKEN_ID, unk_token_id, 0);
  }
  void add_use_layer_norm(bool use_layer_norm) {
    fbb_.AddElement<uint8_t>(ModelConfig::VT_USE_LAYER_NORM, static_cast<uint8_t>(use_layer_norm), 0);
  }
  void add_use_positional_encoding(bool use_positional_encoding) {
    fbb_.AddElement<uint8_t>(ModelConfig::VT_USE_POSITIONAL_ENCODING, static_cast<uint8_t>(use_positional_encoding), 0);
  }
  explicit ModelConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModelConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModelConfig>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModelConfig> CreateModelConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t vocab_size = 0,
    uint32_t embedding_dim = 0,
    uint32_t max_sequence_length = 0,
    uint32_t pad_token_id = 0,
    uint32_t unk_token_id = 0,
    bool use_layer_norm = false,
    bool use_positional_encoding = false) {
  ModelConfigBuilder builder_(_fbb);
  builder_.add_unk_token_id(unk_token_id);
  builder_.add_pad_token_id(pad_token_id);
  builder_.add_max_sequence_length(max_sequence_length);
  builder_.add_embedding_dim(embedding_dim);
  builder_.add_vocab_size(vocab_size);
  builder_.add_use_positional_encoding(use_positional_encoding);
  builder_.add_use_layer_norm(use_layer_norm);
  return builder_.Finish();
}

struct EmbeddingStats FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EmbeddingStatsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MIN_VALUE = 4,
    VT_MAX_VALUE = 6,
    VT_MEAN_VALUE = 8,
    VT_STD_DEV = 10,
    VT_L2_NORM_MEAN = 12,
    VT_SPARSITY_RATIO = 14
  };
  float min_value() const {
    return GetField<float>(VT_MIN_VALUE, 0.0f);
  }
  float max_value() const {
    return GetField<float>(VT_MAX_VALUE, 0.0f);
  }
  float mean_value() const {
    return GetField<float>(VT_MEAN_VALUE, 0.0f);
  }
  float std_dev() const {
    return GetField<float>(VT_STD_DEV, 0.0f);
  }
  float l2_norm_mean() const {
    return GetField<float>(VT_L2_NORM_MEAN, 0.0f);
  }
  float sparsity_ratio() const {
    return GetField<float>(VT_SPARSITY_RATIO, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_MIN_VALUE, 4) &&
           VerifyField<float>(verifier, VT_MAX_VALUE, 4) &&
           VerifyField<float>(verifier, VT_MEAN_VALUE, 4) &&
           VerifyField<float>(verifier, VT_STD_DEV, 4) &&
           VerifyField<float>(verifier, VT_L2_NORM_MEAN, 4) &&
           VerifyField<float>(verifier, VT_SPARSITY_RATIO, 4) &&
           verifier.EndTable();
  }
};

struct EmbeddingStatsBuilder {
  typedef EmbeddingStats Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_min_value(float min_value) {
    fbb_.AddElement<float>(EmbeddingStats::VT_MIN_VALUE, min_value, 0.0f);
  }
  void add_max_value(float max_value) {
    fbb_.AddElement<float>(EmbeddingStats::VT_MAX_VALUE, max_value, 0.0f);
  }
  void add_mean_value(float mean_value) {
    fbb_.AddElement<float>(EmbeddingStats::VT_MEAN_VALUE, mean_value, 0.0f);
  }
  void add_std_dev(float std_dev) {
    fbb_.AddElement<float>(EmbeddingStats::VT_STD_DEV, std_dev, 0.0f);
  }
  void add_l2_norm_mean(float l2_norm_mean) {
    fbb_.AddElement<float>(EmbeddingStats::VT_L2_NORM_MEAN, l2_norm_mean, 0.0f);
  }
  void add_sparsity_ratio(float sparsity_ratio) {
    fbb_.AddElement<float>(EmbeddingStats::VT_SPARSITY_RATIO, sparsity_ratio, 0.0f);
  }
  explicit EmbeddingStatsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EmbeddingStats> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EmbeddingStats>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EmbeddingStats> CreateEmbeddingStats(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float min_value = 0.0f,
    float max_value = 0.0f,
    float mean_value = 0.0f,
    float std_dev = 0.0f,
    float l2_norm_mean = 0.0f,
    float sparsity_ratio = 0.0f) {
  EmbeddingStatsBuilder builder_(_fbb);
  builder_.add_sparsity_ratio(sparsity_ratio);
  builder_.add_l2_norm_mean(l2_norm_mean);
  builder_.add_std_dev(std_dev);
  builder_.add_mean_value(mean_value);
  builder_.add_max_value(max_value);
  builder_.add_min_value(min_value);
  return builder_.Finish();
}

struct EmbeddingWeights FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EmbeddingWeightsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4,
    VT_COMPRESSED_DATA = 6,
    VT_QUANTIZED_DATA = 8,
    VT_COMPRESSION_TYPE = 10,
    VT_QUANTIZATION_TYPE = 12,
    VT_UNCOMPRESSED_SIZE = 14,
    VT_SCALE = 16,
    VT_ZERO_POINT = 18
  };
  const ::flatbuffers::Vector<float> *data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_DATA);
  }
  const ::flatbuffers::Vector<uint8_t> *compressed_data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_COMPRESSED_DATA);
  }
  const ::flatbuffers::Vector<int8_t> *quantized_data() const {
    return GetPointer<const ::flatbuffers::Vector<int8_t> *>(VT_QUANTIZED_DATA);
  }
  GRIMEmbedding::CompressionType compression_type() const {
    return static_cast<GRIMEmbedding::CompressionType>(GetField<int8_t>(VT_COMPRESSION_TYPE, 0));
  }
  GRIMEmbedding::QuantizationType quantization_type() const {
    return static_cast<GRIMEmbedding::QuantizationType>(GetField<int8_t>(VT_QUANTIZATION_TYPE, 0));
  }
  uint64_t uncompressed_size() const {
    return GetField<uint64_t>(VT_UNCOMPRESSED_SIZE, 0);
  }
  float scale() const {
    return GetField<float>(VT_SCALE, 0.0f);
  }
  int32_t zero_point() const {
    return GetField<int32_t>(VT_ZERO_POINT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyOffset(verifier, VT_COMPRESSED_DATA) &&
           verifier.VerifyVector(compressed_data()) &&
           VerifyOffset(verifier, VT_QUANTIZED_DATA) &&
           verifier.VerifyVector(quantized_data()) &&
           VerifyField<int8_t>(verifier, VT_COMPRESSION_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_QUANTIZATION_TYPE, 1) &&
           VerifyField<uint64_t>(verifier, VT_UNCOMPRESSED_SIZE, 8) &&
           VerifyField<float>(verifier, VT_SCALE, 4) &&
           VerifyField<int32_t>(verifier, VT_ZERO_POINT, 4) &&
           verifier.EndTable();
  }
};

struct EmbeddingWeightsBuilder {
  typedef EmbeddingWeights Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> data) {
    fbb_.AddOffset(EmbeddingWeights::VT_DATA, data);
  }
  void add_compressed_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> compressed_data) {
    fbb_.AddOffset(EmbeddingWeights::VT_COMPRESSED_DATA, compressed_data);
  }
  void add_quantized_data(::flatbuffers::Offset<::flatbuffers::Vector<int8_t>> quantized_data) {
    fbb_.AddOffset(EmbeddingWeights::VT_QUANTIZED_DATA, quantized_data);
  }
  void add_compression_type(GRIMEmbedding::CompressionType compression_type) {
    fbb_.AddElement<int8_t>(EmbeddingWeights::VT_COMPRESSION_TYPE, static_cast<int8_t>(compression_type), 0);
  }
  void add_quantization_type(GRIMEmbedding::QuantizationType quantization_type) {
    fbb_.AddElement<int8_t>(EmbeddingWeights::VT_QUANTIZATION_TYPE, static_cast<int8_t>(quantization_type), 0);
  }
  void add_uncompressed_size(uint64_t uncompressed_size) {
    fbb_.AddElement<uint64_t>(EmbeddingWeights::VT_UNCOMPRESSED_SIZE, uncompressed_size, 0);
  }
  void add_scale(float scale) {
    fbb_.AddElement<float>(EmbeddingWeights::VT_SCALE, scale, 0.0f);
  }
  void add_zero_point(int32_t zero_point) {
    fbb_.AddElement<int32_t>(EmbeddingWeights::VT_ZERO_POINT, zero_point, 0);
  }
  explicit EmbeddingWeightsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EmbeddingWeights> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EmbeddingWeights>(end);
    fbb_.Required(o, EmbeddingWeights::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<EmbeddingWeights> CreateEmbeddingWeights(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> compressed_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int8_t>> quantized_data = 0,
    GRIMEmbedding::CompressionType compression_type = GRIMEmbedding::CompressionType_None,
    GRIMEmbedding::QuantizationType quantization_type = GRIMEmbedding::QuantizationType_None,
    uint64_t uncompressed_size = 0,
    float scale = 0.0f,
    int32_t zero_point = 0) {
  EmbeddingWeightsBuilder builder_(_fbb);
  builder_.add_uncompressed_size(uncompressed_size);
  builder_.add_zero_point(zero_point);
  builder_.add_scale(scale);
  builder_.add_quantized_data(quantized_data);
  builder_.add_compressed_data(compressed_data);
  builder_.add_data(data);
  builder_.add_quantization_type(quantization_type);
  builder_.add_compression_type(compression_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EmbeddingWeights> CreateEmbeddingWeightsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *data = nullptr,
    const std::vector<uint8_t> *compressed_data = nullptr,
    const std::vector<int8_t> *quantized_data = nullptr,
    GRIMEmbedding::CompressionType compression_type = GRIMEmbedding::CompressionType_None,
    GRIMEmbedding::QuantizationType quantization_type = GRIMEmbedding::QuantizationType_None,
    uint64_t uncompressed_size = 0,
    float scale = 0.0f,
    int32_t zero_point = 0) {
  auto data__ = data ? _fbb.CreateVector<float>(*data) : 0;
  auto compressed_data__ = compressed_data ? _fbb.CreateVector<uint8_t>(*compressed_data) : 0;
  auto quantized_data__ = quantized_data ? _fbb.CreateVector<int8_t>(*quantized_data) : 0;
  return GRIMEmbedding::CreateEmbeddingWeights(
      _fbb,
      data__,
      compressed_data__,
      quantized_data__,
      compression_type,
      quantization_type,
      uncompressed_size,
      scale,
      zero_point);
}

struct PositionalWeights FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PositionalWeightsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4,
    VT_MAX_POSITIONS = 6
  };
  const ::flatbuffers::Vector<float> *data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_DATA);
  }
  uint32_t max_positions() const {
    return GetField<uint32_t>(VT_MAX_POSITIONS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyField<uint32_t>(verifier, VT_MAX_POSITIONS, 4) &&
           verifier.EndTable();
  }
};

struct PositionalWeightsBuilder {
  typedef PositionalWeights Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> data) {
    fbb_.AddOffset(PositionalWeights::VT_DATA, data);
  }
  void add_max_positions(uint32_t max_positions) {
    fbb_.AddElement<uint32_t>(PositionalWeights::VT_MAX_POSITIONS, max_positions, 0);
  }
  explicit PositionalWeightsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PositionalWeights> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PositionalWeights>(end);
    fbb_.Required(o, PositionalWeights::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<PositionalWeights> CreatePositionalWeights(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> data = 0,
    uint32_t max_positions = 0) {
  PositionalWeightsBuilder builder_(_fbb);
  builder_.add_max_positions(max_positions);
  builder_.add_data(data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PositionalWeights> CreatePositionalWeightsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *data = nullptr,
    uint32_t max_positions = 0) {
  auto data__ = data ? _fbb.CreateVector<float>(*data) : 0;
  return GRIMEmbedding::CreatePositionalWeights(
      _fbb,
      data__,
      max_positions);
}

struct LayerNormParams FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LayerNormParamsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GAMMA = 4,
    VT_BETA = 6,
    VT_EPSILON = 8
  };
  const ::flatbuffers::Vector<float> *gamma() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_GAMMA);
  }
  const ::flatbuffers::Vector<float> *beta() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_BETA);
  }
  float epsilon() const {
    return GetField<float>(VT_EPSILON, 1e-5f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_GAMMA) &&
           verifier.VerifyVector(gamma()) &&
           VerifyOffsetRequired(verifier, VT_BETA) &&
           verifier.VerifyVector(beta()) &&
           VerifyField<float>(verifier, VT_EPSILON, 4) &&
           verifier.EndTable();
  }
};

struct LayerNormParamsBuilder {
  typedef LayerNormParams Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_gamma(::flatbuffers::Offset<::flatbuffers::Vector<float>> gamma) {
    fbb_.AddOffset(LayerNormParams::VT_GAMMA, gamma);
  }
  void add_beta(::flatbuffers::Offset<::flatbuffers::Vector<float>> beta) {
    fbb_.AddOffset(LayerNormParams::VT_BETA, beta);
  }
  void add_epsilon(float epsilon) {
    fbb_.AddElement<float>(LayerNormParams::VT_EPSILON, epsilon, 1e-5f);
  }
  explicit LayerNormParamsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LayerNormParams> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LayerNormParams>(end);
    fbb_.Required(o, LayerNormParams::VT_GAMMA);
    fbb_.Required(o, LayerNormParams::VT_BETA);
    return o;
  }
};

inline ::flatbuffers::Offset<LayerNormParams> CreateLayerNormParams(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> gamma = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> beta = 0,
    float epsilon = 1e-5f) {
  LayerNormParamsBuilder builder_(_fbb);
  builder_.add_epsilon(epsilon);
  builder_.add_beta(beta);
  builder_.add_gamma(gamma);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LayerNormParams> CreateLayerNormParamsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *gamma = nullptr,
    const std::vector<float> *beta = nullptr,
    float epsilon = 1e-5f) {
  auto gamma__ = gamma ? _fbb.CreateVector<float>(*gamma) : 0;
  auto beta__ = beta ? _fbb.CreateVector<float>(*beta) : 0;
  return GRIMEmbedding::CreateLayerNormParams(
      _fbb,
      gamma__,
      beta__,
      epsilon);
}

struct VocabMetadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VocabMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOKEN_STRINGS = 4,
    VT_TOKEN_FREQUENCIES = 6,
    VT_SPECIAL_TOKENS = 8
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *token_strings() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_TOKEN_STRINGS);
  }
  const ::flatbuffers::Vector<uint64_t> *token_frequencies() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_TOKEN_FREQUENCIES);
  }
  const ::flatbuffers::Vector<uint32_t> *special_tokens() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_SPECIAL_TOKENS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TOKEN_STRINGS) &&
           verifier.VerifyVector(token_strings()) &&
           verifier.VerifyVectorOfStrings(token_strings()) &&
           VerifyOffset(verifier, VT_TOKEN_FREQUENCIES) &&
           verifier.VerifyVector(token_frequencies()) &&
           VerifyOffset(verifier, VT_SPECIAL_TOKENS) &&
           verifier.VerifyVector(special_tokens()) &&
           verifier.EndTable();
  }
};

struct VocabMetadataBuilder {
  typedef VocabMetadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_token_strings(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> token_strings) {
    fbb_.AddOffset(VocabMetadata::VT_TOKEN_STRINGS, token_strings);
  }
  void add_token_frequencies(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> token_frequencies) {
    fbb_.AddOffset(VocabMetadata::VT_TOKEN_FREQUENCIES, token_frequencies);
  }
  void add_special_tokens(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> special_tokens) {
    fbb_.AddOffset(VocabMetadata::VT_SPECIAL_TOKENS, special_tokens);
  }
  explicit VocabMetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VocabMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VocabMetadata>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VocabMetadata> CreateVocabMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> token_strings = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> token_frequencies = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> special_tokens = 0) {
  VocabMetadataBuilder builder_(_fbb);
  builder_.add_special_tokens(special_tokens);
  builder_.add_token_frequencies(token_frequencies);
  builder_.add_token_strings(token_strings);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VocabMetadata> CreateVocabMetadataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *token_strings = nullptr,
    const std::vector<uint64_t> *token_frequencies = nullptr,
    const std::vector<uint32_t> *special_tokens = nullptr) {
  auto token_strings__ = token_strings ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*token_strings) : 0;
  auto token_frequencies__ = token_frequencies ? _fbb.CreateVector<uint64_t>(*token_frequencies) : 0;
  auto special_tokens__ = special_tokens ? _fbb.CreateVector<uint32_t>(*special_tokens) : 0;
  return GRIMEmbedding::CreateVocabMetadata(
      _fbb,
      token_strings__,
      token_frequencies__,
      special_tokens__);
}

struct ChecksumData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChecksumDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CRC32 = 4,
    VT_XXHASH64 = 6,
    VT_SHA256 = 8
  };
  uint32_t crc32() const {
    return GetField<uint32_t>(VT_CRC32, 0);
  }
  uint64_t xxhash64() const {
    return GetField<uint64_t>(VT_XXHASH64, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *sha256() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_SHA256);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CRC32, 4) &&
           VerifyField<uint64_t>(verifier, VT_XXHASH64, 8) &&
           VerifyOffset(verifier, VT_SHA256) &&
           verifier.VerifyVector(sha256()) &&
           verifier.EndTable();
  }
};

struct ChecksumDataBuilder {
  typedef ChecksumData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_crc32(uint32_t crc32) {
    fbb_.AddElement<uint32_t>(ChecksumData::VT_CRC32, crc32, 0);
  }
  void add_xxhash64(uint64_t xxhash64) {
    fbb_.AddElement<uint64_t>(ChecksumData::VT_XXHASH64, xxhash64, 0);
  }
  void add_sha256(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> sha256) {
    fbb_.AddOffset(ChecksumData::VT_SHA256, sha256);
  }
  explicit ChecksumDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ChecksumData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ChecksumData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ChecksumData> CreateChecksumData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t crc32 = 0,
    uint64_t xxhash64 = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> sha256 = 0) {
  ChecksumDataBuilder builder_(_fbb);
  builder_.add_xxhash64(xxhash64);
  builder_.add_sha256(sha256);
  builder_.add_crc32(crc32);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ChecksumData> CreateChecksumDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t crc32 = 0,
    uint64_t xxhash64 = 0,
    const std::vector<uint8_t> *sha256 = nullptr) {
  auto sha256__ = sha256 ? _fbb.CreateVector<uint8_t>(*sha256) : 0;
  return GRIMEmbedding::CreateChecksumData(
      _fbb,
      crc32,
      xxhash64,
      sha256__);
}

struct EmbeddingModel FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EmbeddingModelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_MODEL_NAME = 6,
    VT_MODEL_CONFIG = 8,
    VT_EMBEDDING_WEIGHTS = 10,
    VT_POSITIONAL_WEIGHTS = 12,
    VT_LAYER_NORM_PARAMS = 14,
    VT_VOCAB_METADATA = 16,
    VT_TRAINING_METADATA = 18,
    VT_STATS = 20,
    VT_CHECKSUM = 22,
    VT_CREATION_TIMESTAMP = 24,
    VT_CUSTOM_METADATA = 26
  };
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const ::flatbuffers::String *model_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODEL_NAME);
  }
  const GRIMEmbedding::ModelConfig *model_config() const {
    return GetPointer<const GRIMEmbedding::ModelConfig *>(VT_MODEL_CONFIG);
  }
  const GRIMEmbedding::EmbeddingWeights *embedding_weights() const {
    return GetPointer<const GRIMEmbedding::EmbeddingWeights *>(VT_EMBEDDING_WEIGHTS);
  }
  const GRIMEmbedding::PositionalWeights *positional_weights() const {
    return GetPointer<const GRIMEmbedding::PositionalWeights *>(VT_POSITIONAL_WEIGHTS);
  }
  const GRIMEmbedding::LayerNormParams *layer_norm_params() const {
    return GetPointer<const GRIMEmbedding::LayerNormParams *>(VT_LAYER_NORM_PARAMS);
  }
  const GRIMEmbedding::VocabMetadata *vocab_metadata() const {
    return GetPointer<const GRIMEmbedding::VocabMetadata *>(VT_VOCAB_METADATA);
  }
  const GRIMEmbedding::TrainingMetadata *training_metadata() const {
    return GetPointer<const GRIMEmbedding::TrainingMetadata *>(VT_TRAINING_METADATA);
  }
  const GRIMEmbedding::EmbeddingStats *stats() const {
    return GetPointer<const GRIMEmbedding::EmbeddingStats *>(VT_STATS);
  }
  const GRIMEmbedding::ChecksumData *checksum() const {
    return GetPointer<const GRIMEmbedding::ChecksumData *>(VT_CHECKSUM);
  }
  uint64_t creation_timestamp() const {
    return GetField<uint64_t>(VT_CREATION_TIMESTAMP, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *custom_metadata() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CUSTOM_METADATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_MODEL_NAME) &&
           verifier.VerifyString(model_name()) &&
           VerifyOffset(verifier, VT_MODEL_CONFIG) &&
           verifier.VerifyTable(model_config()) &&
           VerifyOffset(verifier, VT_EMBEDDING_WEIGHTS) &&
           verifier.VerifyTable(embedding_weights()) &&
           VerifyOffset(verifier, VT_POSITIONAL_WEIGHTS) &&
           verifier.VerifyTable(positional_weights()) &&
           VerifyOffset(verifier, VT_LAYER_NORM_PARAMS) &&
           verifier.VerifyTable(layer_norm_params()) &&
           VerifyOffset(verifier, VT_VOCAB_METADATA) &&
           verifier.VerifyTable(vocab_metadata()) &&
           VerifyOffset(verifier, VT_TRAINING_METADATA) &&
           verifier.VerifyTable(training_metadata()) &&
           VerifyOffset(verifier, VT_STATS) &&
           verifier.VerifyTable(stats()) &&
           VerifyOffset(verifier, VT_CHECKSUM) &&
           verifier.VerifyTable(checksum()) &&
           VerifyField<uint64_t>(verifier, VT_CREATION_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_CUSTOM_METADATA) &&
           verifier.VerifyVector(custom_metadata()) &&
           verifier.EndTable();
  }
};

struct EmbeddingModelBuilder {
  typedef EmbeddingModel Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(EmbeddingModel::VT_VERSION, version, 0);
  }
  void add_model_name(::flatbuffers::Offset<::flatbuffers::String> model_name) {
    fbb_.AddOffset(EmbeddingModel::VT_MODEL_NAME, model_name);
  }
  void add_model_config(::flatbuffers::Offset<GRIMEmbedding::ModelConfig> model_config) {
    fbb_.AddOffset(EmbeddingModel::VT_MODEL_CONFIG, model_config);
  }
  void add_embedding_weights(::flatbuffers::Offset<GRIMEmbedding::EmbeddingWeights> embedding_weights) {
    fbb_.AddOffset(EmbeddingModel::VT_EMBEDDING_WEIGHTS, embedding_weights);
  }
  void add_positional_weights(::flatbuffers::Offset<GRIMEmbedding::PositionalWeights> positional_weights) {
    fbb_.AddOffset(EmbeddingModel::VT_POSITIONAL_WEIGHTS, positional_weights);
  }
  void add_layer_norm_params(::flatbuffers::Offset<GRIMEmbedding::LayerNormParams> layer_norm_params) {
    fbb_.AddOffset(EmbeddingModel::VT_LAYER_NORM_PARAMS, layer_norm_params);
  }
  void add_vocab_metadata(::flatbuffers::Offset<GRIMEmbedding::VocabMetadata> vocab_metadata) {
    fbb_.AddOffset(EmbeddingModel::VT_VOCAB_METADATA, vocab_metadata);
  }
  void add_training_metadata(::flatbuffers::Offset<GRIMEmbedding::TrainingMetadata> training_metadata) {
    fbb_.AddOffset(EmbeddingModel::VT_TRAINING_METADATA, training_metadata);
  }
  void add_stats(::flatbuffers::Offset<GRIMEmbedding::EmbeddingStats> stats) {
    fbb_.AddOffset(EmbeddingModel::VT_STATS, stats);
  }
  void add_checksum(::flatbuffers::Offset<GRIMEmbedding::ChecksumData> checksum) {
    fbb_.AddOffset(EmbeddingModel::VT_CHECKSUM, checksum);
  }
  void add_creation_timestamp(uint64_t creation_timestamp) {
    fbb_.AddElement<uint64_t>(EmbeddingModel::VT_CREATION_TIMESTAMP, creation_timestamp, 0);
  }
  void add_custom_metadata(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> custom_metadata) {
    fbb_.AddOffset(EmbeddingModel::VT_CUSTOM_METADATA, custom_metadata);
  }
  explicit EmbeddingModelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EmbeddingModel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EmbeddingModel>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EmbeddingModel> CreateEmbeddingModel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> model_name = 0,
    ::flatbuffers::Offset<GRIMEmbedding::ModelConfig> model_config = 0,
    ::flatbuffers::Offset<GRIMEmbedding::EmbeddingWeights> embedding_weights = 0,
    ::flatbuffers::Offset<GRIMEmbedding::PositionalWeights> positional_weights = 0,
    ::flatbuffers::Offset<GRIMEmbedding::LayerNormParams> layer_norm_params = 0,
    ::flatbuffers::Offset<GRIMEmbedding::VocabMetadata> vocab_metadata = 0,
    ::flatbuffers::Offset<GRIMEmbedding::TrainingMetadata> training_metadata = 0,
    ::flatbuffers::Offset<GRIMEmbedding::EmbeddingStats> stats = 0,
    ::flatbuffers::Offset<GRIMEmbedding::ChecksumData> checksum = 0,
    uint64_t creation_timestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> custom_metadata = 0) {
  EmbeddingModelBuilder builder_(_fbb);
  builder_.add_creation_timestamp(creation_timestamp);
  builder_.add_custom_metadata(custom_metadata);
  builder_.add_checksum(checksum);
  builder_.add_stats(stats);
  builder_.add_training_metadata(training_metadata);
  builder_.add_vocab_metadata(vocab_metadata);
  builder_.add_layer_norm_params(layer_norm_params);
  builder_.add_positional_weights(positional_weights);
  builder_.add_embedding_weights(embedding_weights);
  builder_.add_model_config(model_config);
  builder_.add_model_name(model_name);
  builder_.add_version(version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EmbeddingModel> CreateEmbeddingModelDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0,
    const char *model_name = nullptr,
    ::flatbuffers::Offset<GRIMEmbedding::ModelConfig> model_config = 0,
    ::flatbuffers::Offset<GRIMEmbedding::EmbeddingWeights> embedding_weights = 0,
    ::flatbuffers::Offset<GRIMEmbedding::PositionalWeights> positional_weights = 0,
    ::flatbuffers::Offset<GRIMEmbedding::LayerNormParams> layer_norm_params = 0,
    ::flatbuffers::Offset<GRIMEmbedding::VocabMetadata> vocab_metadata = 0,
    ::flatbuffers::Offset<GRIMEmbedding::TrainingMetadata> training_metadata = 0,
    ::flatbuffers::Offset<GRIMEmbedding::EmbeddingStats> stats = 0,
    ::flatbuffers::Offset<GRIMEmbedding::ChecksumData> checksum = 0,
    uint64_t creation_timestamp = 0,
    const std::vector<uint8_t> *custom_metadata = nullptr) {
  auto model_name__ = model_name ? _fbb.CreateString(model_name) : 0;
  auto custom_metadata__ = custom_metadata ? _fbb.CreateVector<uint8_t>(*custom_metadata) : 0;
  return GRIMEmbedding::CreateEmbeddingModel(
      _fbb,
      version,
      model_name__,
      model_config,
      embedding_weights,
      positional_weights,
      layer_norm_params,
      vocab_metadata,
      training_metadata,
      stats,
      checksum,
      creation_timestamp,
      custom_metadata__);
}

inline const GRIMEmbedding::EmbeddingModel *GetEmbeddingModel(const void *buf) {
  return ::flatbuffers::GetRoot<GRIMEmbedding::EmbeddingModel>(buf);
}

inline const GRIMEmbedding::EmbeddingModel *GetSizePrefixedEmbeddingModel(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GRIMEmbedding::EmbeddingModel>(buf);
}

inline const char *EmbeddingModelIdentifier() {
  return "GREM";
}

inline bool EmbeddingModelBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, EmbeddingModelIdentifier());
}

inline bool SizePrefixedEmbeddingModelBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, EmbeddingModelIdentifier(), true);
}

inline bool VerifyEmbeddingModelBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GRIMEmbedding::EmbeddingModel>(EmbeddingModelIdentifier());
}

inline bool VerifySizePrefixedEmbeddingModelBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GRIMEmbedding::EmbeddingModel>(EmbeddingModelIdentifier());
}

inline const char *EmbeddingModelExtension() {
  return "grem";
}

inline void FinishEmbeddingModelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIMEmbedding::EmbeddingModel> root) {
  fbb.Finish(root, EmbeddingModelIdentifier());
}

inline void FinishSizePrefixedEmbeddingModelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIMEmbedding::EmbeddingModel> root) {
  fbb.FinishSizePrefixed(root, EmbeddingModelIdentifier());
}

}  // namespace GRIMEmbedding

#endif  // FLATBUFFERS_GENERATED_GRIMEMBEDDINGWEIGHTS_GRIMEMBEDDING_H_
