// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GRIMTRANSFORMERMODEL_GRIMTRANSFORMER_H_
#define FLATBUFFERS_GENERATED_GRIMTRANSFORMERMODEL_GRIMTRANSFORMER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace GRIMTransformer {

struct Matrix;
struct MatrixBuilder;

struct Vector;
struct VectorBuilder;

struct RMSNormWeights;
struct RMSNormWeightsBuilder;

struct AttentionWeights;
struct AttentionWeightsBuilder;

struct FFNWeights;
struct FFNWeightsBuilder;

struct EncoderLayerWeights;
struct EncoderLayerWeightsBuilder;

struct EmbeddingWeights;
struct EmbeddingWeightsBuilder;

struct LMHeadWeights;
struct LMHeadWeightsBuilder;

struct NumericHeadWeights;
struct NumericHeadWeightsBuilder;

struct ScratchBlockWeights;
struct ScratchBlockWeightsBuilder;

struct ModelConfig;
struct ModelConfigBuilder;

struct LossWeightingWeights;
struct LossWeightingWeightsBuilder;

struct TrainingMetadata;
struct TrainingMetadataBuilder;

struct TransformerModel;
struct TransformerModelBuilder;

enum PositionalEncodingType : uint8_t {
  PositionalEncodingType_NONE = 0,
  PositionalEncodingType_ALIBI = 1,
  PositionalEncodingType_ROPE = 2,
  PositionalEncodingType_ALIBI_ROPE = 3,
  PositionalEncodingType_MIN = PositionalEncodingType_NONE,
  PositionalEncodingType_MAX = PositionalEncodingType_ALIBI_ROPE
};

inline const PositionalEncodingType (&EnumValuesPositionalEncodingType())[4] {
  static const PositionalEncodingType values[] = {
    PositionalEncodingType_NONE,
    PositionalEncodingType_ALIBI,
    PositionalEncodingType_ROPE,
    PositionalEncodingType_ALIBI_ROPE
  };
  return values;
}

inline const char * const *EnumNamesPositionalEncodingType() {
  static const char * const names[5] = {
    "NONE",
    "ALIBI",
    "ROPE",
    "ALIBI_ROPE",
    nullptr
  };
  return names;
}

inline const char *EnumNamePositionalEncodingType(PositionalEncodingType e) {
  if (::flatbuffers::IsOutRange(e, PositionalEncodingType_NONE, PositionalEncodingType_ALIBI_ROPE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPositionalEncodingType()[index];
}

struct Matrix FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MatrixBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4,
    VT_ROWS = 6,
    VT_COLS = 8
  };
  const ::flatbuffers::Vector<float> *data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_DATA);
  }
  uint32_t rows() const {
    return GetField<uint32_t>(VT_ROWS, 0);
  }
  uint32_t cols() const {
    return GetField<uint32_t>(VT_COLS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyField<uint32_t>(verifier, VT_ROWS, 4) &&
           VerifyField<uint32_t>(verifier, VT_COLS, 4) &&
           verifier.EndTable();
  }
};

struct MatrixBuilder {
  typedef Matrix Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> data) {
    fbb_.AddOffset(Matrix::VT_DATA, data);
  }
  void add_rows(uint32_t rows) {
    fbb_.AddElement<uint32_t>(Matrix::VT_ROWS, rows, 0);
  }
  void add_cols(uint32_t cols) {
    fbb_.AddElement<uint32_t>(Matrix::VT_COLS, cols, 0);
  }
  explicit MatrixBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Matrix> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Matrix>(end);
    fbb_.Required(o, Matrix::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<Matrix> CreateMatrix(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> data = 0,
    uint32_t rows = 0,
    uint32_t cols = 0) {
  MatrixBuilder builder_(_fbb);
  builder_.add_cols(cols);
  builder_.add_rows(rows);
  builder_.add_data(data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Matrix> CreateMatrixDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *data = nullptr,
    uint32_t rows = 0,
    uint32_t cols = 0) {
  auto data__ = data ? _fbb.CreateVector<float>(*data) : 0;
  return GRIMTransformer::CreateMatrix(
      _fbb,
      data__,
      rows,
      cols);
}

struct Vector FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VectorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4
  };
  const ::flatbuffers::Vector<float> *data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
};

struct VectorBuilder {
  typedef Vector Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> data) {
    fbb_.AddOffset(Vector::VT_DATA, data);
  }
  explicit VectorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vector> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vector>(end);
    fbb_.Required(o, Vector::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<Vector> CreateVector(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> data = 0) {
  VectorBuilder builder_(_fbb);
  builder_.add_data(data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Vector> CreateVectorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<float>(*data) : 0;
  return GRIMTransformer::CreateVector(
      _fbb,
      data__);
}

struct RMSNormWeights FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RMSNormWeightsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GAMMA = 4,
    VT_EPSILON = 6
  };
  const ::flatbuffers::Vector<float> *gamma() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_GAMMA);
  }
  float epsilon() const {
    return GetField<float>(VT_EPSILON, 1e-5f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_GAMMA) &&
           verifier.VerifyVector(gamma()) &&
           VerifyField<float>(verifier, VT_EPSILON, 4) &&
           verifier.EndTable();
  }
};

struct RMSNormWeightsBuilder {
  typedef RMSNormWeights Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_gamma(::flatbuffers::Offset<::flatbuffers::Vector<float>> gamma) {
    fbb_.AddOffset(RMSNormWeights::VT_GAMMA, gamma);
  }
  void add_epsilon(float epsilon) {
    fbb_.AddElement<float>(RMSNormWeights::VT_EPSILON, epsilon, 1e-5f);
  }
  explicit RMSNormWeightsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RMSNormWeights> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RMSNormWeights>(end);
    fbb_.Required(o, RMSNormWeights::VT_GAMMA);
    return o;
  }
};

inline ::flatbuffers::Offset<RMSNormWeights> CreateRMSNormWeights(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> gamma = 0,
    float epsilon = 1e-5f) {
  RMSNormWeightsBuilder builder_(_fbb);
  builder_.add_epsilon(epsilon);
  builder_.add_gamma(gamma);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RMSNormWeights> CreateRMSNormWeightsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *gamma = nullptr,
    float epsilon = 1e-5f) {
  auto gamma__ = gamma ? _fbb.CreateVector<float>(*gamma) : 0;
  return GRIMTransformer::CreateRMSNormWeights(
      _fbb,
      gamma__,
      epsilon);
}

struct AttentionWeights FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AttentionWeightsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_W_QKV_DATA = 4,
    VT_B_QKV_DATA = 6,
    VT_W_Q_DATA = 8,
    VT_B_Q_DATA = 10,
    VT_W_K_DATA = 12,
    VT_B_K_DATA = 14,
    VT_W_V_DATA = 16,
    VT_B_V_DATA = 18,
    VT_W_O_DATA = 20,
    VT_B_O_DATA = 22,
    VT_ALPHA_Q = 24,
    VT_ALPHA_K = 26,
    VT_D_MODEL = 28,
    VT_NUM_HEADS = 30,
    VT_NUM_KV_HEADS = 32,
    VT_FUSE_QKV = 34
  };
  const ::flatbuffers::Vector<float> *w_qkv_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_W_QKV_DATA);
  }
  const ::flatbuffers::Vector<float> *b_qkv_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_B_QKV_DATA);
  }
  const ::flatbuffers::Vector<float> *w_q_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_W_Q_DATA);
  }
  const ::flatbuffers::Vector<float> *b_q_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_B_Q_DATA);
  }
  const ::flatbuffers::Vector<float> *w_k_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_W_K_DATA);
  }
  const ::flatbuffers::Vector<float> *b_k_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_B_K_DATA);
  }
  const ::flatbuffers::Vector<float> *w_v_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_W_V_DATA);
  }
  const ::flatbuffers::Vector<float> *b_v_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_B_V_DATA);
  }
  const ::flatbuffers::Vector<float> *w_o_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_W_O_DATA);
  }
  const ::flatbuffers::Vector<float> *b_o_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_B_O_DATA);
  }
  const ::flatbuffers::Vector<float> *alpha_q() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_ALPHA_Q);
  }
  const ::flatbuffers::Vector<float> *alpha_k() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_ALPHA_K);
  }
  uint32_t d_model() const {
    return GetField<uint32_t>(VT_D_MODEL, 0);
  }
  uint32_t num_heads() const {
    return GetField<uint32_t>(VT_NUM_HEADS, 0);
  }
  uint32_t num_kv_heads() const {
    return GetField<uint32_t>(VT_NUM_KV_HEADS, 0);
  }
  bool fuse_qkv() const {
    return GetField<uint8_t>(VT_FUSE_QKV, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_W_QKV_DATA) &&
           verifier.VerifyVector(w_qkv_data()) &&
           VerifyOffset(verifier, VT_B_QKV_DATA) &&
           verifier.VerifyVector(b_qkv_data()) &&
           VerifyOffset(verifier, VT_W_Q_DATA) &&
           verifier.VerifyVector(w_q_data()) &&
           VerifyOffset(verifier, VT_B_Q_DATA) &&
           verifier.VerifyVector(b_q_data()) &&
           VerifyOffset(verifier, VT_W_K_DATA) &&
           verifier.VerifyVector(w_k_data()) &&
           VerifyOffset(verifier, VT_B_K_DATA) &&
           verifier.VerifyVector(b_k_data()) &&
           VerifyOffset(verifier, VT_W_V_DATA) &&
           verifier.VerifyVector(w_v_data()) &&
           VerifyOffset(verifier, VT_B_V_DATA) &&
           verifier.VerifyVector(b_v_data()) &&
           VerifyOffsetRequired(verifier, VT_W_O_DATA) &&
           verifier.VerifyVector(w_o_data()) &&
           VerifyOffsetRequired(verifier, VT_B_O_DATA) &&
           verifier.VerifyVector(b_o_data()) &&
           VerifyOffset(verifier, VT_ALPHA_Q) &&
           verifier.VerifyVector(alpha_q()) &&
           VerifyOffset(verifier, VT_ALPHA_K) &&
           verifier.VerifyVector(alpha_k()) &&
           VerifyField<uint32_t>(verifier, VT_D_MODEL, 4) &&
           VerifyField<uint32_t>(verifier, VT_NUM_HEADS, 4) &&
           VerifyField<uint32_t>(verifier, VT_NUM_KV_HEADS, 4) &&
           VerifyField<uint8_t>(verifier, VT_FUSE_QKV, 1) &&
           verifier.EndTable();
  }
};

struct AttentionWeightsBuilder {
  typedef AttentionWeights Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_w_qkv_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> w_qkv_data) {
    fbb_.AddOffset(AttentionWeights::VT_W_QKV_DATA, w_qkv_data);
  }
  void add_b_qkv_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> b_qkv_data) {
    fbb_.AddOffset(AttentionWeights::VT_B_QKV_DATA, b_qkv_data);
  }
  void add_w_q_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> w_q_data) {
    fbb_.AddOffset(AttentionWeights::VT_W_Q_DATA, w_q_data);
  }
  void add_b_q_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> b_q_data) {
    fbb_.AddOffset(AttentionWeights::VT_B_Q_DATA, b_q_data);
  }
  void add_w_k_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> w_k_data) {
    fbb_.AddOffset(AttentionWeights::VT_W_K_DATA, w_k_data);
  }
  void add_b_k_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> b_k_data) {
    fbb_.AddOffset(AttentionWeights::VT_B_K_DATA, b_k_data);
  }
  void add_w_v_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> w_v_data) {
    fbb_.AddOffset(AttentionWeights::VT_W_V_DATA, w_v_data);
  }
  void add_b_v_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> b_v_data) {
    fbb_.AddOffset(AttentionWeights::VT_B_V_DATA, b_v_data);
  }
  void add_w_o_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> w_o_data) {
    fbb_.AddOffset(AttentionWeights::VT_W_O_DATA, w_o_data);
  }
  void add_b_o_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> b_o_data) {
    fbb_.AddOffset(AttentionWeights::VT_B_O_DATA, b_o_data);
  }
  void add_alpha_q(::flatbuffers::Offset<::flatbuffers::Vector<float>> alpha_q) {
    fbb_.AddOffset(AttentionWeights::VT_ALPHA_Q, alpha_q);
  }
  void add_alpha_k(::flatbuffers::Offset<::flatbuffers::Vector<float>> alpha_k) {
    fbb_.AddOffset(AttentionWeights::VT_ALPHA_K, alpha_k);
  }
  void add_d_model(uint32_t d_model) {
    fbb_.AddElement<uint32_t>(AttentionWeights::VT_D_MODEL, d_model, 0);
  }
  void add_num_heads(uint32_t num_heads) {
    fbb_.AddElement<uint32_t>(AttentionWeights::VT_NUM_HEADS, num_heads, 0);
  }
  void add_num_kv_heads(uint32_t num_kv_heads) {
    fbb_.AddElement<uint32_t>(AttentionWeights::VT_NUM_KV_HEADS, num_kv_heads, 0);
  }
  void add_fuse_qkv(bool fuse_qkv) {
    fbb_.AddElement<uint8_t>(AttentionWeights::VT_FUSE_QKV, static_cast<uint8_t>(fuse_qkv), 0);
  }
  explicit AttentionWeightsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AttentionWeights> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AttentionWeights>(end);
    fbb_.Required(o, AttentionWeights::VT_W_O_DATA);
    fbb_.Required(o, AttentionWeights::VT_B_O_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<AttentionWeights> CreateAttentionWeights(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> w_qkv_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> b_qkv_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> w_q_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> b_q_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> w_k_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> b_k_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> w_v_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> b_v_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> w_o_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> b_o_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> alpha_q = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> alpha_k = 0,
    uint32_t d_model = 0,
    uint32_t num_heads = 0,
    uint32_t num_kv_heads = 0,
    bool fuse_qkv = false) {
  AttentionWeightsBuilder builder_(_fbb);
  builder_.add_num_kv_heads(num_kv_heads);
  builder_.add_num_heads(num_heads);
  builder_.add_d_model(d_model);
  builder_.add_alpha_k(alpha_k);
  builder_.add_alpha_q(alpha_q);
  builder_.add_b_o_data(b_o_data);
  builder_.add_w_o_data(w_o_data);
  builder_.add_b_v_data(b_v_data);
  builder_.add_w_v_data(w_v_data);
  builder_.add_b_k_data(b_k_data);
  builder_.add_w_k_data(w_k_data);
  builder_.add_b_q_data(b_q_data);
  builder_.add_w_q_data(w_q_data);
  builder_.add_b_qkv_data(b_qkv_data);
  builder_.add_w_qkv_data(w_qkv_data);
  builder_.add_fuse_qkv(fuse_qkv);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AttentionWeights> CreateAttentionWeightsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *w_qkv_data = nullptr,
    const std::vector<float> *b_qkv_data = nullptr,
    const std::vector<float> *w_q_data = nullptr,
    const std::vector<float> *b_q_data = nullptr,
    const std::vector<float> *w_k_data = nullptr,
    const std::vector<float> *b_k_data = nullptr,
    const std::vector<float> *w_v_data = nullptr,
    const std::vector<float> *b_v_data = nullptr,
    const std::vector<float> *w_o_data = nullptr,
    const std::vector<float> *b_o_data = nullptr,
    const std::vector<float> *alpha_q = nullptr,
    const std::vector<float> *alpha_k = nullptr,
    uint32_t d_model = 0,
    uint32_t num_heads = 0,
    uint32_t num_kv_heads = 0,
    bool fuse_qkv = false) {
  auto w_qkv_data__ = w_qkv_data ? _fbb.CreateVector<float>(*w_qkv_data) : 0;
  auto b_qkv_data__ = b_qkv_data ? _fbb.CreateVector<float>(*b_qkv_data) : 0;
  auto w_q_data__ = w_q_data ? _fbb.CreateVector<float>(*w_q_data) : 0;
  auto b_q_data__ = b_q_data ? _fbb.CreateVector<float>(*b_q_data) : 0;
  auto w_k_data__ = w_k_data ? _fbb.CreateVector<float>(*w_k_data) : 0;
  auto b_k_data__ = b_k_data ? _fbb.CreateVector<float>(*b_k_data) : 0;
  auto w_v_data__ = w_v_data ? _fbb.CreateVector<float>(*w_v_data) : 0;
  auto b_v_data__ = b_v_data ? _fbb.CreateVector<float>(*b_v_data) : 0;
  auto w_o_data__ = w_o_data ? _fbb.CreateVector<float>(*w_o_data) : 0;
  auto b_o_data__ = b_o_data ? _fbb.CreateVector<float>(*b_o_data) : 0;
  auto alpha_q__ = alpha_q ? _fbb.CreateVector<float>(*alpha_q) : 0;
  auto alpha_k__ = alpha_k ? _fbb.CreateVector<float>(*alpha_k) : 0;
  return GRIMTransformer::CreateAttentionWeights(
      _fbb,
      w_qkv_data__,
      b_qkv_data__,
      w_q_data__,
      b_q_data__,
      w_k_data__,
      b_k_data__,
      w_v_data__,
      b_v_data__,
      w_o_data__,
      b_o_data__,
      alpha_q__,
      alpha_k__,
      d_model,
      num_heads,
      num_kv_heads,
      fuse_qkv);
}

struct FFNWeights FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FFNWeightsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_W1_DATA = 4,
    VT_B1_DATA = 6,
    VT_W2_DATA = 8,
    VT_B2_DATA = 10,
    VT_D_MODEL = 12,
    VT_D_FF = 14
  };
  const ::flatbuffers::Vector<float> *w1_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_W1_DATA);
  }
  const ::flatbuffers::Vector<float> *b1_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_B1_DATA);
  }
  const ::flatbuffers::Vector<float> *w2_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_W2_DATA);
  }
  const ::flatbuffers::Vector<float> *b2_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_B2_DATA);
  }
  uint32_t d_model() const {
    return GetField<uint32_t>(VT_D_MODEL, 0);
  }
  uint32_t d_ff() const {
    return GetField<uint32_t>(VT_D_FF, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_W1_DATA) &&
           verifier.VerifyVector(w1_data()) &&
           VerifyOffsetRequired(verifier, VT_B1_DATA) &&
           verifier.VerifyVector(b1_data()) &&
           VerifyOffsetRequired(verifier, VT_W2_DATA) &&
           verifier.VerifyVector(w2_data()) &&
           VerifyOffsetRequired(verifier, VT_B2_DATA) &&
           verifier.VerifyVector(b2_data()) &&
           VerifyField<uint32_t>(verifier, VT_D_MODEL, 4) &&
           VerifyField<uint32_t>(verifier, VT_D_FF, 4) &&
           verifier.EndTable();
  }
};

struct FFNWeightsBuilder {
  typedef FFNWeights Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_w1_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> w1_data) {
    fbb_.AddOffset(FFNWeights::VT_W1_DATA, w1_data);
  }
  void add_b1_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> b1_data) {
    fbb_.AddOffset(FFNWeights::VT_B1_DATA, b1_data);
  }
  void add_w2_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> w2_data) {
    fbb_.AddOffset(FFNWeights::VT_W2_DATA, w2_data);
  }
  void add_b2_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> b2_data) {
    fbb_.AddOffset(FFNWeights::VT_B2_DATA, b2_data);
  }
  void add_d_model(uint32_t d_model) {
    fbb_.AddElement<uint32_t>(FFNWeights::VT_D_MODEL, d_model, 0);
  }
  void add_d_ff(uint32_t d_ff) {
    fbb_.AddElement<uint32_t>(FFNWeights::VT_D_FF, d_ff, 0);
  }
  explicit FFNWeightsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FFNWeights> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FFNWeights>(end);
    fbb_.Required(o, FFNWeights::VT_W1_DATA);
    fbb_.Required(o, FFNWeights::VT_B1_DATA);
    fbb_.Required(o, FFNWeights::VT_W2_DATA);
    fbb_.Required(o, FFNWeights::VT_B2_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<FFNWeights> CreateFFNWeights(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> w1_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> b1_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> w2_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> b2_data = 0,
    uint32_t d_model = 0,
    uint32_t d_ff = 0) {
  FFNWeightsBuilder builder_(_fbb);
  builder_.add_d_ff(d_ff);
  builder_.add_d_model(d_model);
  builder_.add_b2_data(b2_data);
  builder_.add_w2_data(w2_data);
  builder_.add_b1_data(b1_data);
  builder_.add_w1_data(w1_data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FFNWeights> CreateFFNWeightsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *w1_data = nullptr,
    const std::vector<float> *b1_data = nullptr,
    const std::vector<float> *w2_data = nullptr,
    const std::vector<float> *b2_data = nullptr,
    uint32_t d_model = 0,
    uint32_t d_ff = 0) {
  auto w1_data__ = w1_data ? _fbb.CreateVector<float>(*w1_data) : 0;
  auto b1_data__ = b1_data ? _fbb.CreateVector<float>(*b1_data) : 0;
  auto w2_data__ = w2_data ? _fbb.CreateVector<float>(*w2_data) : 0;
  auto b2_data__ = b2_data ? _fbb.CreateVector<float>(*b2_data) : 0;
  return GRIMTransformer::CreateFFNWeights(
      _fbb,
      w1_data__,
      b1_data__,
      w2_data__,
      b2_data__,
      d_model,
      d_ff);
}

struct EncoderLayerWeights FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EncoderLayerWeightsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ATTENTION = 4,
    VT_FFN = 6,
    VT_RMS1 = 8,
    VT_RMS2 = 10,
    VT_LAYER_SCALE1 = 12,
    VT_LAYER_SCALE2 = 14,
    VT_RMS_POST_ATTN = 16,
    VT_RMS_POST_FFN = 18,
    VT_LAYER_ID = 20
  };
  const GRIMTransformer::AttentionWeights *attention() const {
    return GetPointer<const GRIMTransformer::AttentionWeights *>(VT_ATTENTION);
  }
  const GRIMTransformer::FFNWeights *ffn() const {
    return GetPointer<const GRIMTransformer::FFNWeights *>(VT_FFN);
  }
  const GRIMTransformer::RMSNormWeights *rms1() const {
    return GetPointer<const GRIMTransformer::RMSNormWeights *>(VT_RMS1);
  }
  const GRIMTransformer::RMSNormWeights *rms2() const {
    return GetPointer<const GRIMTransformer::RMSNormWeights *>(VT_RMS2);
  }
  const ::flatbuffers::Vector<float> *layer_scale1() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_LAYER_SCALE1);
  }
  const ::flatbuffers::Vector<float> *layer_scale2() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_LAYER_SCALE2);
  }
  const GRIMTransformer::RMSNormWeights *rms_post_attn() const {
    return GetPointer<const GRIMTransformer::RMSNormWeights *>(VT_RMS_POST_ATTN);
  }
  const GRIMTransformer::RMSNormWeights *rms_post_ffn() const {
    return GetPointer<const GRIMTransformer::RMSNormWeights *>(VT_RMS_POST_FFN);
  }
  uint32_t layer_id() const {
    return GetField<uint32_t>(VT_LAYER_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ATTENTION) &&
           verifier.VerifyTable(attention()) &&
           VerifyOffsetRequired(verifier, VT_FFN) &&
           verifier.VerifyTable(ffn()) &&
           VerifyOffsetRequired(verifier, VT_RMS1) &&
           verifier.VerifyTable(rms1()) &&
           VerifyOffsetRequired(verifier, VT_RMS2) &&
           verifier.VerifyTable(rms2()) &&
           VerifyOffset(verifier, VT_LAYER_SCALE1) &&
           verifier.VerifyVector(layer_scale1()) &&
           VerifyOffset(verifier, VT_LAYER_SCALE2) &&
           verifier.VerifyVector(layer_scale2()) &&
           VerifyOffset(verifier, VT_RMS_POST_ATTN) &&
           verifier.VerifyTable(rms_post_attn()) &&
           VerifyOffset(verifier, VT_RMS_POST_FFN) &&
           verifier.VerifyTable(rms_post_ffn()) &&
           VerifyField<uint32_t>(verifier, VT_LAYER_ID, 4) &&
           verifier.EndTable();
  }
};

struct EncoderLayerWeightsBuilder {
  typedef EncoderLayerWeights Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_attention(::flatbuffers::Offset<GRIMTransformer::AttentionWeights> attention) {
    fbb_.AddOffset(EncoderLayerWeights::VT_ATTENTION, attention);
  }
  void add_ffn(::flatbuffers::Offset<GRIMTransformer::FFNWeights> ffn) {
    fbb_.AddOffset(EncoderLayerWeights::VT_FFN, ffn);
  }
  void add_rms1(::flatbuffers::Offset<GRIMTransformer::RMSNormWeights> rms1) {
    fbb_.AddOffset(EncoderLayerWeights::VT_RMS1, rms1);
  }
  void add_rms2(::flatbuffers::Offset<GRIMTransformer::RMSNormWeights> rms2) {
    fbb_.AddOffset(EncoderLayerWeights::VT_RMS2, rms2);
  }
  void add_layer_scale1(::flatbuffers::Offset<::flatbuffers::Vector<float>> layer_scale1) {
    fbb_.AddOffset(EncoderLayerWeights::VT_LAYER_SCALE1, layer_scale1);
  }
  void add_layer_scale2(::flatbuffers::Offset<::flatbuffers::Vector<float>> layer_scale2) {
    fbb_.AddOffset(EncoderLayerWeights::VT_LAYER_SCALE2, layer_scale2);
  }
  void add_rms_post_attn(::flatbuffers::Offset<GRIMTransformer::RMSNormWeights> rms_post_attn) {
    fbb_.AddOffset(EncoderLayerWeights::VT_RMS_POST_ATTN, rms_post_attn);
  }
  void add_rms_post_ffn(::flatbuffers::Offset<GRIMTransformer::RMSNormWeights> rms_post_ffn) {
    fbb_.AddOffset(EncoderLayerWeights::VT_RMS_POST_FFN, rms_post_ffn);
  }
  void add_layer_id(uint32_t layer_id) {
    fbb_.AddElement<uint32_t>(EncoderLayerWeights::VT_LAYER_ID, layer_id, 0);
  }
  explicit EncoderLayerWeightsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EncoderLayerWeights> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EncoderLayerWeights>(end);
    fbb_.Required(o, EncoderLayerWeights::VT_ATTENTION);
    fbb_.Required(o, EncoderLayerWeights::VT_FFN);
    fbb_.Required(o, EncoderLayerWeights::VT_RMS1);
    fbb_.Required(o, EncoderLayerWeights::VT_RMS2);
    return o;
  }
};

inline ::flatbuffers::Offset<EncoderLayerWeights> CreateEncoderLayerWeights(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<GRIMTransformer::AttentionWeights> attention = 0,
    ::flatbuffers::Offset<GRIMTransformer::FFNWeights> ffn = 0,
    ::flatbuffers::Offset<GRIMTransformer::RMSNormWeights> rms1 = 0,
    ::flatbuffers::Offset<GRIMTransformer::RMSNormWeights> rms2 = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> layer_scale1 = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> layer_scale2 = 0,
    ::flatbuffers::Offset<GRIMTransformer::RMSNormWeights> rms_post_attn = 0,
    ::flatbuffers::Offset<GRIMTransformer::RMSNormWeights> rms_post_ffn = 0,
    uint32_t layer_id = 0) {
  EncoderLayerWeightsBuilder builder_(_fbb);
  builder_.add_layer_id(layer_id);
  builder_.add_rms_post_ffn(rms_post_ffn);
  builder_.add_rms_post_attn(rms_post_attn);
  builder_.add_layer_scale2(layer_scale2);
  builder_.add_layer_scale1(layer_scale1);
  builder_.add_rms2(rms2);
  builder_.add_rms1(rms1);
  builder_.add_ffn(ffn);
  builder_.add_attention(attention);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EncoderLayerWeights> CreateEncoderLayerWeightsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<GRIMTransformer::AttentionWeights> attention = 0,
    ::flatbuffers::Offset<GRIMTransformer::FFNWeights> ffn = 0,
    ::flatbuffers::Offset<GRIMTransformer::RMSNormWeights> rms1 = 0,
    ::flatbuffers::Offset<GRIMTransformer::RMSNormWeights> rms2 = 0,
    const std::vector<float> *layer_scale1 = nullptr,
    const std::vector<float> *layer_scale2 = nullptr,
    ::flatbuffers::Offset<GRIMTransformer::RMSNormWeights> rms_post_attn = 0,
    ::flatbuffers::Offset<GRIMTransformer::RMSNormWeights> rms_post_ffn = 0,
    uint32_t layer_id = 0) {
  auto layer_scale1__ = layer_scale1 ? _fbb.CreateVector<float>(*layer_scale1) : 0;
  auto layer_scale2__ = layer_scale2 ? _fbb.CreateVector<float>(*layer_scale2) : 0;
  return GRIMTransformer::CreateEncoderLayerWeights(
      _fbb,
      attention,
      ffn,
      rms1,
      rms2,
      layer_scale1__,
      layer_scale2__,
      rms_post_attn,
      rms_post_ffn,
      layer_id);
}

struct EmbeddingWeights FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EmbeddingWeightsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOKEN_EMBEDDINGS = 4,
    VT_POSITIONAL_ENCODINGS = 6,
    VT_RMS_GAMMA = 8,
    VT_VOCAB_SIZE = 10,
    VT_D_MODEL = 12,
    VT_MAX_SEQ_LEN = 14,
    VT_USE_RMS_NORM = 16
  };
  const ::flatbuffers::Vector<float> *token_embeddings() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_TOKEN_EMBEDDINGS);
  }
  const ::flatbuffers::Vector<float> *positional_encodings() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_POSITIONAL_ENCODINGS);
  }
  const ::flatbuffers::Vector<float> *rms_gamma() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_RMS_GAMMA);
  }
  uint32_t vocab_size() const {
    return GetField<uint32_t>(VT_VOCAB_SIZE, 0);
  }
  uint32_t d_model() const {
    return GetField<uint32_t>(VT_D_MODEL, 0);
  }
  uint32_t max_seq_len() const {
    return GetField<uint32_t>(VT_MAX_SEQ_LEN, 0);
  }
  bool use_rms_norm() const {
    return GetField<uint8_t>(VT_USE_RMS_NORM, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TOKEN_EMBEDDINGS) &&
           verifier.VerifyVector(token_embeddings()) &&
           VerifyOffset(verifier, VT_POSITIONAL_ENCODINGS) &&
           verifier.VerifyVector(positional_encodings()) &&
           VerifyOffset(verifier, VT_RMS_GAMMA) &&
           verifier.VerifyVector(rms_gamma()) &&
           VerifyField<uint32_t>(verifier, VT_VOCAB_SIZE, 4) &&
           VerifyField<uint32_t>(verifier, VT_D_MODEL, 4) &&
           VerifyField<uint32_t>(verifier, VT_MAX_SEQ_LEN, 4) &&
           VerifyField<uint8_t>(verifier, VT_USE_RMS_NORM, 1) &&
           verifier.EndTable();
  }
};

struct EmbeddingWeightsBuilder {
  typedef EmbeddingWeights Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_token_embeddings(::flatbuffers::Offset<::flatbuffers::Vector<float>> token_embeddings) {
    fbb_.AddOffset(EmbeddingWeights::VT_TOKEN_EMBEDDINGS, token_embeddings);
  }
  void add_positional_encodings(::flatbuffers::Offset<::flatbuffers::Vector<float>> positional_encodings) {
    fbb_.AddOffset(EmbeddingWeights::VT_POSITIONAL_ENCODINGS, positional_encodings);
  }
  void add_rms_gamma(::flatbuffers::Offset<::flatbuffers::Vector<float>> rms_gamma) {
    fbb_.AddOffset(EmbeddingWeights::VT_RMS_GAMMA, rms_gamma);
  }
  void add_vocab_size(uint32_t vocab_size) {
    fbb_.AddElement<uint32_t>(EmbeddingWeights::VT_VOCAB_SIZE, vocab_size, 0);
  }
  void add_d_model(uint32_t d_model) {
    fbb_.AddElement<uint32_t>(EmbeddingWeights::VT_D_MODEL, d_model, 0);
  }
  void add_max_seq_len(uint32_t max_seq_len) {
    fbb_.AddElement<uint32_t>(EmbeddingWeights::VT_MAX_SEQ_LEN, max_seq_len, 0);
  }
  void add_use_rms_norm(bool use_rms_norm) {
    fbb_.AddElement<uint8_t>(EmbeddingWeights::VT_USE_RMS_NORM, static_cast<uint8_t>(use_rms_norm), 0);
  }
  explicit EmbeddingWeightsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EmbeddingWeights> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EmbeddingWeights>(end);
    fbb_.Required(o, EmbeddingWeights::VT_TOKEN_EMBEDDINGS);
    return o;
  }
};

inline ::flatbuffers::Offset<EmbeddingWeights> CreateEmbeddingWeights(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> token_embeddings = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> positional_encodings = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> rms_gamma = 0,
    uint32_t vocab_size = 0,
    uint32_t d_model = 0,
    uint32_t max_seq_len = 0,
    bool use_rms_norm = false) {
  EmbeddingWeightsBuilder builder_(_fbb);
  builder_.add_max_seq_len(max_seq_len);
  builder_.add_d_model(d_model);
  builder_.add_vocab_size(vocab_size);
  builder_.add_rms_gamma(rms_gamma);
  builder_.add_positional_encodings(positional_encodings);
  builder_.add_token_embeddings(token_embeddings);
  builder_.add_use_rms_norm(use_rms_norm);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EmbeddingWeights> CreateEmbeddingWeightsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *token_embeddings = nullptr,
    const std::vector<float> *positional_encodings = nullptr,
    const std::vector<float> *rms_gamma = nullptr,
    uint32_t vocab_size = 0,
    uint32_t d_model = 0,
    uint32_t max_seq_len = 0,
    bool use_rms_norm = false) {
  auto token_embeddings__ = token_embeddings ? _fbb.CreateVector<float>(*token_embeddings) : 0;
  auto positional_encodings__ = positional_encodings ? _fbb.CreateVector<float>(*positional_encodings) : 0;
  auto rms_gamma__ = rms_gamma ? _fbb.CreateVector<float>(*rms_gamma) : 0;
  return GRIMTransformer::CreateEmbeddingWeights(
      _fbb,
      token_embeddings__,
      positional_encodings__,
      rms_gamma__,
      vocab_size,
      d_model,
      max_seq_len,
      use_rms_norm);
}

struct LMHeadWeights FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LMHeadWeightsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROJECTION_DATA = 4,
    VT_BIAS_DATA = 6,
    VT_D_MODEL = 8,
    VT_VOCAB_SIZE = 10,
    VT_TIE_EMBEDDINGS = 12,
    VT_USE_BIAS = 14
  };
  const ::flatbuffers::Vector<float> *projection_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_PROJECTION_DATA);
  }
  const ::flatbuffers::Vector<float> *bias_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_BIAS_DATA);
  }
  uint32_t d_model() const {
    return GetField<uint32_t>(VT_D_MODEL, 0);
  }
  uint32_t vocab_size() const {
    return GetField<uint32_t>(VT_VOCAB_SIZE, 0);
  }
  bool tie_embeddings() const {
    return GetField<uint8_t>(VT_TIE_EMBEDDINGS, 0) != 0;
  }
  bool use_bias() const {
    return GetField<uint8_t>(VT_USE_BIAS, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROJECTION_DATA) &&
           verifier.VerifyVector(projection_data()) &&
           VerifyOffset(verifier, VT_BIAS_DATA) &&
           verifier.VerifyVector(bias_data()) &&
           VerifyField<uint32_t>(verifier, VT_D_MODEL, 4) &&
           VerifyField<uint32_t>(verifier, VT_VOCAB_SIZE, 4) &&
           VerifyField<uint8_t>(verifier, VT_TIE_EMBEDDINGS, 1) &&
           VerifyField<uint8_t>(verifier, VT_USE_BIAS, 1) &&
           verifier.EndTable();
  }
};

struct LMHeadWeightsBuilder {
  typedef LMHeadWeights Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_projection_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> projection_data) {
    fbb_.AddOffset(LMHeadWeights::VT_PROJECTION_DATA, projection_data);
  }
  void add_bias_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> bias_data) {
    fbb_.AddOffset(LMHeadWeights::VT_BIAS_DATA, bias_data);
  }
  void add_d_model(uint32_t d_model) {
    fbb_.AddElement<uint32_t>(LMHeadWeights::VT_D_MODEL, d_model, 0);
  }
  void add_vocab_size(uint32_t vocab_size) {
    fbb_.AddElement<uint32_t>(LMHeadWeights::VT_VOCAB_SIZE, vocab_size, 0);
  }
  void add_tie_embeddings(bool tie_embeddings) {
    fbb_.AddElement<uint8_t>(LMHeadWeights::VT_TIE_EMBEDDINGS, static_cast<uint8_t>(tie_embeddings), 0);
  }
  void add_use_bias(bool use_bias) {
    fbb_.AddElement<uint8_t>(LMHeadWeights::VT_USE_BIAS, static_cast<uint8_t>(use_bias), 0);
  }
  explicit LMHeadWeightsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LMHeadWeights> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LMHeadWeights>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LMHeadWeights> CreateLMHeadWeights(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> projection_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> bias_data = 0,
    uint32_t d_model = 0,
    uint32_t vocab_size = 0,
    bool tie_embeddings = false,
    bool use_bias = false) {
  LMHeadWeightsBuilder builder_(_fbb);
  builder_.add_vocab_size(vocab_size);
  builder_.add_d_model(d_model);
  builder_.add_bias_data(bias_data);
  builder_.add_projection_data(projection_data);
  builder_.add_use_bias(use_bias);
  builder_.add_tie_embeddings(tie_embeddings);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LMHeadWeights> CreateLMHeadWeightsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *projection_data = nullptr,
    const std::vector<float> *bias_data = nullptr,
    uint32_t d_model = 0,
    uint32_t vocab_size = 0,
    bool tie_embeddings = false,
    bool use_bias = false) {
  auto projection_data__ = projection_data ? _fbb.CreateVector<float>(*projection_data) : 0;
  auto bias_data__ = bias_data ? _fbb.CreateVector<float>(*bias_data) : 0;
  return GRIMTransformer::CreateLMHeadWeights(
      _fbb,
      projection_data__,
      bias_data__,
      d_model,
      vocab_size,
      tie_embeddings,
      use_bias);
}

struct NumericHeadWeights FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NumericHeadWeightsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROJECTION_DATA = 4,
    VT_BIAS_DATA = 6,
    VT_D_MODEL = 8,
    VT_USE_BIAS = 10
  };
  const ::flatbuffers::Vector<float> *projection_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_PROJECTION_DATA);
  }
  const ::flatbuffers::Vector<float> *bias_data() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_BIAS_DATA);
  }
  uint32_t d_model() const {
    return GetField<uint32_t>(VT_D_MODEL, 0);
  }
  bool use_bias() const {
    return GetField<uint8_t>(VT_USE_BIAS, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROJECTION_DATA) &&
           verifier.VerifyVector(projection_data()) &&
           VerifyOffset(verifier, VT_BIAS_DATA) &&
           verifier.VerifyVector(bias_data()) &&
           VerifyField<uint32_t>(verifier, VT_D_MODEL, 4) &&
           VerifyField<uint8_t>(verifier, VT_USE_BIAS, 1) &&
           verifier.EndTable();
  }
};

struct NumericHeadWeightsBuilder {
  typedef NumericHeadWeights Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_projection_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> projection_data) {
    fbb_.AddOffset(NumericHeadWeights::VT_PROJECTION_DATA, projection_data);
  }
  void add_bias_data(::flatbuffers::Offset<::flatbuffers::Vector<float>> bias_data) {
    fbb_.AddOffset(NumericHeadWeights::VT_BIAS_DATA, bias_data);
  }
  void add_d_model(uint32_t d_model) {
    fbb_.AddElement<uint32_t>(NumericHeadWeights::VT_D_MODEL, d_model, 0);
  }
  void add_use_bias(bool use_bias) {
    fbb_.AddElement<uint8_t>(NumericHeadWeights::VT_USE_BIAS, static_cast<uint8_t>(use_bias), 0);
  }
  explicit NumericHeadWeightsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NumericHeadWeights> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NumericHeadWeights>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NumericHeadWeights> CreateNumericHeadWeights(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> projection_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> bias_data = 0,
    uint32_t d_model = 0,
    bool use_bias = false) {
  NumericHeadWeightsBuilder builder_(_fbb);
  builder_.add_d_model(d_model);
  builder_.add_bias_data(bias_data);
  builder_.add_projection_data(projection_data);
  builder_.add_use_bias(use_bias);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<NumericHeadWeights> CreateNumericHeadWeightsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *projection_data = nullptr,
    const std::vector<float> *bias_data = nullptr,
    uint32_t d_model = 0,
    bool use_bias = false) {
  auto projection_data__ = projection_data ? _fbb.CreateVector<float>(*projection_data) : 0;
  auto bias_data__ = bias_data ? _fbb.CreateVector<float>(*bias_data) : 0;
  return GRIMTransformer::CreateNumericHeadWeights(
      _fbb,
      projection_data__,
      bias_data__,
      d_model,
      use_bias);
}

struct ScratchBlockWeights FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ScratchBlockWeightsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ATOM_TYPE_EMBEDDINGS = 4,
    VT_ATOM_PROJECTION = 6,
    VT_TEXT_FEATURE_PROJECTION = 8,
    VT_VALUE_EXTRACTION_WEIGHT = 10,
    VT_VALUE_EXTRACTION_BIAS = 12,
    VT_NUM_ATOM_TYPES = 14,
    VT_ATOM_EMBEDDING_DIM = 16,
    VT_D_MODEL = 18,
    VT_ATOM_SCALE = 20,
    VT_ENABLED = 22
  };
  const ::flatbuffers::Vector<float> *atom_type_embeddings() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_ATOM_TYPE_EMBEDDINGS);
  }
  const ::flatbuffers::Vector<float> *atom_projection() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_ATOM_PROJECTION);
  }
  const ::flatbuffers::Vector<float> *text_feature_projection() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_TEXT_FEATURE_PROJECTION);
  }
  const ::flatbuffers::Vector<float> *value_extraction_weight() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_VALUE_EXTRACTION_WEIGHT);
  }
  const ::flatbuffers::Vector<float> *value_extraction_bias() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_VALUE_EXTRACTION_BIAS);
  }
  uint32_t num_atom_types() const {
    return GetField<uint32_t>(VT_NUM_ATOM_TYPES, 0);
  }
  uint32_t atom_embedding_dim() const {
    return GetField<uint32_t>(VT_ATOM_EMBEDDING_DIM, 0);
  }
  uint32_t d_model() const {
    return GetField<uint32_t>(VT_D_MODEL, 0);
  }
  float atom_scale() const {
    return GetField<float>(VT_ATOM_SCALE, 0.0f);
  }
  bool enabled() const {
    return GetField<uint8_t>(VT_ENABLED, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ATOM_TYPE_EMBEDDINGS) &&
           verifier.VerifyVector(atom_type_embeddings()) &&
           VerifyOffset(verifier, VT_ATOM_PROJECTION) &&
           verifier.VerifyVector(atom_projection()) &&
           VerifyOffset(verifier, VT_TEXT_FEATURE_PROJECTION) &&
           verifier.VerifyVector(text_feature_projection()) &&
           VerifyOffset(verifier, VT_VALUE_EXTRACTION_WEIGHT) &&
           verifier.VerifyVector(value_extraction_weight()) &&
           VerifyOffset(verifier, VT_VALUE_EXTRACTION_BIAS) &&
           verifier.VerifyVector(value_extraction_bias()) &&
           VerifyField<uint32_t>(verifier, VT_NUM_ATOM_TYPES, 4) &&
           VerifyField<uint32_t>(verifier, VT_ATOM_EMBEDDING_DIM, 4) &&
           VerifyField<uint32_t>(verifier, VT_D_MODEL, 4) &&
           VerifyField<float>(verifier, VT_ATOM_SCALE, 4) &&
           VerifyField<uint8_t>(verifier, VT_ENABLED, 1) &&
           verifier.EndTable();
  }
};

struct ScratchBlockWeightsBuilder {
  typedef ScratchBlockWeights Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_atom_type_embeddings(::flatbuffers::Offset<::flatbuffers::Vector<float>> atom_type_embeddings) {
    fbb_.AddOffset(ScratchBlockWeights::VT_ATOM_TYPE_EMBEDDINGS, atom_type_embeddings);
  }
  void add_atom_projection(::flatbuffers::Offset<::flatbuffers::Vector<float>> atom_projection) {
    fbb_.AddOffset(ScratchBlockWeights::VT_ATOM_PROJECTION, atom_projection);
  }
  void add_text_feature_projection(::flatbuffers::Offset<::flatbuffers::Vector<float>> text_feature_projection) {
    fbb_.AddOffset(ScratchBlockWeights::VT_TEXT_FEATURE_PROJECTION, text_feature_projection);
  }
  void add_value_extraction_weight(::flatbuffers::Offset<::flatbuffers::Vector<float>> value_extraction_weight) {
    fbb_.AddOffset(ScratchBlockWeights::VT_VALUE_EXTRACTION_WEIGHT, value_extraction_weight);
  }
  void add_value_extraction_bias(::flatbuffers::Offset<::flatbuffers::Vector<float>> value_extraction_bias) {
    fbb_.AddOffset(ScratchBlockWeights::VT_VALUE_EXTRACTION_BIAS, value_extraction_bias);
  }
  void add_num_atom_types(uint32_t num_atom_types) {
    fbb_.AddElement<uint32_t>(ScratchBlockWeights::VT_NUM_ATOM_TYPES, num_atom_types, 0);
  }
  void add_atom_embedding_dim(uint32_t atom_embedding_dim) {
    fbb_.AddElement<uint32_t>(ScratchBlockWeights::VT_ATOM_EMBEDDING_DIM, atom_embedding_dim, 0);
  }
  void add_d_model(uint32_t d_model) {
    fbb_.AddElement<uint32_t>(ScratchBlockWeights::VT_D_MODEL, d_model, 0);
  }
  void add_atom_scale(float atom_scale) {
    fbb_.AddElement<float>(ScratchBlockWeights::VT_ATOM_SCALE, atom_scale, 0.0f);
  }
  void add_enabled(bool enabled) {
    fbb_.AddElement<uint8_t>(ScratchBlockWeights::VT_ENABLED, static_cast<uint8_t>(enabled), 0);
  }
  explicit ScratchBlockWeightsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ScratchBlockWeights> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ScratchBlockWeights>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ScratchBlockWeights> CreateScratchBlockWeights(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> atom_type_embeddings = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> atom_projection = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> text_feature_projection = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> value_extraction_weight = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> value_extraction_bias = 0,
    uint32_t num_atom_types = 0,
    uint32_t atom_embedding_dim = 0,
    uint32_t d_model = 0,
    float atom_scale = 0.0f,
    bool enabled = false) {
  ScratchBlockWeightsBuilder builder_(_fbb);
  builder_.add_atom_scale(atom_scale);
  builder_.add_d_model(d_model);
  builder_.add_atom_embedding_dim(atom_embedding_dim);
  builder_.add_num_atom_types(num_atom_types);
  builder_.add_value_extraction_bias(value_extraction_bias);
  builder_.add_value_extraction_weight(value_extraction_weight);
  builder_.add_text_feature_projection(text_feature_projection);
  builder_.add_atom_projection(atom_projection);
  builder_.add_atom_type_embeddings(atom_type_embeddings);
  builder_.add_enabled(enabled);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ScratchBlockWeights> CreateScratchBlockWeightsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *atom_type_embeddings = nullptr,
    const std::vector<float> *atom_projection = nullptr,
    const std::vector<float> *text_feature_projection = nullptr,
    const std::vector<float> *value_extraction_weight = nullptr,
    const std::vector<float> *value_extraction_bias = nullptr,
    uint32_t num_atom_types = 0,
    uint32_t atom_embedding_dim = 0,
    uint32_t d_model = 0,
    float atom_scale = 0.0f,
    bool enabled = false) {
  auto atom_type_embeddings__ = atom_type_embeddings ? _fbb.CreateVector<float>(*atom_type_embeddings) : 0;
  auto atom_projection__ = atom_projection ? _fbb.CreateVector<float>(*atom_projection) : 0;
  auto text_feature_projection__ = text_feature_projection ? _fbb.CreateVector<float>(*text_feature_projection) : 0;
  auto value_extraction_weight__ = value_extraction_weight ? _fbb.CreateVector<float>(*value_extraction_weight) : 0;
  auto value_extraction_bias__ = value_extraction_bias ? _fbb.CreateVector<float>(*value_extraction_bias) : 0;
  return GRIMTransformer::CreateScratchBlockWeights(
      _fbb,
      atom_type_embeddings__,
      atom_projection__,
      text_feature_projection__,
      value_extraction_weight__,
      value_extraction_bias__,
      num_atom_types,
      atom_embedding_dim,
      d_model,
      atom_scale,
      enabled);
}

struct ModelConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelConfigBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VOCAB_SIZE = 4,
    VT_D_MODEL = 6,
    VT_NUM_LAYERS = 8,
    VT_NUM_HEADS = 10,
    VT_NUM_KV_HEADS = 12,
    VT_D_FF = 14,
    VT_MAX_SEQ_LEN = 16,
    VT_DROPOUT_RATE = 18,
    VT_ATTENTION_DROPOUT = 20,
    VT_POSITIONAL_ENCODING = 22,
    VT_USE_ALIBI = 24,
    VT_CAUSAL_MASK = 26,
    VT_USE_PRE_NORM = 28,
    VT_FUSE_QKV = 30,
    VT_TIE_EMBEDDINGS = 32,
    VT_USE_BIAS = 34
  };
  uint32_t vocab_size() const {
    return GetField<uint32_t>(VT_VOCAB_SIZE, 0);
  }
  uint32_t d_model() const {
    return GetField<uint32_t>(VT_D_MODEL, 0);
  }
  uint32_t num_layers() const {
    return GetField<uint32_t>(VT_NUM_LAYERS, 0);
  }
  uint32_t num_heads() const {
    return GetField<uint32_t>(VT_NUM_HEADS, 0);
  }
  uint32_t num_kv_heads() const {
    return GetField<uint32_t>(VT_NUM_KV_HEADS, 0);
  }
  uint32_t d_ff() const {
    return GetField<uint32_t>(VT_D_FF, 0);
  }
  uint32_t max_seq_len() const {
    return GetField<uint32_t>(VT_MAX_SEQ_LEN, 0);
  }
  float dropout_rate() const {
    return GetField<float>(VT_DROPOUT_RATE, 0.1f);
  }
  float attention_dropout() const {
    return GetField<float>(VT_ATTENTION_DROPOUT, 0.1f);
  }
  GRIMTransformer::PositionalEncodingType positional_encoding() const {
    return static_cast<GRIMTransformer::PositionalEncodingType>(GetField<uint8_t>(VT_POSITIONAL_ENCODING, 3));
  }
  bool use_alibi() const {
    return GetField<uint8_t>(VT_USE_ALIBI, 0) != 0;
  }
  bool causal_mask() const {
    return GetField<uint8_t>(VT_CAUSAL_MASK, 1) != 0;
  }
  bool use_pre_norm() const {
    return GetField<uint8_t>(VT_USE_PRE_NORM, 1) != 0;
  }
  bool fuse_qkv() const {
    return GetField<uint8_t>(VT_FUSE_QKV, 1) != 0;
  }
  bool tie_embeddings() const {
    return GetField<uint8_t>(VT_TIE_EMBEDDINGS, 1) != 0;
  }
  bool use_bias() const {
    return GetField<uint8_t>(VT_USE_BIAS, 1) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VOCAB_SIZE, 4) &&
           VerifyField<uint32_t>(verifier, VT_D_MODEL, 4) &&
           VerifyField<uint32_t>(verifier, VT_NUM_LAYERS, 4) &&
           VerifyField<uint32_t>(verifier, VT_NUM_HEADS, 4) &&
           VerifyField<uint32_t>(verifier, VT_NUM_KV_HEADS, 4) &&
           VerifyField<uint32_t>(verifier, VT_D_FF, 4) &&
           VerifyField<uint32_t>(verifier, VT_MAX_SEQ_LEN, 4) &&
           VerifyField<float>(verifier, VT_DROPOUT_RATE, 4) &&
           VerifyField<float>(verifier, VT_ATTENTION_DROPOUT, 4) &&
           VerifyField<uint8_t>(verifier, VT_POSITIONAL_ENCODING, 1) &&
           VerifyField<uint8_t>(verifier, VT_USE_ALIBI, 1) &&
           VerifyField<uint8_t>(verifier, VT_CAUSAL_MASK, 1) &&
           VerifyField<uint8_t>(verifier, VT_USE_PRE_NORM, 1) &&
           VerifyField<uint8_t>(verifier, VT_FUSE_QKV, 1) &&
           VerifyField<uint8_t>(verifier, VT_TIE_EMBEDDINGS, 1) &&
           VerifyField<uint8_t>(verifier, VT_USE_BIAS, 1) &&
           verifier.EndTable();
  }
};

struct ModelConfigBuilder {
  typedef ModelConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vocab_size(uint32_t vocab_size) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_VOCAB_SIZE, vocab_size, 0);
  }
  void add_d_model(uint32_t d_model) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_D_MODEL, d_model, 0);
  }
  void add_num_layers(uint32_t num_layers) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_NUM_LAYERS, num_layers, 0);
  }
  void add_num_heads(uint32_t num_heads) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_NUM_HEADS, num_heads, 0);
  }
  void add_num_kv_heads(uint32_t num_kv_heads) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_NUM_KV_HEADS, num_kv_heads, 0);
  }
  void add_d_ff(uint32_t d_ff) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_D_FF, d_ff, 0);
  }
  void add_max_seq_len(uint32_t max_seq_len) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_MAX_SEQ_LEN, max_seq_len, 0);
  }
  void add_dropout_rate(float dropout_rate) {
    fbb_.AddElement<float>(ModelConfig::VT_DROPOUT_RATE, dropout_rate, 0.1f);
  }
  void add_attention_dropout(float attention_dropout) {
    fbb_.AddElement<float>(ModelConfig::VT_ATTENTION_DROPOUT, attention_dropout, 0.1f);
  }
  void add_positional_encoding(GRIMTransformer::PositionalEncodingType positional_encoding) {
    fbb_.AddElement<uint8_t>(ModelConfig::VT_POSITIONAL_ENCODING, static_cast<uint8_t>(positional_encoding), 3);
  }
  void add_use_alibi(bool use_alibi) {
    fbb_.AddElement<uint8_t>(ModelConfig::VT_USE_ALIBI, static_cast<uint8_t>(use_alibi), 0);
  }
  void add_causal_mask(bool causal_mask) {
    fbb_.AddElement<uint8_t>(ModelConfig::VT_CAUSAL_MASK, static_cast<uint8_t>(causal_mask), 1);
  }
  void add_use_pre_norm(bool use_pre_norm) {
    fbb_.AddElement<uint8_t>(ModelConfig::VT_USE_PRE_NORM, static_cast<uint8_t>(use_pre_norm), 1);
  }
  void add_fuse_qkv(bool fuse_qkv) {
    fbb_.AddElement<uint8_t>(ModelConfig::VT_FUSE_QKV, static_cast<uint8_t>(fuse_qkv), 1);
  }
  void add_tie_embeddings(bool tie_embeddings) {
    fbb_.AddElement<uint8_t>(ModelConfig::VT_TIE_EMBEDDINGS, static_cast<uint8_t>(tie_embeddings), 1);
  }
  void add_use_bias(bool use_bias) {
    fbb_.AddElement<uint8_t>(ModelConfig::VT_USE_BIAS, static_cast<uint8_t>(use_bias), 1);
  }
  explicit ModelConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModelConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModelConfig>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModelConfig> CreateModelConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t vocab_size = 0,
    uint32_t d_model = 0,
    uint32_t num_layers = 0,
    uint32_t num_heads = 0,
    uint32_t num_kv_heads = 0,
    uint32_t d_ff = 0,
    uint32_t max_seq_len = 0,
    float dropout_rate = 0.1f,
    float attention_dropout = 0.1f,
    GRIMTransformer::PositionalEncodingType positional_encoding = GRIMTransformer::PositionalEncodingType_ALIBI_ROPE,
    bool use_alibi = false,
    bool causal_mask = true,
    bool use_pre_norm = true,
    bool fuse_qkv = true,
    bool tie_embeddings = true,
    bool use_bias = true) {
  ModelConfigBuilder builder_(_fbb);
  builder_.add_attention_dropout(attention_dropout);
  builder_.add_dropout_rate(dropout_rate);
  builder_.add_max_seq_len(max_seq_len);
  builder_.add_d_ff(d_ff);
  builder_.add_num_kv_heads(num_kv_heads);
  builder_.add_num_heads(num_heads);
  builder_.add_num_layers(num_layers);
  builder_.add_d_model(d_model);
  builder_.add_vocab_size(vocab_size);
  builder_.add_use_bias(use_bias);
  builder_.add_tie_embeddings(tie_embeddings);
  builder_.add_fuse_qkv(fuse_qkv);
  builder_.add_use_pre_norm(use_pre_norm);
  builder_.add_causal_mask(causal_mask);
  builder_.add_use_alibi(use_alibi);
  builder_.add_positional_encoding(positional_encoding);
  return builder_.Finish();
}

struct LossWeightingWeights FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LossWeightingWeightsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LOG_VAR_TEXT = 4,
    VT_LOG_VAR_NUMERIC = 6
  };
  float log_var_text() const {
    return GetField<float>(VT_LOG_VAR_TEXT, 0.0f);
  }
  float log_var_numeric() const {
    return GetField<float>(VT_LOG_VAR_NUMERIC, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_LOG_VAR_TEXT, 4) &&
           VerifyField<float>(verifier, VT_LOG_VAR_NUMERIC, 4) &&
           verifier.EndTable();
  }
};

struct LossWeightingWeightsBuilder {
  typedef LossWeightingWeights Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_log_var_text(float log_var_text) {
    fbb_.AddElement<float>(LossWeightingWeights::VT_LOG_VAR_TEXT, log_var_text, 0.0f);
  }
  void add_log_var_numeric(float log_var_numeric) {
    fbb_.AddElement<float>(LossWeightingWeights::VT_LOG_VAR_NUMERIC, log_var_numeric, 0.0f);
  }
  explicit LossWeightingWeightsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LossWeightingWeights> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LossWeightingWeights>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LossWeightingWeights> CreateLossWeightingWeights(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float log_var_text = 0.0f,
    float log_var_numeric = 0.0f) {
  LossWeightingWeightsBuilder builder_(_fbb);
  builder_.add_log_var_numeric(log_var_numeric);
  builder_.add_log_var_text(log_var_text);
  return builder_.Finish();
}

struct TrainingMetadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrainingMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OPTIMIZER = 4,
    VT_LEARNING_RATE = 6,
    VT_BATCH_SIZE = 8,
    VT_NUM_EPOCHS = 10,
    VT_TRAINING_STEPS = 12,
    VT_FINAL_TRAIN_LOSS = 14,
    VT_FINAL_VAL_LOSS = 16,
    VT_BEST_VAL_LOSS = 18,
    VT_GRADIENT_NORM = 20,
    VT_TIMESTAMP = 22,
    VT_TRAINING_DURATION_SECONDS = 24,
    VT_MODEL_NAME = 26
  };
  const ::flatbuffers::String *optimizer() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OPTIMIZER);
  }
  float learning_rate() const {
    return GetField<float>(VT_LEARNING_RATE, 0.0f);
  }
  uint32_t batch_size() const {
    return GetField<uint32_t>(VT_BATCH_SIZE, 0);
  }
  uint32_t num_epochs() const {
    return GetField<uint32_t>(VT_NUM_EPOCHS, 0);
  }
  uint64_t training_steps() const {
    return GetField<uint64_t>(VT_TRAINING_STEPS, 0);
  }
  float final_train_loss() const {
    return GetField<float>(VT_FINAL_TRAIN_LOSS, 0.0f);
  }
  float final_val_loss() const {
    return GetField<float>(VT_FINAL_VAL_LOSS, 0.0f);
  }
  float best_val_loss() const {
    return GetField<float>(VT_BEST_VAL_LOSS, 0.0f);
  }
  float gradient_norm() const {
    return GetField<float>(VT_GRADIENT_NORM, 0.0f);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint64_t training_duration_seconds() const {
    return GetField<uint64_t>(VT_TRAINING_DURATION_SECONDS, 0);
  }
  const ::flatbuffers::String *model_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODEL_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_OPTIMIZER) &&
           verifier.VerifyString(optimizer()) &&
           VerifyField<float>(verifier, VT_LEARNING_RATE, 4) &&
           VerifyField<uint32_t>(verifier, VT_BATCH_SIZE, 4) &&
           VerifyField<uint32_t>(verifier, VT_NUM_EPOCHS, 4) &&
           VerifyField<uint64_t>(verifier, VT_TRAINING_STEPS, 8) &&
           VerifyField<float>(verifier, VT_FINAL_TRAIN_LOSS, 4) &&
           VerifyField<float>(verifier, VT_FINAL_VAL_LOSS, 4) &&
           VerifyField<float>(verifier, VT_BEST_VAL_LOSS, 4) &&
           VerifyField<float>(verifier, VT_GRADIENT_NORM, 4) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint64_t>(verifier, VT_TRAINING_DURATION_SECONDS, 8) &&
           VerifyOffset(verifier, VT_MODEL_NAME) &&
           verifier.VerifyString(model_name()) &&
           verifier.EndTable();
  }
};

struct TrainingMetadataBuilder {
  typedef TrainingMetadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_optimizer(::flatbuffers::Offset<::flatbuffers::String> optimizer) {
    fbb_.AddOffset(TrainingMetadata::VT_OPTIMIZER, optimizer);
  }
  void add_learning_rate(float learning_rate) {
    fbb_.AddElement<float>(TrainingMetadata::VT_LEARNING_RATE, learning_rate, 0.0f);
  }
  void add_batch_size(uint32_t batch_size) {
    fbb_.AddElement<uint32_t>(TrainingMetadata::VT_BATCH_SIZE, batch_size, 0);
  }
  void add_num_epochs(uint32_t num_epochs) {
    fbb_.AddElement<uint32_t>(TrainingMetadata::VT_NUM_EPOCHS, num_epochs, 0);
  }
  void add_training_steps(uint64_t training_steps) {
    fbb_.AddElement<uint64_t>(TrainingMetadata::VT_TRAINING_STEPS, training_steps, 0);
  }
  void add_final_train_loss(float final_train_loss) {
    fbb_.AddElement<float>(TrainingMetadata::VT_FINAL_TRAIN_LOSS, final_train_loss, 0.0f);
  }
  void add_final_val_loss(float final_val_loss) {
    fbb_.AddElement<float>(TrainingMetadata::VT_FINAL_VAL_LOSS, final_val_loss, 0.0f);
  }
  void add_best_val_loss(float best_val_loss) {
    fbb_.AddElement<float>(TrainingMetadata::VT_BEST_VAL_LOSS, best_val_loss, 0.0f);
  }
  void add_gradient_norm(float gradient_norm) {
    fbb_.AddElement<float>(TrainingMetadata::VT_GRADIENT_NORM, gradient_norm, 0.0f);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(TrainingMetadata::VT_TIMESTAMP, timestamp, 0);
  }
  void add_training_duration_seconds(uint64_t training_duration_seconds) {
    fbb_.AddElement<uint64_t>(TrainingMetadata::VT_TRAINING_DURATION_SECONDS, training_duration_seconds, 0);
  }
  void add_model_name(::flatbuffers::Offset<::flatbuffers::String> model_name) {
    fbb_.AddOffset(TrainingMetadata::VT_MODEL_NAME, model_name);
  }
  explicit TrainingMetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrainingMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrainingMetadata>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TrainingMetadata> CreateTrainingMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> optimizer = 0,
    float learning_rate = 0.0f,
    uint32_t batch_size = 0,
    uint32_t num_epochs = 0,
    uint64_t training_steps = 0,
    float final_train_loss = 0.0f,
    float final_val_loss = 0.0f,
    float best_val_loss = 0.0f,
    float gradient_norm = 0.0f,
    uint64_t timestamp = 0,
    uint64_t training_duration_seconds = 0,
    ::flatbuffers::Offset<::flatbuffers::String> model_name = 0) {
  TrainingMetadataBuilder builder_(_fbb);
  builder_.add_training_duration_seconds(training_duration_seconds);
  builder_.add_timestamp(timestamp);
  builder_.add_training_steps(training_steps);
  builder_.add_model_name(model_name);
  builder_.add_gradient_norm(gradient_norm);
  builder_.add_best_val_loss(best_val_loss);
  builder_.add_final_val_loss(final_val_loss);
  builder_.add_final_train_loss(final_train_loss);
  builder_.add_num_epochs(num_epochs);
  builder_.add_batch_size(batch_size);
  builder_.add_learning_rate(learning_rate);
  builder_.add_optimizer(optimizer);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TrainingMetadata> CreateTrainingMetadataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *optimizer = nullptr,
    float learning_rate = 0.0f,
    uint32_t batch_size = 0,
    uint32_t num_epochs = 0,
    uint64_t training_steps = 0,
    float final_train_loss = 0.0f,
    float final_val_loss = 0.0f,
    float best_val_loss = 0.0f,
    float gradient_norm = 0.0f,
    uint64_t timestamp = 0,
    uint64_t training_duration_seconds = 0,
    const char *model_name = nullptr) {
  auto optimizer__ = optimizer ? _fbb.CreateString(optimizer) : 0;
  auto model_name__ = model_name ? _fbb.CreateString(model_name) : 0;
  return GRIMTransformer::CreateTrainingMetadata(
      _fbb,
      optimizer__,
      learning_rate,
      batch_size,
      num_epochs,
      training_steps,
      final_train_loss,
      final_val_loss,
      best_val_loss,
      gradient_norm,
      timestamp,
      training_duration_seconds,
      model_name__);
}

struct TransformerModel FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TransformerModelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_CONFIG = 6,
    VT_EMBEDDINGS = 8,
    VT_ENCODER_LAYERS = 10,
    VT_LM_HEAD = 12,
    VT_NUMERIC_HEAD = 14,
    VT_SCRATCH_BLOCK = 16,
    VT_FINAL_RMS_GAMMA = 18,
    VT_LOSS_WEIGHTING = 20,
    VT_TRAINING_METADATA = 22,
    VT_CHECKSUM_CRC32 = 24,
    VT_CHECKSUM_XXHASH64 = 26,
    VT_CREATION_TIMESTAMP = 28,
    VT_LAST_MODIFIED_TIMESTAMP = 30
  };
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const GRIMTransformer::ModelConfig *config() const {
    return GetPointer<const GRIMTransformer::ModelConfig *>(VT_CONFIG);
  }
  const GRIMTransformer::EmbeddingWeights *embeddings() const {
    return GetPointer<const GRIMTransformer::EmbeddingWeights *>(VT_EMBEDDINGS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMTransformer::EncoderLayerWeights>> *encoder_layers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GRIMTransformer::EncoderLayerWeights>> *>(VT_ENCODER_LAYERS);
  }
  const GRIMTransformer::LMHeadWeights *lm_head() const {
    return GetPointer<const GRIMTransformer::LMHeadWeights *>(VT_LM_HEAD);
  }
  const GRIMTransformer::NumericHeadWeights *numeric_head() const {
    return GetPointer<const GRIMTransformer::NumericHeadWeights *>(VT_NUMERIC_HEAD);
  }
  const GRIMTransformer::ScratchBlockWeights *scratch_block() const {
    return GetPointer<const GRIMTransformer::ScratchBlockWeights *>(VT_SCRATCH_BLOCK);
  }
  const ::flatbuffers::Vector<float> *final_rms_gamma() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_FINAL_RMS_GAMMA);
  }
  const GRIMTransformer::LossWeightingWeights *loss_weighting() const {
    return GetPointer<const GRIMTransformer::LossWeightingWeights *>(VT_LOSS_WEIGHTING);
  }
  const GRIMTransformer::TrainingMetadata *training_metadata() const {
    return GetPointer<const GRIMTransformer::TrainingMetadata *>(VT_TRAINING_METADATA);
  }
  uint32_t checksum_crc32() const {
    return GetField<uint32_t>(VT_CHECKSUM_CRC32, 0);
  }
  uint64_t checksum_xxhash64() const {
    return GetField<uint64_t>(VT_CHECKSUM_XXHASH64, 0);
  }
  uint64_t creation_timestamp() const {
    return GetField<uint64_t>(VT_CREATION_TIMESTAMP, 0);
  }
  uint64_t last_modified_timestamp() const {
    return GetField<uint64_t>(VT_LAST_MODIFIED_TIMESTAMP, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffsetRequired(verifier, VT_CONFIG) &&
           verifier.VerifyTable(config()) &&
           VerifyOffsetRequired(verifier, VT_EMBEDDINGS) &&
           verifier.VerifyTable(embeddings()) &&
           VerifyOffsetRequired(verifier, VT_ENCODER_LAYERS) &&
           verifier.VerifyVector(encoder_layers()) &&
           verifier.VerifyVectorOfTables(encoder_layers()) &&
           VerifyOffsetRequired(verifier, VT_LM_HEAD) &&
           verifier.VerifyTable(lm_head()) &&
           VerifyOffset(verifier, VT_NUMERIC_HEAD) &&
           verifier.VerifyTable(numeric_head()) &&
           VerifyOffset(verifier, VT_SCRATCH_BLOCK) &&
           verifier.VerifyTable(scratch_block()) &&
           VerifyOffset(verifier, VT_FINAL_RMS_GAMMA) &&
           verifier.VerifyVector(final_rms_gamma()) &&
           VerifyOffset(verifier, VT_LOSS_WEIGHTING) &&
           verifier.VerifyTable(loss_weighting()) &&
           VerifyOffset(verifier, VT_TRAINING_METADATA) &&
           verifier.VerifyTable(training_metadata()) &&
           VerifyField<uint32_t>(verifier, VT_CHECKSUM_CRC32, 4) &&
           VerifyField<uint64_t>(verifier, VT_CHECKSUM_XXHASH64, 8) &&
           VerifyField<uint64_t>(verifier, VT_CREATION_TIMESTAMP, 8) &&
           VerifyField<uint64_t>(verifier, VT_LAST_MODIFIED_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct TransformerModelBuilder {
  typedef TransformerModel Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(TransformerModel::VT_VERSION, version, 0);
  }
  void add_config(::flatbuffers::Offset<GRIMTransformer::ModelConfig> config) {
    fbb_.AddOffset(TransformerModel::VT_CONFIG, config);
  }
  void add_embeddings(::flatbuffers::Offset<GRIMTransformer::EmbeddingWeights> embeddings) {
    fbb_.AddOffset(TransformerModel::VT_EMBEDDINGS, embeddings);
  }
  void add_encoder_layers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMTransformer::EncoderLayerWeights>>> encoder_layers) {
    fbb_.AddOffset(TransformerModel::VT_ENCODER_LAYERS, encoder_layers);
  }
  void add_lm_head(::flatbuffers::Offset<GRIMTransformer::LMHeadWeights> lm_head) {
    fbb_.AddOffset(TransformerModel::VT_LM_HEAD, lm_head);
  }
  void add_numeric_head(::flatbuffers::Offset<GRIMTransformer::NumericHeadWeights> numeric_head) {
    fbb_.AddOffset(TransformerModel::VT_NUMERIC_HEAD, numeric_head);
  }
  void add_scratch_block(::flatbuffers::Offset<GRIMTransformer::ScratchBlockWeights> scratch_block) {
    fbb_.AddOffset(TransformerModel::VT_SCRATCH_BLOCK, scratch_block);
  }
  void add_final_rms_gamma(::flatbuffers::Offset<::flatbuffers::Vector<float>> final_rms_gamma) {
    fbb_.AddOffset(TransformerModel::VT_FINAL_RMS_GAMMA, final_rms_gamma);
  }
  void add_loss_weighting(::flatbuffers::Offset<GRIMTransformer::LossWeightingWeights> loss_weighting) {
    fbb_.AddOffset(TransformerModel::VT_LOSS_WEIGHTING, loss_weighting);
  }
  void add_training_metadata(::flatbuffers::Offset<GRIMTransformer::TrainingMetadata> training_metadata) {
    fbb_.AddOffset(TransformerModel::VT_TRAINING_METADATA, training_metadata);
  }
  void add_checksum_crc32(uint32_t checksum_crc32) {
    fbb_.AddElement<uint32_t>(TransformerModel::VT_CHECKSUM_CRC32, checksum_crc32, 0);
  }
  void add_checksum_xxhash64(uint64_t checksum_xxhash64) {
    fbb_.AddElement<uint64_t>(TransformerModel::VT_CHECKSUM_XXHASH64, checksum_xxhash64, 0);
  }
  void add_creation_timestamp(uint64_t creation_timestamp) {
    fbb_.AddElement<uint64_t>(TransformerModel::VT_CREATION_TIMESTAMP, creation_timestamp, 0);
  }
  void add_last_modified_timestamp(uint64_t last_modified_timestamp) {
    fbb_.AddElement<uint64_t>(TransformerModel::VT_LAST_MODIFIED_TIMESTAMP, last_modified_timestamp, 0);
  }
  explicit TransformerModelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TransformerModel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TransformerModel>(end);
    fbb_.Required(o, TransformerModel::VT_CONFIG);
    fbb_.Required(o, TransformerModel::VT_EMBEDDINGS);
    fbb_.Required(o, TransformerModel::VT_ENCODER_LAYERS);
    fbb_.Required(o, TransformerModel::VT_LM_HEAD);
    return o;
  }
};

inline ::flatbuffers::Offset<TransformerModel> CreateTransformerModel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0,
    ::flatbuffers::Offset<GRIMTransformer::ModelConfig> config = 0,
    ::flatbuffers::Offset<GRIMTransformer::EmbeddingWeights> embeddings = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GRIMTransformer::EncoderLayerWeights>>> encoder_layers = 0,
    ::flatbuffers::Offset<GRIMTransformer::LMHeadWeights> lm_head = 0,
    ::flatbuffers::Offset<GRIMTransformer::NumericHeadWeights> numeric_head = 0,
    ::flatbuffers::Offset<GRIMTransformer::ScratchBlockWeights> scratch_block = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> final_rms_gamma = 0,
    ::flatbuffers::Offset<GRIMTransformer::LossWeightingWeights> loss_weighting = 0,
    ::flatbuffers::Offset<GRIMTransformer::TrainingMetadata> training_metadata = 0,
    uint32_t checksum_crc32 = 0,
    uint64_t checksum_xxhash64 = 0,
    uint64_t creation_timestamp = 0,
    uint64_t last_modified_timestamp = 0) {
  TransformerModelBuilder builder_(_fbb);
  builder_.add_last_modified_timestamp(last_modified_timestamp);
  builder_.add_creation_timestamp(creation_timestamp);
  builder_.add_checksum_xxhash64(checksum_xxhash64);
  builder_.add_checksum_crc32(checksum_crc32);
  builder_.add_training_metadata(training_metadata);
  builder_.add_loss_weighting(loss_weighting);
  builder_.add_final_rms_gamma(final_rms_gamma);
  builder_.add_scratch_block(scratch_block);
  builder_.add_numeric_head(numeric_head);
  builder_.add_lm_head(lm_head);
  builder_.add_encoder_layers(encoder_layers);
  builder_.add_embeddings(embeddings);
  builder_.add_config(config);
  builder_.add_version(version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TransformerModel> CreateTransformerModelDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0,
    ::flatbuffers::Offset<GRIMTransformer::ModelConfig> config = 0,
    ::flatbuffers::Offset<GRIMTransformer::EmbeddingWeights> embeddings = 0,
    const std::vector<::flatbuffers::Offset<GRIMTransformer::EncoderLayerWeights>> *encoder_layers = nullptr,
    ::flatbuffers::Offset<GRIMTransformer::LMHeadWeights> lm_head = 0,
    ::flatbuffers::Offset<GRIMTransformer::NumericHeadWeights> numeric_head = 0,
    ::flatbuffers::Offset<GRIMTransformer::ScratchBlockWeights> scratch_block = 0,
    const std::vector<float> *final_rms_gamma = nullptr,
    ::flatbuffers::Offset<GRIMTransformer::LossWeightingWeights> loss_weighting = 0,
    ::flatbuffers::Offset<GRIMTransformer::TrainingMetadata> training_metadata = 0,
    uint32_t checksum_crc32 = 0,
    uint64_t checksum_xxhash64 = 0,
    uint64_t creation_timestamp = 0,
    uint64_t last_modified_timestamp = 0) {
  auto encoder_layers__ = encoder_layers ? _fbb.CreateVector<::flatbuffers::Offset<GRIMTransformer::EncoderLayerWeights>>(*encoder_layers) : 0;
  auto final_rms_gamma__ = final_rms_gamma ? _fbb.CreateVector<float>(*final_rms_gamma) : 0;
  return GRIMTransformer::CreateTransformerModel(
      _fbb,
      version,
      config,
      embeddings,
      encoder_layers__,
      lm_head,
      numeric_head,
      scratch_block,
      final_rms_gamma__,
      loss_weighting,
      training_metadata,
      checksum_crc32,
      checksum_xxhash64,
      creation_timestamp,
      last_modified_timestamp);
}

inline const GRIMTransformer::TransformerModel *GetTransformerModel(const void *buf) {
  return ::flatbuffers::GetRoot<GRIMTransformer::TransformerModel>(buf);
}

inline const GRIMTransformer::TransformerModel *GetSizePrefixedTransformerModel(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GRIMTransformer::TransformerModel>(buf);
}

inline const char *TransformerModelIdentifier() {
  return "GRMT";
}

inline bool TransformerModelBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, TransformerModelIdentifier());
}

inline bool SizePrefixedTransformerModelBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, TransformerModelIdentifier(), true);
}

inline bool VerifyTransformerModelBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GRIMTransformer::TransformerModel>(TransformerModelIdentifier());
}

inline bool VerifySizePrefixedTransformerModelBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GRIMTransformer::TransformerModel>(TransformerModelIdentifier());
}

inline const char *TransformerModelExtension() {
  return "bin";
}

inline void FinishTransformerModelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIMTransformer::TransformerModel> root) {
  fbb.Finish(root, TransformerModelIdentifier());
}

inline void FinishSizePrefixedTransformerModelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GRIMTransformer::TransformerModel> root) {
  fbb.FinishSizePrefixed(root, TransformerModelIdentifier());
}

}  // namespace GRIMTransformer

#endif  // FLATBUFFERS_GENERATED_GRIMTRANSFORMERMODEL_GRIMTRANSFORMER_H_
