#!/usr/bin/env python3
"""
Compile NLP Grammar to FlatBuffers binary format
Converts nlp_grammar.json to grammar_rules.fb for efficient loading

Usage:
    python compile_grammar_fb.py --input resources/nlp_grammar.json --output resources/grammar_rules.fb
"""

import argparse
import json
import sys
from pathlib import Path
import time

try:
    import flatbuffers
    # Import generated FlatBuffer classes (will be generated by flatc)
    # These will be available after running: flatc --python grammar_rules.fbs
    sys.path.insert(0, str(Path(__file__).parent.parent / 'nlp'))
    from GrammarRules import (
        GrammarConfig, GrammarComponent, CommandVerb, CommandObject,
        SentenceTemplate, ContextRule, LearningConfig
    )
except ImportError as e:
    print(f"Error: {e}")
    print("\nPlease ensure:")
    print("1. flatbuffers is installed: pip install flatbuffers")
    print("2. Generate Python bindings: flatc --python nlp/grammar_rules.fbs")
    sys.exit(1)


def compile_grammar_to_flatbuffer(json_path: Path, output_path: Path):
    """Compile JSON grammar to FlatBuffer binary."""
    
    # Load JSON
    with open(json_path, 'r', encoding='utf-8') as f:
        grammar_data = json.load(f)
    
    # Create FlatBuffer
    builder = flatbuffers.Builder(1024)
    
    # Build components
    component_offsets = []
    for name, comp in grammar_data.get('grammar_components', {}).items():
        name_offset = builder.CreateString(name)
        desc_offset = builder.CreateString(comp.get('description', ''))
        
        # Patterns
        pattern_offsets = [builder.CreateString(p) for p in comp.get('patterns', [])]
        GrammarComponent.StartPatternsVector(builder, len(pattern_offsets))
        for p in reversed(pattern_offsets):
            builder.PrependUOffsetTRelative(p)
        patterns_offset = builder.EndVector()
        
        # Create component
        GrammarComponent.Start(builder)
        GrammarComponent.AddName(builder, name_offset)
        GrammarComponent.AddDescription(builder, desc_offset)
        GrammarComponent.AddPatterns(builder, patterns_offset)
        GrammarComponent.AddOptional(builder, comp.get('optional', False))
        GrammarComponent.AddCapture(builder, comp.get('capture', False))
        GrammarComponent.AddRequiresContext(builder, comp.get('requires_context', False))
        GrammarComponent.AddFrequency(builder, comp.get('frequency', 0))
        GrammarComponent.AddWeight(builder, comp.get('weight', 1.0))
        component_offsets.append(GrammarComponent.End(builder))
    
    # Build components vector
    GrammarConfig.StartComponentsVector(builder, len(component_offsets))
    for c in reversed(component_offsets):
        builder.PrependUOffsetTRelative(c)
    components_vector = builder.EndVector()
    
    # Build verbs (similar pattern)
    verb_offsets = []
    for verb, data in grammar_data.get('command_verbs', {}).items():
        verb_offset = builder.CreateString(verb)
        intent_offset = builder.CreateString(data.get('intent', ''))
        pipeline_offset = builder.CreateString(data.get('pipeline_category', 'command'))
        
        syn_offsets = [builder.CreateString(s) for s in data.get('synonyms', [])]
        CommandVerb.StartSynonymsVector(builder, len(syn_offsets))
        for s in reversed(syn_offsets):
            builder.PrependUOffsetTRelative(s)
        synonyms_offset = builder.EndVector()
        
        CommandVerb.Start(builder)
        CommandVerb.AddCanonical(builder, verb_offset)
        CommandVerb.AddSynonyms(builder, synonyms_offset)
        CommandVerb.AddIntent(builder, intent_offset)
        CommandVerb.AddRequiresObject(builder, data.get('requires_object', False))
        CommandVerb.AddFrequency(builder, data.get('frequency', 0))
        CommandVerb.AddWeight(builder, data.get('weight', 1.0))
        CommandVerb.AddPipelineCategory(builder, pipeline_offset)
        verb_offsets.append(CommandVerb.End(builder))
    
    GrammarConfig.StartVerbsVector(builder, len(verb_offsets))
    for v in reversed(verb_offsets):
        builder.PrependUOffsetTRelative(v)
    verbs_vector = builder.EndVector()
    
    # Build objects
    object_offsets = []
    for obj, data in grammar_data.get('command_objects', {}).items():
        obj_offset = builder.CreateString(obj)
        cat_offset = builder.CreateString(data.get('category', ''))
        
        syn_offsets = [builder.CreateString(s) for s in data.get('synonyms', [])]
        CommandObject.StartSynonymsVector(builder, len(syn_offsets))
        for s in reversed(syn_offsets):
            builder.PrependUOffsetTRelative(s)
        synonyms_offset = builder.EndVector()
        
        CommandObject.Start(builder)
        CommandObject.AddCanonical(builder, obj_offset)
        CommandObject.AddSynonyms(builder, synonyms_offset)
        CommandObject.AddCategory(builder, cat_offset)
        CommandObject.AddFrequency(builder, data.get('frequency', 0))
        CommandObject.AddWeight(builder, data.get('weight', 1.0))
        object_offsets.append(CommandObject.End(builder))
    
    GrammarConfig.StartObjectsVector(builder, len(object_offsets))
    for o in reversed(object_offsets):
        builder.PrependUOffsetTRelative(o)
    objects_vector = builder.EndVector()
    
    # Build templates
    template_offsets = []
    for name, tmpl in grammar_data.get('sentence_templates', {}).items():
        name_offset = builder.CreateString(name)
        struct_offset = builder.CreateString(tmpl.get('structure', ''))
        cat_offset = builder.CreateString(tmpl.get('category', ''))
        pipeline_offset = builder.CreateString(tmpl.get('pipeline_category', 'command'))
        
        ex_offsets = [builder.CreateString(e) for e in tmpl.get('examples', [])]
        SentenceTemplate.StartExamplesVector(builder, len(ex_offsets))
        for e in reversed(ex_offsets):
            builder.PrependUOffsetTRelative(e)
        examples_offset = builder.EndVector()
        
        mod_offsets = [builder.CreateString(m) for m in tmpl.get('common_modifiers', [])]
        SentenceTemplate.StartCommonModifiersVector(builder, len(mod_offsets))
        for m in reversed(mod_offsets):
            builder.PrependUOffsetTRelative(m)
        modifiers_offset = builder.EndVector()
        
        SentenceTemplate.Start(builder)
        SentenceTemplate.AddName(builder, name_offset)
        SentenceTemplate.AddStructure(builder, struct_offset)
        SentenceTemplate.AddExamples(builder, examples_offset)
        SentenceTemplate.AddRequiresContext(builder, tmpl.get('requires_context', False))
        SentenceTemplate.AddCategory(builder, cat_offset)
        SentenceTemplate.AddFrequency(builder, tmpl.get('frequency', 0))
        SentenceTemplate.AddWeight(builder, tmpl.get('weight', 1.0))
        SentenceTemplate.AddPipelineCategory(builder, pipeline_offset)
        SentenceTemplate.AddAvgDepth(builder, tmpl.get('avg_depth', 0.0))
        SentenceTemplate.AddCommonModifiers(builder, modifiers_offset)
        template_offsets.append(SentenceTemplate.End(builder))
    
    GrammarConfig.StartTemplatesVector(builder, len(template_offsets))
    for t in reversed(template_offsets):
        builder.PrependUOffsetTRelative(t)
    templates_vector = builder.EndVector()
    
    # Build learning config
    learning_data = grammar_data.get('learning_config', {})
    LearningConfig.Start(builder)
    LearningConfig.AddEnableOnlineLearning(builder, learning_data.get('enable_online_learning', True))
    LearningConfig.AddMinConfidenceThreshold(builder, learning_data.get('min_confidence_threshold', 0.6))
    LearningConfig.AddFeedbackWeight(builder, learning_data.get('feedback_weight', 0.3))
    LearningConfig.AddDecayRate(builder, learning_data.get('decay_rate', 0.95))
    learning_offset = LearningConfig.End(builder)
    
    # Build root config
    lang_offset = builder.CreateString(grammar_data.get('language', 'en'))
    source_offset = builder.CreateString(grammar_data.get('treebank_source', 'Unknown'))
    
    GrammarConfig.Start(builder)
    GrammarConfig.AddVersion(builder, grammar_data.get('version', 1))
    GrammarConfig.AddLanguage(builder, lang_offset)
    GrammarConfig.AddTreebankSource(builder, source_offset)
    GrammarConfig.AddComponents(builder, components_vector)
    GrammarConfig.AddVerbs(builder, verbs_vector)
    GrammarConfig.AddObjects(builder, objects_vector)
    GrammarConfig.AddTemplates(builder, templates_vector)
    GrammarConfig.AddLearningConfig(builder, learning_offset)
    GrammarConfig.AddGeneratedTimestamp(builder, int(time.time()))
    GrammarConfig.AddTotalSentencesAnalyzed(builder, 0)
    merge_offset = builder.CreateString('weighted')
    GrammarConfig.AddMergeStrategy(builder, merge_offset)
    config = GrammarConfig.End(builder)
    
    builder.Finish(config)
    
    # Write to file
    buf = builder.Output()
    with open(output_path, 'wb') as f:
        f.write(buf)
    
    print(f"✓ Compiled grammar to: {output_path}")
    print(f"  Size: {len(buf)} bytes")
    print(f"  Components: {len(grammar_data.get('grammar_components', {}))}")
    print(f"  Verbs: {len(grammar_data.get('command_verbs', {}))}")
    print(f"  Objects: {len(grammar_data.get('command_objects', {}))}")
    print(f"  Templates: {len(grammar_data.get('sentence_templates', {}))}")


def main():
    parser = argparse.ArgumentParser(description='Compile NLP grammar to FlatBuffer binary')
    parser.add_argument('--input', '-i', type=Path, default=Path('resources/nlp_grammar.json'))
    parser.add_argument('--output', '-o', type=Path, default=Path('resources/grammar_rules.fb'))
    
    args = parser.parse_args()
    
    if not args.input.exists():
        print(f"Error: Input file not found: {args.input}")
        return 1
    
    try:
        compile_grammar_to_flatbuffer(args.input, args.output)
        return 0
    except Exception as e:
        print(f"Error compiling grammar: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == '__main__':
    sys.exit(main())
