# automatically generated by the FlatBuffers compiler, do not modify

# namespace: GrammarRules

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CommandVerb(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CommandVerb()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCommandVerb(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CommandVerb
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CommandVerb
    def Canonical(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CommandVerb
    def Synonyms(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # CommandVerb
    def SynonymsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CommandVerb
    def SynonymsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # CommandVerb
    def Intent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CommandVerb
    def RequiresObject(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CommandVerb
    def Frequency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CommandVerb
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # CommandVerb
    def PipelineCategory(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CommandVerbStart(builder):
    builder.StartObject(7)

def Start(builder):
    CommandVerbStart(builder)

def CommandVerbAddCanonical(builder, canonical):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(canonical), 0)

def AddCanonical(builder, canonical):
    CommandVerbAddCanonical(builder, canonical)

def CommandVerbAddSynonyms(builder, synonyms):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(synonyms), 0)

def AddSynonyms(builder, synonyms):
    CommandVerbAddSynonyms(builder, synonyms)

def CommandVerbStartSynonymsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSynonymsVector(builder, numElems):
    return CommandVerbStartSynonymsVector(builder, numElems)

def CommandVerbAddIntent(builder, intent):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(intent), 0)

def AddIntent(builder, intent):
    CommandVerbAddIntent(builder, intent)

def CommandVerbAddRequiresObject(builder, requiresObject):
    builder.PrependBoolSlot(3, requiresObject, 0)

def AddRequiresObject(builder, requiresObject):
    CommandVerbAddRequiresObject(builder, requiresObject)

def CommandVerbAddFrequency(builder, frequency):
    builder.PrependInt32Slot(4, frequency, 0)

def AddFrequency(builder, frequency):
    CommandVerbAddFrequency(builder, frequency)

def CommandVerbAddWeight(builder, weight):
    builder.PrependFloat32Slot(5, weight, 1.0)

def AddWeight(builder, weight):
    CommandVerbAddWeight(builder, weight)

def CommandVerbAddPipelineCategory(builder, pipelineCategory):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(pipelineCategory), 0)

def AddPipelineCategory(builder, pipelineCategory):
    CommandVerbAddPipelineCategory(builder, pipelineCategory)

def CommandVerbEnd(builder):
    return builder.EndObject()

def End(builder):
    return CommandVerbEnd(builder)
