# automatically generated by the FlatBuffers compiler, do not modify

# namespace: GrammarRules

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SentenceTemplate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SentenceTemplate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSentenceTemplate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SentenceTemplate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SentenceTemplate
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SentenceTemplate
    def Structure(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SentenceTemplate
    def Examples(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # SentenceTemplate
    def ExamplesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SentenceTemplate
    def ExamplesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # SentenceTemplate
    def RequiresContext(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SentenceTemplate
    def Category(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SentenceTemplate
    def Frequency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SentenceTemplate
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # SentenceTemplate
    def PipelineCategory(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SentenceTemplate
    def AvgDepth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SentenceTemplate
    def CommonModifiers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # SentenceTemplate
    def CommonModifiersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SentenceTemplate
    def CommonModifiersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

def SentenceTemplateStart(builder):
    builder.StartObject(10)

def Start(builder):
    SentenceTemplateStart(builder)

def SentenceTemplateAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    SentenceTemplateAddName(builder, name)

def SentenceTemplateAddStructure(builder, structure):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(structure), 0)

def AddStructure(builder, structure):
    SentenceTemplateAddStructure(builder, structure)

def SentenceTemplateAddExamples(builder, examples):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(examples), 0)

def AddExamples(builder, examples):
    SentenceTemplateAddExamples(builder, examples)

def SentenceTemplateStartExamplesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartExamplesVector(builder, numElems):
    return SentenceTemplateStartExamplesVector(builder, numElems)

def SentenceTemplateAddRequiresContext(builder, requiresContext):
    builder.PrependBoolSlot(3, requiresContext, 0)

def AddRequiresContext(builder, requiresContext):
    SentenceTemplateAddRequiresContext(builder, requiresContext)

def SentenceTemplateAddCategory(builder, category):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(category), 0)

def AddCategory(builder, category):
    SentenceTemplateAddCategory(builder, category)

def SentenceTemplateAddFrequency(builder, frequency):
    builder.PrependInt32Slot(5, frequency, 0)

def AddFrequency(builder, frequency):
    SentenceTemplateAddFrequency(builder, frequency)

def SentenceTemplateAddWeight(builder, weight):
    builder.PrependFloat32Slot(6, weight, 1.0)

def AddWeight(builder, weight):
    SentenceTemplateAddWeight(builder, weight)

def SentenceTemplateAddPipelineCategory(builder, pipelineCategory):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(pipelineCategory), 0)

def AddPipelineCategory(builder, pipelineCategory):
    SentenceTemplateAddPipelineCategory(builder, pipelineCategory)

def SentenceTemplateAddAvgDepth(builder, avgDepth):
    builder.PrependFloat32Slot(8, avgDepth, 0.0)

def AddAvgDepth(builder, avgDepth):
    SentenceTemplateAddAvgDepth(builder, avgDepth)

def SentenceTemplateAddCommonModifiers(builder, commonModifiers):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(commonModifiers), 0)

def AddCommonModifiers(builder, commonModifiers):
    SentenceTemplateAddCommonModifiers(builder, commonModifiers)

def SentenceTemplateStartCommonModifiersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCommonModifiersVector(builder, numElems):
    return SentenceTemplateStartCommonModifiersVector(builder, numElems)

def SentenceTemplateEnd(builder):
    return builder.EndObject()

def End(builder):
    return SentenceTemplateEnd(builder)
