//======================================================//
//  AtomTable.hpp
//  Atom Registry for GRIM Tokenizer/ScratchBlock Bridge
//  
//  The AtomTable stores the actual values of detected
//  structural atoms. When tokenization detects a URL,
//  number, etc., the raw value is stored here and a
//  placeholder token is emitted. ScratchBlock can then
//  query this table to get the parsed representation.
//  
//  Features:
//  - Type-safe atom storage and retrieval
//  - Parsing functions for each atom type
//  - GPU-friendly packed representation
//  - Thread-safe registry operations
//  
//  Author: GRIM Team
//  Date: December 2025
//======================================================//

#pragma once

#include "Unigram.hpp"  // For AtomType

#include <cuda_runtime.h>
#include <cstdint>
#include <memory>
#include <mutex>
#include <string>
#include <variant>
#include <vector>
#include <unordered_map>

namespace GRIM {
namespace Tokenizer {

// Forward declaration (defined in UniByte.hpp)
struct StructuralSpan;

//======================================================//
//  Parsed Atom Values
//======================================================//

// Integer atom: stores signed 64-bit value
struct AtomInteger {
    int64_t value;
    int base;  // 10, 16, 2, 8
    bool has_sign;
};

// Float atom: stores double-precision value
struct AtomFloat {
    double value;
    bool has_exponent;
    int exponent;
};

// URL atom: parsed components
struct AtomURL {
    std::string scheme;      // http, https, ftp
    std::string host;
    int port;                // -1 if not specified
    std::string path;
    std::string query;
    std::string fragment;
};

// Email atom: parsed components
struct AtomEmail {
    std::string local;       // before @
    std::string domain;      // after @
};

// Path atom: parsed components
struct AtomPath {
    bool is_absolute;
    bool is_windows;         // Uses backslashes
    std::vector<std::string> components;
    std::string extension;   // File extension if present
};

// Date atom: parsed components
struct AtomDate {
    int year;
    int month;
    int day;
    enum Format { ISO, US, EU } format;
};

// Time atom: parsed components
struct AtomTime {
    int hour;
    int minute;
    int second;
    bool is_24h;
    bool is_pm;  // Only valid if !is_24h
};

// IP Address atom
struct AtomIP {
    uint8_t octets[4];
    bool is_valid;
};

// String literal atom
struct AtomString {
    std::string value;       // Unescaped content
    char quote_char;         // ' or "
    bool has_escapes;
};

// Identifier atom
struct AtomIdentifier {
    std::string name;
    enum Style { SNAKE_CASE, CAMEL_CASE, PASCAL_CASE, SCREAMING_SNAKE, UNKNOWN } style;
};

// Generic/unknown atom
struct AtomGeneric {
    std::string raw_value;
};

//======================================================//
//  Atom Value Variant
//======================================================//
using AtomValue = std::variant<
    AtomInteger,
    AtomFloat,
    AtomURL,
    AtomEmail,
    AtomPath,
    AtomDate,
    AtomTime,
    AtomIP,
    AtomString,
    AtomIdentifier,
    AtomGeneric
>;

//======================================================//
//  Atom Origin - Where did this atom come from?
//======================================================//
enum class AtomOrigin : uint8_t {
    USER_INPUT,         // From user's input text
    MODEL_GENERATED,    // Generated by the model
    SYSTEM,             // System-injected (e.g., special tokens)
    TOOL_DERIVED,       // Derived from tool execution
    UNKNOWN
};

//======================================================//
//  Atom Category - High-level grouping
//======================================================//
enum class AtomCategory : uint8_t {
    NUMERIC,      // Numbers (integers, floats, hex, binary)
    TEMPORAL,     // Dates and times
    STRUCTURAL,   // URLs, emails, paths, IPs (formatted)
    STRING,       // String literals
    IDENTIFIER,   // Code identifiers (variable names, etc.)
    SYSTEM,       // Reserved/special atoms
    GENERIC       // Unknown/custom types
};

//======================================================//
//  String Pool Entry - References into global string pool
//======================================================//
struct StringRef {
    uint32_t offset;          // Offset in string pool
    uint32_t length;          // Length in bytes
    
    StringRef() : offset(0), length(0) {}
    StringRef(uint32_t off, uint32_t len) : offset(off), length(len) {}
};

//======================================================//
//  Atom Entry - 64-Byte Cache-Aligned Record
//  Fits exactly in one cache line for maximum performance
//======================================================//
struct alignas(64) AtomEntry {
    // --- Hot data (first 32 bytes) ---
    uint64_t hash;            // FNV-1a hash for deduplication (8 bytes)
    uint32_t id;              // Unique ID (4 bytes)
    AtomType type;            // Atom type (4 bytes)
    AtomCategory category;    // Category (1 byte)
    AtomOrigin origin;        // Origin (1 byte)
    uint8_t padding1[2];      // Alignment padding (2 bytes)
    
    StringRef raw_text_ref;   // Reference to string pool (8 bytes)
    float confidence;         // Model confidence (4 bytes)
    
    // --- Warm data (second 32 bytes) ---
    uint64_t created_at;      // Timestamp (8 bytes)
    uint32_t source_start;    // Position in original text (4 bytes)
    uint32_t source_end;      // End position (4 bytes)
    
    // GPU-packed numeric value and flags
    float numeric_value;      // For numeric types (4 bytes)
    uint32_t flags;           // Type-specific flags (4 bytes)
    
    StringRef parsed_ref;     // Reference to parsed string data (8 bytes)
    
    // Initialize to safe defaults
    AtomEntry() 
        : hash(0), id(0), type(AtomType::ATOM_IDENTIFIER), 
          category(AtomCategory::GENERIC), origin(AtomOrigin::USER_INPUT),
          padding1{0, 0}, raw_text_ref(), confidence(1.0f),
          created_at(0), source_start(0), source_end(0),
          numeric_value(0.0f), flags(0), parsed_ref() {}
};

static_assert(sizeof(AtomEntry) == 64, "AtomEntry must be exactly 64 bytes");

//======================================================//
//  Atom Parsing Result
//======================================================//
struct ParseResult {
    bool success;
    AtomValue value;
    std::string error_message;
};

//======================================================//
//  Atom Token ID Constants
//======================================================//
//======================================================//
//  AtomTable - Main Registry Class
//======================================================//
class AtomTable {
public:
    AtomTable();
    ~AtomTable();

    // Disable copy
    AtomTable(const AtomTable&) = delete;
    AtomTable& operator=(const AtomTable&) = delete;

    // Move support
    AtomTable(AtomTable&&) noexcept;
    AtomTable& operator=(AtomTable&&) noexcept;

    //--------------------------------------------------//
    // Registration
    //--------------------------------------------------//
    
    // Register a new atom from a detected span
    // Returns the atom ID (for lookup later)
    uint32_t registerAtom(AtomType type, 
                          std::string_view raw_text,
                          size_t source_start = 0,
                          size_t source_end = 0);
    
    // Register with pre-parsed value
    uint32_t registerAtom(AtomType type,
                          std::string_view raw_text,
                          const AtomValue& parsed_value,
                          size_t source_start = 0,
                          size_t source_end = 0);
    
    // Convenience: Register with AtomValue and raw text (tests use this form)
    uint32_t registerAtom(AtomType type,
                          const AtomValue& parsed_value,
                          std::string_view raw_text,
                          size_t source_start = 0,
                          size_t source_end = 0);
    
    // Register from StructuralSpan
    // Register from StructuralSpan (zero-copy!)
    uint32_t registerSpan(const StructuralSpan& span);

    // Try to register from StructuralSpan (no-throw when full).
    // Returns false if the table is full and the span is not already present.
    bool tryRegisterSpan(const StructuralSpan& span, uint32_t& out_id);

    //--------------------------------------------------//
    // Lookup
    //--------------------------------------------------//
    
    // Get atom by ID
    const AtomEntry* getAtom(uint32_t id) const;
    
    // Alias for getAtom (for API consistency)
    const AtomEntry* getAtomEntry(uint32_t id) const { return getAtom(id); }
    
    // Get all atoms of a specific type
    std::vector<const AtomEntry*> getAtomsByType(AtomType type) const;
    
    // Get atom count
    size_t size() const { return entries_.size(); }
    
    // Check if ID exists
    bool hasAtom(uint32_t id) const;

    //--------------------------------------------------//
    // Parsing
    //--------------------------------------------------//
    
    // Parse a raw text span into an AtomValue
    // This is the main parsing entry point
    static ParseResult parseAtom(AtomType type, const std::string& text);
    
    // Type-specific parsing functions
    static ParseResult parseInteger(const std::string& text);
    static ParseResult parseFloat(const std::string& text);
    static ParseResult parseHex(const std::string& text);
    static ParseResult parseBinary(const std::string& text);
    static ParseResult parseURL(const std::string& text);
    static ParseResult parseEmail(const std::string& text);
    static ParseResult parsePath(const std::string& text);
    static ParseResult parseDate(const std::string& text);
    static ParseResult parseTime(const std::string& text);
    static ParseResult parseIP(const std::string& text);
    static ParseResult parseStringLiteral(const std::string& text);
    static ParseResult parseIdentifier(const std::string& text);

    //--------------------------------------------------//
    // Serialization
    //--------------------------------------------------//
    
    // Convert atom back to string representation (needs string pool access)
    std::string atomToString(const AtomEntry& entry) const;
    
    // Serialize atom value directly to buffer (zero-copy!)
    // Returns number of bytes written
    static size_t atomValueSerialize(AtomType type, const AtomValue& value, char* out, size_t max);
    
    // String version (allocates - prefer atomValueSerialize for performance)
    static std::string atomValueToString(AtomType type, const AtomValue& value);
    
    // Get numeric value (for types that have one)
    static double getNumericValue(const AtomEntry& entry);
    static bool hasNumericValue(AtomType type);

    //--------------------------------------------------//
    // Metadata Helpers
    //--------------------------------------------------//
    
    // Compute category from type
    static AtomCategory getCategoryForType(AtomType type);
    
    // Compute hash for deduplication
    uint64_t computeHash(const AtomEntry& entry) const;
    static uint64_t computeHash(AtomType type, std::string_view raw_text);
    
    // Get current timestamp (microseconds since epoch)
    static uint64_t getCurrentTimestamp();
    
    // Update atom metadata
    void setOrigin(uint32_t id, AtomOrigin origin);
    void setConfidence(uint32_t id, float confidence);
    void setCategory(uint32_t id, AtomCategory category);

    //--------------------------------------------------//
    // GPU Transfer
    //--------------------------------------------------//
    
    // Pack atoms for GPU transfer (64-byte aligned, no string data)
    struct GPUAtomData {
        float* d_numeric_values;      // [num_atoms] - numeric values
        uint32_t* d_flags;            // [num_atoms] - type-specific flags
        uint32_t* d_types;            // [num_atoms] - atom types
        size_t num_atoms;
        
        GPUAtomData() 
            : d_numeric_values(nullptr)
            , d_flags(nullptr)
            , d_types(nullptr)
            , num_atoms(0) {}
    };
    
    // Upload current table to GPU (batch mode for performance)
    bool uploadToGPU(GPUAtomData& out_data, cudaStream_t stream = nullptr);
    
    // Convenience: Upload to internal GPU buffer (no-arg version)
    bool uploadToGPU(cudaStream_t stream = nullptr);
    
    // Get pointer to internal GPU data (valid after uploadToGPU())
    const GPUAtomData* getGPUBuffer() const { return &gpu_data_; }
    GPUAtomData* getGPUBuffer() { return &gpu_data_; }
    
    // Check if GPU data needs refresh
    bool isGPUDirty() const { return gpu_dirty_; }
    
    // Free GPU data
    static void freeGPUData(GPUAtomData& data);

    //--------------------------------------------------//
    // Lifecycle
    //--------------------------------------------------//
    
    void clear();
    void reserve(size_t count);
    bool saveToFile(const std::string& path) const;
    bool saveToTextFile(const std::string& path) const;
    bool loadFromFile(const std::string& path);
    static bool computeFileHash(const std::string& path, uint64_t& out_hash);
    
    //--------------------------------------------------//
    // String Pool Access
    //--------------------------------------------------//
    
    // Get string from pool by reference
    std::string_view getString(const StringRef& ref) const;
    
    // Get statistics
    size_t getStringPoolSize() const { return string_pool_.size(); }
    size_t getEntryCount() const { return entries_.size(); }
    size_t getDeduplicationHitRate() const;

private:
    // --- Core Storage ---
    std::vector<AtomEntry> entries_;              // Cache-aligned atom entries
    std::vector<char> string_pool_;               // Append-only string buffer
    std::unordered_map<uint64_t, uint32_t> hash_to_id_;  // Hash → ID for dedup
    std::unordered_map<AtomType, std::vector<uint32_t>> type_index_;  // Type → IDs
    
    uint32_t next_id_ = 0;
    size_t dedup_hits_ = 0;                       // Deduplication statistics
    size_t total_queries_ = 0;
    mutable std::mutex mutex_;
    
    // --- GPU Batch Upload State ---
    std::vector<uint32_t> pending_gpu_upload_;    // IDs waiting for upload
    bool gpu_dirty_ = false;
    GPUAtomData gpu_data_;                        // Internal GPU buffer storage
    
    // --- Helper Methods ---
    
    // String pool: append string and get reference
    StringRef internString(const std::string& str);
    StringRef internString(std::string_view sv);
    StringRef internString(const char* data, size_t length);
    
    // Deduplication: check if atom already exists
    // Returns existing ID if found, or UINT32_MAX if not
    uint32_t findExisting(uint64_t hash, std::string_view raw_text);
    
    // Pack numeric value for GPU (no string copying)
    void packNumericValue(AtomEntry& entry, const AtomValue& parsed);
};

//======================================================//
//  Inline Helpers
//======================================================//

// Get human-readable name for atom type
inline const char* atomTypeName(AtomType type) {
    switch (type) {
        case AtomType::ATOM_INTEGER: return "INTEGER";
        case AtomType::ATOM_FLOAT: return "FLOAT";
        case AtomType::ATOM_HEX: return "HEX";
        case AtomType::ATOM_BINARY: return "BINARY";
        case AtomType::ATOM_URL: return "URL";
        case AtomType::ATOM_EMAIL: return "EMAIL";
        case AtomType::ATOM_PATH: return "PATH";
        case AtomType::ATOM_DATE: return "DATE";
        case AtomType::ATOM_TIME: return "TIME";
        case AtomType::ATOM_IP_ADDRESS: return "IP";
        case AtomType::ATOM_STRING_LITERAL: return "STRING";
        case AtomType::ATOM_IDENTIFIER: return "IDENTIFIER";
        case AtomType::ATOM_REGEX: return "REGEX";
        case AtomType::ATOM_EQUATION: return "EQUATION";
        case AtomType::ATOM_EXPRESSION: return "EXPRESSION";
        default: return "UNKNOWN";
    }
}

// Check if atom type is numeric
inline bool isNumericAtom(AtomType type) {
    return type == AtomType::ATOM_INTEGER ||
           type == AtomType::ATOM_FLOAT ||
           type == AtomType::ATOM_HEX ||
           type == AtomType::ATOM_BINARY;
}

} // namespace Tokenizer
} // namespace GRIM
